/**
 * @generated by `cargo run -p usfm_galley --bin codegen` from
 * `galley/src/find/wire/schema.rs`. DO NOT EDIT — edit the schema, or this
 * template at `galley/find-reader.ts.tmpl`, and regenerate.
 * `galley/tests/codegen_output_matches_input.rs` fails the build if this file
 * is stale.
 *
 * The reader over one find buffer — what `find(id, …)` and `findAll(…)`
 * answer. Its writer is generated from the SAME declaration, so the two ends
 * of the wire cannot disagree, and no consumer learns a layout.
 *
 *   import { Hits } from "usfm-galley/find-reader";
 *
 *   const hits = Hits.open(galley.findAll("God", { wholeWord: true, limit: 200 }));
 *   for (let n = 0; n < hits.hitCount; n++) {
 *     const hit = hits.hit(n);
 *     highlight(hits.id(hit.bookIndex), hit.projectedFrom, hit.projectedTo);
 *     const pieces = hit.pieces();            // one per contiguous SOURCE range
 *     for (let p = 0; p < pieces.length; p++) {
 *       edit(pieces.seek(p).sourceFrom, pieces.seek(p).sourceTo);
 *     }
 *     card(hits.preview(n));
 *   }
 *
 * Every offset is UTF-16 — the unit an editor's coordinates are already in.
 * A hit carries two spaces because they are not the same interval: the
 * PROJECTED range is what a reader sees and a highlighter wants; the source
 * pieces are where an edit has to land, one per contiguous run, because the
 * bytes between two pieces are exactly the markup the projection dropped.
 * Whether that markup survives a replacement is the caller's decision, never
 * Find's.
 */

/** `FIND`, the four bytes in order. */
export const MAGIC = 0x444e4946;
/** The layout this reader knows. A buffer naming another one throws. */
export const FORMAT_VERSION = 1;

export const HEADER_BYTES = 16;
export const HEADER_MAGIC_OFFSET = 0;
export const HEADER_VERSION_OFFSET = 4;
export const HEADER_HIT_COUNT_OFFSET = 8;
export const HEADER_BOOK_COUNT_OFFSET = 12;

/** Bytes per row, from the same declaration the row classes below come from. */
export const HIT_HEAD_STRIDE = 16;
export const PIECE_STRIDE = 8;
export const ID_LEN_STRIDE = 4;
export const PREVIEW_LEN_STRIDE = 4;

/**
 * One hit: where a reader sees it, and where an editor would change it.
 *
 * 16 bytes per row head, then `pieceCount` × 8. A CURSOR: `seek` moves it and the getters read the
* row it is on. The row starts are found once, at construction; the
* tail accessor makes one view per call.
 */
export class HitRow {
  readonly #view: DataView;
  readonly #starts: Uint32Array;
  readonly #end: number;
  #row = 0;

  /**
   * A tailed block's row COUNT is not a function of its bytes, so the
   * envelope that framed it passes one; the walk stops at whichever comes
   * first, the count or the end of the view.
   */
  constructor(view: DataView, rows = Infinity) {
    this.#view = view;
    const starts: number[] = [];
    let at = 0;
    while (starts.length < rows && at + 16 <= view.byteLength) {
      starts.push(at);
      at += 16 + view.getUint32(at + 12, true) * 8;
    }
    this.#starts = Uint32Array.from(starts);
    this.#end = at;
  }

  /** Rows in the block. */
  get length(): number {
    return this.#starts.length;
  }

  /** Bytes those rows occupy: where the block ENDS. */
  get byteLength(): number {
    return this.#end;
  }

  /** Bytes of this row's HEAD; the run after it is `pieceCount` × 8. */
  readonly stride = 16;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    const at = this.#starts[n];
    if (at === undefined) {
      throw new RangeError(`row ${n} of ${this.#starts.length}`);
    }
    this.#row = at;
    return this;
  }

  /** Into the buffer's own id table, which names every book SEARCHED. */
  get bookIndex(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** First unit of the hit in the PROJECTION — what a highlighter wants. */
  get projectedFrom(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** One past its last unit. */
  get projectedTo(): number {
    return this.#view.getUint32(this.#row + 8, true);
  }

  /** Source pieces below; more than one where the hit crosses masked markup. */
  get pieceCount(): number {
    return this.#view.getUint32(this.#row + 12, true);
  }

  /** One contiguous source piece of a hit, in the raw book's UTF-16. */
  pieces(): PieceRow {
    const at = this.#row + 16;
    return new PieceRow(
      new DataView(this.#view.buffer, this.#view.byteOffset + at, this.pieceCount * 8),
    );
  }

}

/**
 * One contiguous source piece of a hit, in the raw book's UTF-16.
 *
 * 8 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class PieceRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 8;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 8;
    return this;
  }

  /** First unit of the piece in the SOURCE — where an edit lands. */
  get sourceFrom(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** One past its last unit. */
  get sourceTo(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

}

/**
 * One searched book's id length in bytes, in id-table order.
 *
 * 4 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class IdLenRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 4;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 4;
    return this;
  }

  /** Bytes of UTF-8 in the blob at the end of the buffer. */
  get idByteLen(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

}

/**
 * One hit's preview length in bytes, index-aligned with the hits.
 *
 * 4 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class PreviewLenRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 4;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 4;
    return this;
  }

  /** Bytes of UTF-8 in the blob at the end of the buffer. */
  get previewByteLen(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

}

const UTF8 = new TextDecoder();

/** One search's hits, and the two string tables they point into. */
export class Hits {
  readonly #bytes: Uint8Array;
  readonly #rows: HitRow;
  readonly #idLens: IdLenRow;
  readonly #previewLens: PreviewLenRow;
  readonly #blobAt: number;
  /** Hits in the buffer. */
  readonly hitCount: number;
  /** Books SEARCHED — not books that matched; every one is in the id table. */
  readonly bookCount: number;
  #idAt: Uint32Array | undefined;
  #previewAt: Uint32Array | undefined;

  private constructor(bytes: Uint8Array, view: DataView) {
    this.#bytes = bytes;
    this.hitCount = view.getUint32(HEADER_HIT_COUNT_OFFSET, true);
    this.bookCount = view.getUint32(HEADER_BOOK_COUNT_OFFSET, true);

    const slice = (at: number, bytes: number) =>
      new DataView(this.#bytes.buffer, this.#bytes.byteOffset + at, bytes);

    // A hit's length is a value it carries, so the rows are walked once — and
    // the walk is also what says where the two length arrays begin.
    this.#rows = new HitRow(
      slice(HEADER_BYTES, bytes.byteLength - HEADER_BYTES),
      this.hitCount,
    );
    const idLensAt = HEADER_BYTES + this.#rows.byteLength;
    const previewLensAt = idLensAt + this.bookCount * ID_LEN_STRIDE;
    this.#blobAt = previewLensAt + this.hitCount * PREVIEW_LEN_STRIDE;
    this.#idLens = new IdLenRow(slice(idLensAt, this.bookCount * ID_LEN_STRIDE));
    this.#previewLens = new PreviewLenRow(
      slice(previewLensAt, this.hitCount * PREVIEW_LEN_STRIDE),
    );
  }

  /**
   * Validate the envelope and take a view over it. Throws — loudly, naming
   * both versions — rather than misreading a buffer this reader predates.
   */
  static open(buffer: Uint8Array | ArrayBuffer): Hits {
    const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
    if (bytes.byteLength < HEADER_BYTES) {
      throw new Error(`find buffer is ${bytes.byteLength} bytes; the header alone is ${HEADER_BYTES}`);
    }
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const magic = view.getUint32(HEADER_MAGIC_OFFSET, true);
    if (magic !== MAGIC) {
      throw new Error(`not a find buffer: magic 0x${magic.toString(16).padStart(8, "0")}`);
    }
    const version = view.getUint32(HEADER_VERSION_OFFSET, true);
    if (version !== FORMAT_VERSION) {
      throw new Error(
        `this reader is FIND v${FORMAT_VERSION}; the buffer says v${version} — update usfm-galley`,
      );
    }
    return new Hits(bytes, view);
  }

  /** Hit `n`, as a cursor: its offsets, and `pieces()` for its source ranges. */
  hit(n: number): HitRow {
    if (n < 0 || n >= this.hitCount) throw new RangeError(`hit ${n} of ${this.hitCount}`);
    return this.#rows.seek(n);
  }

  /** The id of book `index` — a hit's `bookIndex`, or any book searched. */
  id(index: number): string {
    if (index < 0 || index >= this.bookCount) {
      throw new RangeError(`book ${index} of ${this.bookCount}`);
    }
    const at = this.#tables()[0][index];
    return UTF8.decode(this.#bytes.subarray(at, at + this.#idLens.seek(index).idByteLen));
  }

  /**
   * Hit `n`'s preview: the projected text around it, ellipsed and trimmed for
   * a result card. DISPLAY TEXT ONLY — never read an offset back out of it.
   */
  preview(n: number): string {
    if (n < 0 || n >= this.hitCount) throw new RangeError(`hit ${n} of ${this.hitCount}`);
    const at = this.#tables()[1][n];
    return UTF8.decode(
      this.#bytes.subarray(at, at + this.#previewLens.seek(n).previewByteLen),
    );
  }

  /** Every id, in the buffer's own book order. */
  ids(): string[] {
    return Array.from({ length: this.bookCount }, (_unused, index) => this.id(index));
  }

  /**
   * Where each id and each preview begins in the blob: one pass over the two
   * length arrays, on first use, so a caller that only highlights never pays
   * for the strings it did not ask for.
   */
  #tables(): [Uint32Array, Uint32Array] {
    if (!this.#idAt || !this.#previewAt) {
      const ids = new Uint32Array(this.bookCount);
      const previews = new Uint32Array(this.hitCount);
      let at = this.#blobAt;
      for (let n = 0; n < this.bookCount; n += 1) {
        ids[n] = at;
        at += this.#idLens.seek(n).idByteLen;
      }
      for (let n = 0; n < this.hitCount; n += 1) {
        previews[n] = at;
        at += this.#previewLens.seek(n).previewByteLen;
      }
      this.#idAt = ids;
      this.#previewAt = previews;
    }
    return [this.#idAt, this.#previewAt];
  }
}
