/**
 * @generated by `cargo run -p usfm_galley --bin codegen` from
 * `galley/src/mask/schema.rs`. DO NOT EDIT — edit the schema, or this template
 * at `galley/mask-reader.ts.tmpl`, and regenerate.
 * `galley/tests/codegen_output_matches_input.rs` fails the build if this file
 * is stale.
 *
 * The reader over one mask map — what `mask(id, …)` and `maskOf(text, …)`
 * answer. Its writer is generated from the SAME declaration, so the two ends
 * of the wire cannot disagree, and no consumer learns a layout.
 *
 *   import { MaskMap } from "usfm-galley/mask-reader";
 *
 *   const map = MaskMap.open(galley.mask("books/MRK.usfm", { utf16: true }));
 *   let projection = "";
 *   for (let n = 0; n < map.rangeCount; n++) {
 *     const r = map.range(n);
 *     projection += source.slice(r.sourceFrom, r.sourceTo);   // === verseText(id)
 *   }
 *   map.toSource(offset);            // where a projected offset sits in the source
 *   map.pieces(from, to);            // and where a projected SPAN does, one per run
 *
 * The projection is a pure CONCATENATION of source slices: nothing is
 * inserted between two ranges, so a host holding the source can rebuild the
 * reading from this map alone. `sourceLen` says which text the map was cut
 * from — compare it before joining slices out of a string that has moved on.
 */

/** `MASK`, the four bytes in order. */
export const MAGIC = 0x4b53414d;
/** The layout this reader knows. A buffer naming another one throws. */
export const FORMAT_VERSION = 1;
/** Header flag: every offset in the buffer is UTF-16 rather than a byte. */
export const FLAG_UTF16 = 1;

/** Which cut the ranges came from. */
export const RECIPE_VERSE_TEXT = 0;
export const RECIPE_STRUCTURE = 1;

export const HEADER_BYTES = 28;
export const HEADER_MAGIC_OFFSET = 0;
export const HEADER_VERSION_OFFSET = 4;
export const HEADER_FLAGS_OFFSET = 8;
export const HEADER_RECIPE_OFFSET = 12;
export const HEADER_RANGE_COUNT_OFFSET = 16;
export const HEADER_SOURCE_LEN_OFFSET = 20;
export const HEADER_PROJECTED_LEN_OFFSET = 24;

/** Bytes per row, from the same declaration the row class below comes from. */
export const RANGE_STRIDE = 8;

/**
 * One kept source span. Sorted, disjoint, non-empty, maximal.
 *
 * 8 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class RangeRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 8;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 8;
    return this;
  }

  /** First kept unit. */
  get sourceFrom(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** One past the last. */
  get sourceTo(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

}

/** One source span as a plain pair, which is what `pieces` hands back. */
export type Piece = [from: number, to: number];

/** One book's map: which source spans the projection is made of, in order. */
export class MaskMap {
  readonly #rows: RangeRow;
  /** Kept spans in the buffer. */
  readonly rangeCount: number;
  /** The header's raw flag word; read [`utf16`](#utf16) rather than this. */
  readonly flags: number;
  /** `"verseText"` or `"structure"` — which cut these ranges came from. */
  readonly recipe: string;
  /** The length of the text the ranges were cut from, in this buffer's unit. */
  readonly sourceLen: number;
  /** The length of the projection they concatenate to, in the same unit. */
  readonly projectedLen: number;
  /**
   * Where each range begins in the PROJECTION: the prefix sum of the range
   * lengths, built in one pass at open rather than shipped, since it is four
   * bytes a range for a value this loop derives in microseconds.
   */
  readonly starts: Uint32Array;

  private constructor(bytes: Uint8Array, view: DataView) {
    this.flags = view.getUint32(HEADER_FLAGS_OFFSET, true);
    this.rangeCount = view.getUint32(HEADER_RANGE_COUNT_OFFSET, true);
    this.sourceLen = view.getUint32(HEADER_SOURCE_LEN_OFFSET, true);
    this.projectedLen = view.getUint32(HEADER_PROJECTED_LEN_OFFSET, true);
    this.recipe =
      view.getUint32(HEADER_RECIPE_OFFSET, true) === RECIPE_STRUCTURE ? "structure" : "verseText";
    this.#rows = new RangeRow(
      new DataView(bytes.buffer, bytes.byteOffset + HEADER_BYTES, this.rangeCount * RANGE_STRIDE),
    );
    const starts = new Uint32Array(this.rangeCount);
    let at = 0;
    for (let n = 0; n < this.rangeCount; n += 1) {
      starts[n] = at;
      const row = this.#rows.seek(n);
      at += row.sourceTo - row.sourceFrom;
    }
    this.starts = starts;
  }

  /**
   * Validate the envelope and take a view over it. Throws — loudly, naming
   * both versions — rather than misreading a buffer this reader predates.
   */
  static open(buffer: Uint8Array | ArrayBuffer): MaskMap {
    const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
    if (bytes.byteLength < HEADER_BYTES) {
      throw new Error(`mask buffer is ${bytes.byteLength} bytes; the header alone is ${HEADER_BYTES}`);
    }
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const magic = view.getUint32(HEADER_MAGIC_OFFSET, true);
    if (magic !== MAGIC) {
      throw new Error(`not a mask buffer: magic 0x${magic.toString(16).padStart(8, "0")}`);
    }
    const version = view.getUint32(HEADER_VERSION_OFFSET, true);
    if (version !== FORMAT_VERSION) {
      throw new Error(
        `this reader is MASK v${FORMAT_VERSION}; the buffer says v${version} — update usfm-galley`,
      );
    }
    // There is no stride word to disagree with: the rows ARE the rest of the
    // buffer, so a stride this reader does not share shows up as a block that
    // does not fit the count the header states.
    const rows = view.getUint32(HEADER_RANGE_COUNT_OFFSET, true) * RANGE_STRIDE;
    if (bytes.byteLength < HEADER_BYTES + rows) {
      throw new Error(
        `mask buffer holds ${bytes.byteLength - HEADER_BYTES} bytes of rows; ` +
          `${view.getUint32(HEADER_RANGE_COUNT_OFFSET, true)} × ${RANGE_STRIDE} is ${rows}`,
      );
    }
    return new MaskMap(bytes, view);
  }

  /** Whether every offset in the buffer is UTF-16 rather than a byte. */
  get utf16(): boolean {
    return (this.flags & FLAG_UTF16) !== 0;
  }

  /** Range `n`, as the shared cursor — read it before seeking again. */
  range(n: number): RangeRow {
    if (n < 0 || n >= this.rangeCount) throw new RangeError(`range ${n} of ${this.rangeCount}`);
    return this.#rows.seek(n);
  }

  /**
   * The source offset a projected offset names. TOTAL: the projection's own
   * length answers the end of the last range, and anything past it clamps
   * there.
   */
  toSource(projected: number): number {
    if (this.rangeCount === 0) return 0;
    const at = Math.min(projected, this.projectedLen);
    const row = this.#rowOf(at);
    return this.range(row).sourceFrom + (at - this.starts[row]);
  }

  /**
   * The source spans a projected interval covers, one per kept range it
   * touches — the same answer a find hit's `pieces()` carries, because the
   * bytes between two spans are exactly the markup the projection dropped.
   */
  pieces(from: number, to: number): Piece[] {
    // Past the projection there is nothing to name; `to` past it clamps.
    if (to <= from || from >= this.projectedLen) return [];
    const out: Piece[] = [];
    let row = this.#rowOf(from);
    let cursor = from;
    while (cursor < to && row < this.rangeCount) {
      const range = this.range(row);
      const start = this.starts[row];
      const end = start + (range.sourceTo - range.sourceFrom);
      const stop = Math.min(to, end);
      out.push([range.sourceFrom + (cursor - start), range.sourceFrom + (stop - start)]);
      cursor = stop;
      row += 1;
    }
    return out;
  }

  /** The last range beginning at or before `at` — binary search on `starts`. */
  #rowOf(at: number): number {
    let low = 0;
    let high = this.rangeCount;
    while (low < high) {
      const mid = (low + high) >> 1;
      if (this.starts[mid] <= at) low = mid + 1;
      else high = mid;
    }
    return low === 0 ? 0 : low - 1;
  }

  /** Every range as a plain pair, for a caller that wants the array. */
  *[Symbol.iterator](): IterableIterator<Piece> {
    for (let n = 0; n < this.rangeCount; n += 1) {
      const row = this.range(n);
      yield [row.sourceFrom, row.sourceTo];
    }
  }
}
