/**
 * @generated by `cargo run -p usfm_galley --bin codegen` from
 * `galley/src/sous/settings.rs`. DO NOT EDIT.
 *
 * ```text
 * const values = fromSettings(galley);      // { placement: true, …, support_floor: 5, … }
 * toSettings(galley, { ...values, doubled_separated: true });
 * SOUS_SETTINGS.support_floor.description   // "How many times something must occur…"
 * ```
 *
 * A setting kitchen adds, removes, or retypes changes `SousSettingsValues`, so
 * a host that restates it fails to compile rather than missing it.
 */

import type { SousSettings as BundlerSettings } from "./pkg-bundler/usfm_galley.js";
import type { SousSettings as WebSettings } from "./pkg-web/usfm_galley.js";

export type SettingKey =
  | "placement"
  | "run_shape"
  | "exact_neighbor"
  | "pooled_neighbor"
  | "rarity"
  | "casing"
  | "word_length"
  | "doubled"
  | "letter_runs"
  | "sentence_start"
  | "book_rate"
  | "support_floor"
  | "word_support_floor"
  | "terminal_upper_share_bp"
  | "terminal_lower_share_bp"
  | "sentence_start_upper_bp"
  | "word_length_sigma"
  | "doubles_productive_bp"
  | "doubled_bare"
  | "doubled_separated"
  | "book_rate_ratio"
  | "book_rate_min_bp"
  | "book_rate_min_uses"
  | "z_long"
  | "z_short"
  | "min_verses"
  | "lengths_enabled"
  | "presence"
  | "source_copy"
  | "source_copy_min_run";

/** Every setting, as the wasm `SousSettings` class types it. */
export interface SousSettingsValues {
  readonly placement: boolean;
  readonly run_shape: boolean;
  readonly exact_neighbor: boolean;
  readonly pooled_neighbor: boolean;
  readonly rarity: boolean;
  readonly casing: boolean;
  readonly word_length: boolean;
  readonly doubled: boolean;
  readonly letter_runs: boolean;
  readonly sentence_start: boolean;
  readonly book_rate: boolean;
  readonly support_floor: number;
  readonly word_support_floor: number;
  readonly terminal_upper_share_bp: number;
  readonly terminal_lower_share_bp: number;
  readonly sentence_start_upper_bp: number;
  readonly word_length_sigma: number;
  readonly doubles_productive_bp: number;
  readonly doubled_bare: boolean;
  readonly doubled_separated: boolean;
  readonly book_rate_ratio: number;
  readonly book_rate_min_bp: number;
  readonly book_rate_min_uses: number;
  readonly z_long: number;
  readonly z_short: number;
  readonly min_verses: number;
  readonly lengths_enabled: boolean;
  readonly presence: boolean;
  readonly source_copy: boolean;
  readonly source_copy_min_run: number;
}

export type SettingKind = "switch" | "count" | "share-bp" | "decimal";
export type SettingGroup = "rules" | "thresholds" | "reference";

export interface SettingSpec<K extends SettingKey> {
  readonly key: K;
  /** A share-bp is out of 10,000. */
  readonly kind: SettingKind;
  readonly default: SousSettingsValues[K];
  readonly min?: number;
  readonly max?: number;
  readonly group: SettingGroup;
  readonly label: string;
  /** One plain sentence: what the check looks for. */
  readonly description: string;
}

export const SETTING_KEYS: readonly SettingKey[] = [
  "placement",
  "run_shape",
  "exact_neighbor",
  "pooled_neighbor",
  "rarity",
  "casing",
  "word_length",
  "doubled",
  "letter_runs",
  "sentence_start",
  "book_rate",
  "support_floor",
  "word_support_floor",
  "terminal_upper_share_bp",
  "terminal_lower_share_bp",
  "sentence_start_upper_bp",
  "word_length_sigma",
  "doubles_productive_bp",
  "doubled_bare",
  "doubled_separated",
  "book_rate_ratio",
  "book_rate_min_bp",
  "book_rate_min_uses",
  "z_long",
  "z_short",
  "min_verses",
  "lengths_enabled",
  "presence",
  "source_copy",
  "source_copy_min_run",
];

export const SOUS_SETTINGS: { readonly [K in SettingKey]: SettingSpec<K> } = {
  placement: {
    key: "placement",
    kind: "switch",
    default: true,
    group: "rules",
    label: "What a mark touches",
    description:
      "Flags a punctuation mark or digit right next to something it is rarely next to in this project, like a comma touching the next word, by counting every use of that mark across the whole project.",
  },
  run_shape: {
    key: "run_shape",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Groups of marks",
    description:
      "Flags a group of marks written together, like “;'”, when this project rarely groups that mark that way and does not write that exact group often.",
  },
  exact_neighbor: {
    key: "exact_neighbor",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Pairs of marks",
    description:
      "Flags two marks side by side, like “?,”, when this project almost never puts the second one right after the first.",
  },
  pooled_neighbor: {
    key: "pooled_neighbor",
    kind: "switch",
    default: false,
    group: "rules",
    label: "A mark and the kind of mark after it",
    description:
      "Flags a mark followed directly by a kind of mark, such as a quotation mark or a dash, that rarely follows it in this project; off by default because the pairs check already covers it.",
  },
  rarity: {
    key: "rarity",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Rare characters",
    description:
      "Lists characters this project uses only a handful of times in all its books, like a curly apostrophe in a project that otherwise uses straight ones.",
  },
  casing: {
    key: "casing",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Capital letters",
    description:
      "Flags a word capitalized, or not, in a way this project rarely writes that word in the middle of a sentence, like “On” where the project writes “on”.",
  },
  word_length: {
    key: "word_length",
    kind: "switch",
    default: false,
    group: "rules",
    label: "Very long words",
    description:
      "Flags words far longer than the words this project usually uses, which can mean two words ran together; off by default because long names are common.",
  },
  doubled: {
    key: "doubled",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Doubled words",
    description:
      "Turns every check for a word written twice in a row on or off.",
  },
  letter_runs: {
    key: "letter_runs",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Repeated letters",
    description:
      "Flags a letter written more times in a row than this project ever writes it, like “joyfullly”.",
  },
  sentence_start: {
    key: "sentence_start",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Lowercase after a sentence end",
    description:
      "Flags a lowercase word right after a mark, like “?” or “!”, that this project almost always follows with a capital.",
  },
  book_rate: {
    key: "book_rate",
    kind: "switch",
    default: true,
    group: "rules",
    label: "One book differs",
    description:
      "Flags one book that puts a mark next to something far more often than the project's other books do, like a dash after a space in one book only.",
  },
  support_floor: {
    key: "support_floor",
    kind: "count",
    default: 5,
    min: 1,
    max: 4294967295,
    group: "thresholds",
    label: "Habit count",
    description:
      "How many times something must occur before the checks treat it as a habit of this project rather than a one-off.",
  },
  word_support_floor: {
    key: "word_support_floor",
    kind: "count",
    default: 20,
    min: 1,
    max: 4294967295,
    group: "thresholds",
    label: "Word habit count",
    description:
      "How many times a word must appear in the middle of a sentence before the capital-letter check compares its spellings.",
  },
  terminal_upper_share_bp: {
    key: "terminal_upper_share_bp",
    kind: "share-bp",
    default: 8000,
    min: 0,
    max: 10000,
    group: "thresholds",
    label: "Capital after a mark",
    description:
      "How often this project must follow a mark with a capital before a capital there counts as the mark's doing and not the word's.",
  },
  terminal_lower_share_bp: {
    key: "terminal_lower_share_bp",
    kind: "share-bp",
    default: 2000,
    min: 0,
    max: 10000,
    group: "thresholds",
    label: "Capital left to the word",
    description:
      "How rarely this project may follow a mark with a capital for the capital-letter check to still judge the word after it; a mark followed by capitals more often than this, but not often enough to count as the mark's doing, is skipped.",
  },
  sentence_start_upper_bp: {
    key: "sentence_start_upper_bp",
    kind: "share-bp",
    default: 9800,
    min: 0,
    max: 10000,
    group: "thresholds",
    label: "Capital expected after a mark",
    description:
      "How often this project must follow a mark with a capital before a lowercase word after that mark is flagged.",
  },
  word_length_sigma: {
    key: "word_length_sigma",
    kind: "count",
    default: 4,
    min: 1,
    max: 255,
    group: "thresholds",
    label: "How long a very long word is",
    description:
      "How far past this project's usual word length a word must be, counted in steps of how much word lengths usually vary, before the long-word check flags it.",
  },
  doubles_productive_bp: {
    key: "doubles_productive_bp",
    kind: "share-bp",
    default: 300,
    min: 0,
    max: 10000,
    group: "thresholds",
    label: "Repeating language",
    description:
      "When more than this share of the different words in the project are written twice in a row more than once, the project is taken to repeat words on purpose and the doubled-word checks stay silent.",
  },
  doubled_bare: {
    key: "doubled_bare",
    kind: "switch",
    default: true,
    group: "rules",
    label: "Doubled with a space",
    description:
      "Flags a word written twice in a row with only a space between, like “the the”, unless this project does that with the word often.",
  },
  doubled_separated: {
    key: "doubled_separated",
    kind: "switch",
    default: false,
    group: "rules",
    label: "Doubled with punctuation",
    description:
      "Flags a word written twice with punctuation between, like “Moses, Moses”, unless this project does that with the word often; off by default because calling someone by name twice is common.",
  },
  book_rate_ratio: {
    key: "book_rate_ratio",
    kind: "count",
    default: 10,
    min: 1,
    max: 65535,
    group: "thresholds",
    label: "One book: how many times more",
    description:
      "How many times more often than the other books typically do one book must put a mark next to something before the one-book check flags it.",
  },
  book_rate_min_bp: {
    key: "book_rate_min_bp",
    kind: "share-bp",
    default: 4000,
    min: 0,
    max: 10000,
    group: "thresholds",
    label: "One book: least share",
    description:
      "The least share of a mark's uses in one book that must be next to the same thing before the one-book check flags that book.",
  },
  book_rate_min_uses: {
    key: "book_rate_min_uses",
    kind: "count",
    default: 100,
    min: 1,
    max: 4294967295,
    group: "thresholds",
    label: "One book: least uses",
    description:
      "How many times a book must use a mark before the one-book check may flag that book for it.",
  },
  z_long: {
    key: "z_long",
    kind: "decimal",
    default: 3.5,
    min: 0,
    group: "reference",
    label: "Long verse distance",
    description:
      "How far past this project's usual length compared with the source a verse must be, on the long side, before it is flagged as much longer.",
  },
  z_short: {
    key: "z_short",
    kind: "decimal",
    default: 3.5,
    min: 0,
    group: "reference",
    label: "Short verse distance",
    description:
      "How far short of this project's usual length compared with the source a verse must be before it is flagged as much shorter.",
  },
  min_verses: {
    key: "min_verses",
    kind: "count",
    default: 50,
    min: 0,
    max: 4294967295,
    group: "reference",
    label: "Verses to compare a book",
    description:
      "How many verses a book must share with the source before its verse lengths are compared within that book as well as across the project.",
  },
  lengths_enabled: {
    key: "lengths_enabled",
    kind: "switch",
    default: true,
    group: "reference",
    label: "Verse lengths",
    description:
      "Compares each verse's length with the same verse in the source text and flags verses much longer or shorter than this project usually is.",
  },
  presence: {
    key: "presence",
    kind: "switch",
    default: true,
    group: "reference",
    label: "Missing and extra verses",
    description:
      "Flags verses the source text has and this book lacks, verses this book has and the source lacks, and verses left empty.",
  },
  source_copy: {
    key: "source_copy",
    kind: "switch",
    default: false,
    group: "reference",
    label: "Copied source words",
    description:
      "Flags words in a row spelled exactly as in the same verse of the source text, which can mean source text was pasted in; off by default.",
  },
  source_copy_min_run: {
    key: "source_copy_min_run",
    kind: "count",
    default: 3,
    min: 2,
    max: 4294967295,
    group: "reference",
    label: "Copied words in a row",
    description:
      "How many words in a row must match the source verse before the copied-words check flags them.",
  },
};

type DataKey<T> = { [K in keyof T]: T[K] extends (...args: never[]) => unknown ? never : K }[keyof T];
type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Field<C, K> = K extends keyof C ? C[K] : never;
type Retyped<C> = { [K in SettingKey]: Same<SousSettingsValues[K], Field<C, K>> extends true ? never : K }[SettingKey];
type ExactlyTheClass<C> = Same<SettingKey, DataKey<C>> extends true ? ([Retyped<C>] extends [never] ? true : false) : false;
// Fails to compile when this file and either build's `SousSettings` disagree.
const exactlyTheClass: [ExactlyTheClass<BundlerSettings>, ExactlyTheClass<WebSettings>] = [true, true];
void exactlyTheClass;

/** The settings handle `Galley.config()` hands out, in either build. */
export type SettingsHandle = { -readonly [K in SettingKey]: SousSettingsValues[K] } & { free(): void };

/** What `toSettings` and `fromSettings` need of a `Galley`, from either build. */
export interface SettingsHost {
  config(): SettingsHandle;
  setConfig(settings: SettingsHandle): void;
}

/** A copy of the settings the next publication judges with. */
export function fromSettings(galley: SettingsHost): SousSettingsValues {
  const handle = galley.config();
  try {
    return {
      placement: handle.placement,
      run_shape: handle.run_shape,
      exact_neighbor: handle.exact_neighbor,
      pooled_neighbor: handle.pooled_neighbor,
      rarity: handle.rarity,
      casing: handle.casing,
      word_length: handle.word_length,
      doubled: handle.doubled,
      letter_runs: handle.letter_runs,
      sentence_start: handle.sentence_start,
      book_rate: handle.book_rate,
      support_floor: handle.support_floor,
      word_support_floor: handle.word_support_floor,
      terminal_upper_share_bp: handle.terminal_upper_share_bp,
      terminal_lower_share_bp: handle.terminal_lower_share_bp,
      sentence_start_upper_bp: handle.sentence_start_upper_bp,
      word_length_sigma: handle.word_length_sigma,
      doubles_productive_bp: handle.doubles_productive_bp,
      doubled_bare: handle.doubled_bare,
      doubled_separated: handle.doubled_separated,
      book_rate_ratio: handle.book_rate_ratio,
      book_rate_min_bp: handle.book_rate_min_bp,
      book_rate_min_uses: handle.book_rate_min_uses,
      z_long: handle.z_long,
      z_short: handle.z_short,
      min_verses: handle.min_verses,
      lengths_enabled: handle.lengths_enabled,
      presence: handle.presence,
      source_copy: handle.source_copy,
      source_copy_min_run: handle.source_copy_min_run,
    };
  } finally {
    handle.free();
  }
}

/** Replaces every setting; the next publication judges with them. */
export function toSettings(galley: SettingsHost, values: SousSettingsValues): void {
  const handle = galley.config();
  try {
    handle.placement = values.placement;
    handle.run_shape = values.run_shape;
    handle.exact_neighbor = values.exact_neighbor;
    handle.pooled_neighbor = values.pooled_neighbor;
    handle.rarity = values.rarity;
    handle.casing = values.casing;
    handle.word_length = values.word_length;
    handle.doubled = values.doubled;
    handle.letter_runs = values.letter_runs;
    handle.sentence_start = values.sentence_start;
    handle.book_rate = values.book_rate;
    handle.support_floor = values.support_floor;
    handle.word_support_floor = values.word_support_floor;
    handle.terminal_upper_share_bp = values.terminal_upper_share_bp;
    handle.terminal_lower_share_bp = values.terminal_lower_share_bp;
    handle.sentence_start_upper_bp = values.sentence_start_upper_bp;
    handle.word_length_sigma = values.word_length_sigma;
    handle.doubles_productive_bp = values.doubles_productive_bp;
    handle.doubled_bare = values.doubled_bare;
    handle.doubled_separated = values.doubled_separated;
    handle.book_rate_ratio = values.book_rate_ratio;
    handle.book_rate_min_bp = values.book_rate_min_bp;
    handle.book_rate_min_uses = values.book_rate_min_uses;
    handle.z_long = values.z_long;
    handle.z_short = values.z_short;
    handle.min_verses = values.min_verses;
    handle.lengths_enabled = values.lengths_enabled;
    handle.presence = values.presence;
    handle.source_copy = values.source_copy;
    handle.source_copy_min_run = values.source_copy_min_run;
  } catch (error) {
    handle.free();
    throw error;
  }
  // `setConfig` takes the handle; nothing is left to free.
  galley.setConfig(handle);
}
