/**
 * @generated by `cargo run -p usfm_galley --bin codegen` from
 * `galley/src/toc/schema.rs`. DO NOT EDIT — edit the schema, or this template
 * at `galley/toc-reader.ts.tmpl`, and regenerate.
 * `galley/tests/codegen_output_matches_input.rs` fails the build if this file
 * is stale.
 *
 * The reader over one census buffer — what `galley.toc(id)` and
 * `galley.tocAll()` answer. Its writer is generated from the SAME declaration,
 * so the two ends of the wire cannot disagree, and no consumer ever learns a
 * layout.
 *
 *   import { Census } from "usfm-galley/toc-reader";
 *
 *   const census = Census.open(galley.tocAll());
 *   for (const book of census) {
 *     sidebar.add(book.code, book.chapters, book.verseCount);
 *   }
 *
 * Lazy on purpose: opening validates the envelope and nothing else, and a row
 * is decoded only when something asks for it. A sidebar over 66 books reads 66
 * directory entries and no verse row at all.
 */

/** `TOCS`, the four bytes in order. */
export const MAGIC = 0x53434f54;
/** The layout this reader knows. A buffer naming another one throws. */
export const FORMAT_VERSION = 1;
/** Header flag: every offset in the buffer is UTF-16 rather than a byte. */
export const FLAG_UTF16 = 1;

export const HEADER_BYTES = 28;
export const HEADER_MAGIC_OFFSET = 0;
export const HEADER_VERSION_OFFSET = 4;
export const HEADER_FLAGS_OFFSET = 8;
export const HEADER_BOOK_COUNT_OFFSET = 12;
export const HEADER_CHAPTER_STRIDE_OFFSET = 16;
export const HEADER_VERSE_STRIDE_OFFSET = 20;
export const HEADER_DIRECTORY_AT_OFFSET = 24;

export const DIRECTORY_ENTRY_BYTES = 28;
export const DIRECTORY_CODE_OFFSET = 0;
export const DIRECTORY_CHAPTERS_AT_OFFSET = 4;
export const DIRECTORY_CHAPTER_ROWS_OFFSET = 8;
export const DIRECTORY_VERSES_AT_OFFSET = 12;
export const DIRECTORY_VERSE_ROWS_OFFSET = 16;
export const DIRECTORY_ID_AT_OFFSET = 20;
export const DIRECTORY_ID_LEN_OFFSET = 24;

/** Bytes per row, from the same declaration the row classes below come from. */
export const CHAPTER_STRIDE = 14;
export const VERSE_STRIDE = 10;

/**
 * One chapter's extent, its number, and what its verses count to.
 *
 * 14 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class ChapterRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 14;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 14;
    return this;
  }

  /** First byte of the `\c` marker; 0 on the front-matter row. */
  get start(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** One past the chapter's last byte. Rows TILE the book. */
  get end(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** The number read, or 0 — absent, malformed, or row 0's front matter. */
  get number(): number {
    return this.#view.getUint16(this.#row + 8, true);
  }

  /** How many `\v` markers sit inside this chapter's span, saturating. */
  get anchors(): number {
    return this.#view.getUint16(this.#row + 10, true);
  }

  /** The highest verse number those anchors name; 0 when none does. A bridge `\v 5-7` is one anchor reaching 7 — so this is the count that keys by NUMBER where `anchors` counts MARKERS. */
  get lastVerse(): number {
    return this.#view.getUint16(this.#row + 12, true);
  }

}

/**
 * One verse anchor and the range of verse numbers it names.
 *
 * 10 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class VerseRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 10;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 10;
    return this;
  }

  /** First byte of the `\v` marker. */
  get at(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** The number of the chapter row whose span CONTAINS this anchor — position, never the designator. */
  get chapter(): number {
    return this.#view.getUint16(this.#row + 4, true);
  }

  /** Lowest verse named; 0 when the designator is absent or malformed. */
  get first(): number {
    return this.#view.getUint16(this.#row + 6, true);
  }

  /** Highest named — equal to `first` unless this is a bridge. */
  get last(): number {
    return this.#view.getUint16(this.#row + 8, true);
  }

}

const UTF8 = new TextDecoder();

/** One book's entry in the directory, and cursors over its two row blocks. */
export class BookCensus {
  readonly #bytes: Uint8Array;
  readonly #view: DataView;
  readonly #at: number;

  constructor(bytes: Uint8Array, view: DataView, at: number) {
    this.#bytes = bytes;
    this.#view = view;
    this.#at = at;
  }

  /** The `\id` code, three bytes as they were written: `"GEN"`. */
  get code(): string {
    const at = this.#at + DIRECTORY_CODE_OFFSET;
    let end = at;
    while (end < at + 3 && this.#bytes[end] !== 0) end += 1;
    return UTF8.decode(this.#bytes.subarray(at, end));
  }

  /** The opaque id the host registered the book under — a path, in practice. */
  get id(): string {
    const at = this.#view.getUint32(this.#at + DIRECTORY_ID_AT_OFFSET, true);
    const len = this.#view.getUint32(this.#at + DIRECTORY_ID_LEN_OFFSET, true);
    return UTF8.decode(this.#bytes.subarray(at, at + len));
  }

  /**
   * Chapter rows in the buffer, the synthetic front-matter row included. Row 0
   * is ALWAYS that row: it carries the bytes before the first `\c`, which is
   * what makes the rows tile the book.
   */
  get chapterCount(): number {
    return this.#view.getUint32(this.#at + DIRECTORY_CHAPTER_ROWS_OFFSET, true);
  }

  /** `\c` markers in the book — [`chapterCount`](#chapterCount) less row 0. */
  get chapters(): number {
    return Math.max(0, this.chapterCount - 1);
  }

  /**
   * `\v` markers in the book. NOT the number of verses: a bridge `\v 5-7` is
   * one anchor naming three, which is why a chapter row carries both
   * `anchors` and `lastVerse` and this reader picks neither for you.
   */
  get verseCount(): number {
    return this.#view.getUint32(this.#at + DIRECTORY_VERSE_ROWS_OFFSET, true);
  }

  /** A cursor over this book's chapter rows. */
  get chapterRows(): ChapterRow {
    return new ChapterRow(this.#block(DIRECTORY_CHAPTERS_AT_OFFSET, this.chapterCount, CHAPTER_STRIDE));
  }

  /** A cursor over this book's verse anchors, in source order. */
  get verseRows(): VerseRow {
    return new VerseRow(this.#block(DIRECTORY_VERSES_AT_OFFSET, this.verseCount, VERSE_STRIDE));
  }

  #block(offset: number, rows: number, stride: number): DataView {
    const at = this.#view.getUint32(this.#at + offset, true);
    return new DataView(this.#bytes.buffer, this.#bytes.byteOffset + at, rows * stride);
  }
}

/** One census buffer: the books a `toc` or `tocAll` call was asked about. */
export class Census {
  readonly #bytes: Uint8Array;
  readonly #view: DataView;
  readonly #directoryAt: number;
  /** How many books the buffer describes. */
  readonly bookCount: number;
  /** The header's raw flag word; read [`utf16`](#utf16) rather than this. */
  readonly flags: number;

  private constructor(bytes: Uint8Array, view: DataView) {
    this.#bytes = bytes;
    this.#view = view;
    this.flags = view.getUint32(HEADER_FLAGS_OFFSET, true);
    this.bookCount = view.getUint32(HEADER_BOOK_COUNT_OFFSET, true);
    this.#directoryAt = view.getUint32(HEADER_DIRECTORY_AT_OFFSET, true);
  }

  /**
   * Validate the envelope and take a view over it. Throws — loudly, naming
   * both versions — rather than misreading a buffer this reader predates.
   */
  static open(buffer: Uint8Array | ArrayBuffer): Census {
    const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
    if (bytes.byteLength < HEADER_BYTES) {
      throw new Error(`census buffer is ${bytes.byteLength} bytes; the header alone is ${HEADER_BYTES}`);
    }
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const magic = view.getUint32(HEADER_MAGIC_OFFSET, true);
    if (magic !== MAGIC) {
      throw new Error(`not a census buffer: magic 0x${magic.toString(16).padStart(8, "0")}`);
    }
    const version = view.getUint32(HEADER_VERSION_OFFSET, true);
    if (version !== FORMAT_VERSION) {
      throw new Error(
        `this reader is TOCS v${FORMAT_VERSION}; the buffer says v${version} — update usfm-galley`,
      );
    }
    const strides: [string, number, number][] = [
      ["Chapter", HEADER_CHAPTER_STRIDE_OFFSET, CHAPTER_STRIDE],
      ["Verse", HEADER_VERSE_STRIDE_OFFSET, VERSE_STRIDE],
    ];
    for (const [name, at, known] of strides) {
      const stride = view.getUint32(at, true);
      if (stride !== known) {
        throw new Error(`${name} rows are ${stride} bytes in this buffer and ${known} in this reader`);
      }
    }
    return new Census(bytes, view);
  }

  /** Whether every offset in the buffer is UTF-16 rather than a byte. */
  get utf16(): boolean {
    return (this.flags & FLAG_UTF16) !== 0;
  }

  /** Book `n`, in the order the call was asked about — canonical, for `tocAll`. */
  book(n: number): BookCensus {
    if (n < 0 || n >= this.bookCount) {
      throw new RangeError(`book ${n} of ${this.bookCount}`);
    }
    return new BookCensus(this.#bytes, this.#view, this.#directoryAt + n * DIRECTORY_ENTRY_BYTES);
  }

  /** The book registered under `id`, or `undefined` — a linear walk of the directory. */
  find(id: string): BookCensus | undefined {
    for (const book of this) {
      if (book.id === id) return book;
    }
    return undefined;
  }

  *[Symbol.iterator](): IterableIterator<BookCensus> {
    for (let n = 0; n < this.bookCount; n += 1) yield this.book(n);
  }
}
