//! @generated by `cargo run -p usfm_galley --bin codegen` from
//! `find::wire::schema`. DO NOT EDIT — edit the schema or `find::wire::emit`
//! and regenerate. `galley/tests/codegen_output_matches_input.rs` fails the
//! build if this is stale.
//!
//! One writer per record. Fields go out in schema order, little-endian, with
//! no padding between them — nothing here casts a Rust struct, so nothing
//! depends on its layout.
//!
//! `offsets` is COLLECTED AND DROPPED by this format's encoder: find converts
//! per book, against the projection's table and the source's, before a row is
//! built, so there is no later sweep to feed. The parameter stays because one
//! emitter writes every wire in the workspace, and a vocabulary with a
//! "sweep or not" switch on it would be a concept bought for one caller.

// Every field is cast to its wire width uniformly, whether or not the engine's
// type already matches. A generator that emitted the cast only sometimes would
// be a generator with a special case in it; the redundant ones cost nothing.
#![allow(clippy::unnecessary_cast)]

use super::WireHit;
use crate::pantry::BookId;

/// Where every offset landed in the buffer. See the note above: this format
/// fills one and drops it.
pub type Offsets = Vec<usize>;

/// One hit: where a reader sees it, and where an editor would change it.
///
/// 16 bytes per row head, then `pieceCount` × 8. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_hits(rows: &[WireHit], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 16);
    for h in rows {
        // Into the buffer's own id table, which names every book SEARCHED.
        out.extend_from_slice(&((h.book) as u32).to_le_bytes());
        offsets.push(out.len());
        // First unit of the hit in the PROJECTION — what a highlighter wants.
        out.extend_from_slice(&((h.from) as u32).to_le_bytes());
        offsets.push(out.len());
        // One past its last unit.
        out.extend_from_slice(&((h.to) as u32).to_le_bytes());
        // Source pieces below; more than one where the hit crosses masked markup.
        out.extend_from_slice(&((h.pieces.len()) as u32).to_le_bytes());
        for p in &h.pieces {
            offsets.push(out.len());
            // First unit of the piece in the SOURCE — where an edit lands.
            out.extend_from_slice(&((p.0) as u32).to_le_bytes());
            offsets.push(out.len());
            // One past its last unit.
            out.extend_from_slice(&((p.1) as u32).to_le_bytes());
        }
    }
}

/// One contiguous source piece of a hit, in the raw book's UTF-16.
///
/// 8 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_pieces(rows: &[(u32, u32)], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 8);
    for p in rows {
        offsets.push(out.len());
        // First unit of the piece in the SOURCE — where an edit lands.
        out.extend_from_slice(&((p.0) as u32).to_le_bytes());
        offsets.push(out.len());
        // One past its last unit.
        out.extend_from_slice(&((p.1) as u32).to_le_bytes());
    }
}

/// One searched book's id length in bytes, in id-table order.
///
/// 4 bytes per row. Every field is an index or a code, so nothing
/// here is ever converted.
pub fn write_id_lens(rows: &[BookId], out: &mut Vec<u8>, _offsets: &mut Offsets) {
    out.reserve(rows.len() * 4);
    for id in rows {
        // Bytes of UTF-8 in the blob at the end of the buffer.
        out.extend_from_slice(&((id.as_str().len()) as u32).to_le_bytes());
    }
}

/// One hit's preview length in bytes, index-aligned with the hits.
///
/// 4 bytes per row. Every field is an index or a code, so nothing
/// here is ever converted.
pub fn write_preview_lens(rows: &[String], out: &mut Vec<u8>, _offsets: &mut Offsets) {
    out.reserve(rows.len() * 4);
    for s in rows {
        // Bytes of UTF-8 in the blob at the end of the buffer.
        out.extend_from_slice(&((s.len()) as u32).to_le_bytes());
    }
}
