//! @generated by `cargo run -p usfm_galley --bin codegen` from `mask::schema`.
//! DO NOT EDIT — edit the schema or `mask::emit` and regenerate.
//! `galley/tests/codegen_output_matches_input.rs` fails the build if this is
//! stale.
//!
//! The writer for the map's one record. Fields go out in schema order,
//! little-endian, with no padding between them — nothing here casts a Rust
//! struct, so nothing depends on its layout. `offsets` collects the buffer
//! position of every source offset written, which is what lets one sweep
//! rebase the whole block through the book's own `Utf16Table`.

// Every field is cast to its wire width uniformly, whether or not the engine's
// type already matches. A generator that emitted the cast only sometimes would
// be a generator with a special case in it; the redundant ones cost nothing.
#![allow(clippy::unnecessary_cast)]

use core::ops::Range;

/// Where every source offset landed in the block's bytes, so one sweep
/// converts them all.
pub type Offsets = Vec<usize>;

/// One kept source span. Sorted, disjoint, non-empty, maximal.
///
/// 8 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_ranges(rows: &[Range<u32>], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 8);
    for r in rows {
        offsets.push(out.len());
        // First kept unit.
        out.extend_from_slice(&((r.start) as u32).to_le_bytes());
        offsets.push(out.len());
        // One past the last.
        out.extend_from_slice(&((r.end) as u32).to_le_bytes());
    }
}
