//! The JS side-table: `LINT_ROWS` rendered as JSON, one entry per code.
//!
//! ```text
//! LINT_ROWS[0]                  {"code": 0,
//!   name: "unclosed-note"        "name": "unclosed-note",
//!   category: Structure          "category": "structure",
//!   severity: Some(Error)        "severity": "error",
//!   escalation: []               "escalation": [],
//!   aux: AuxKind::None           "aux": "none",
//!   template: "\\f was never…"   "template": "\\f was never closed",
//!   fix_label: Some("close…")    "formatter": false,
//!                                "fixLabel": "close the note"}
//! ```
//!
//! A finding crosses the wasm wall as SEVEN NUMBERS, one of which is this
//! array's index. Everything a UI has to say about it — the label, the ladder
//! rung, the family it groups under, the sentence its two spans go into — is
//! read out of this file, which the bundle loads once. No string is ever
//! per-finding.
//!
//! CHECKED IN beside the bindings crate and regenerated by `cargo run --bin
//! codegen`; `tests/codegen_output_matches_input.rs` fails the build when the
//! checked-in copy is stale, exactly as it does for the marker table.
//!
//! **The array is dense and index-addressed**: entry `n` is `Code`'s `n`th
//! variant, Form-channel rows included. They are marked `"severity": "form"`
//! and never appear in an `analyze` diagnostics read (they are the formatter's
//! rows and `lint` never evaluates them) — the entry exists so the index stays
//! the discriminant.

use core::fmt::Write as _;

use super::rows::{AuxKind, Category, LINT_ROWS, LintRow, Severity, UsfmVersion};

/// The wire's own version. Bump when a FIELD changes, not when a row does.
pub const SCHEMA: &str = "onion-diagnostics-v1";

/// The whole side-table as JSON text. Deterministic: row order is `Code`'s
/// declaration order and every field is emitted unconditionally.
pub fn diagnostics_json() -> String {
    let mut out = String::with_capacity(16 * 1024);
    out.push_str("{\n");
    writeln!(out, "  \"schema\": {},", quoted(SCHEMA)).expect("String write");
    out.push_str("  \"codes\": [\n");
    for (code, row) in LINT_ROWS.iter().enumerate() {
        entry(&mut out, code, row);
        out.push_str(if code + 1 == LINT_ROWS.len() {
            "\n"
        } else {
            ",\n"
        });
    }
    out.push_str("  ]\n}\n");
    out
}

fn entry(out: &mut String, code: usize, row: &LintRow) {
    out.push_str("    {");
    write!(out, "\"code\": {code}").expect("String write");
    write!(out, ", \"name\": {}", quoted(row.name)).expect("String write");
    write!(out, ", \"category\": {}", quoted(category(row.category))).expect("String write");
    match row.severity {
        // `null` is the GATE, not an omission: the code says nothing until a
        // `\usfm` line declares its first rung.
        None => out.push_str(", \"severity\": null"),
        Some(severity) => {
            write!(out, ", \"severity\": {}", quoted(severity_name(severity))).expect("String write")
        }
    }
    out.push_str(", \"escalation\": [");
    for (at, (version, severity)) in row.escalation.iter().enumerate() {
        if at > 0 {
            out.push_str(", ");
        }
        write!(
            out,
            "[{}, {}]",
            quoted(version_name(*version)),
            quoted(severity_name(*severity))
        )
        .expect("String write");
    }
    out.push(']');
    write!(out, ", \"aux\": {}", quoted(aux(row.aux))).expect("String write");
    write!(out, ", \"template\": {}", quoted(row.template)).expect("String write");
    write!(out, ", \"formatter\": {}", row.formatter).expect("String write");
    match row.fix_label {
        None => out.push_str(", \"fixLabel\": null"),
        Some(label) => write!(out, ", \"fixLabel\": {}", quoted(label)).expect("String write"),
    }
    out.push('}');
}

fn category(category: Category) -> &'static str {
    match category {
        Category::Structure => "structure",
        Category::Ordering => "ordering",
        Category::Attributes => "attributes",
        Category::Payload => "payload",
        Category::Form => "form",
        Category::Version => "version",
    }
}

/// The consumer-facing ladder. The first four are CodeMirror's own
/// `Diagnostic.severity` strings, mapped 1:1 with no translation table; the
/// fifth is the formatter's channel.
fn severity_name(severity: Severity) -> &'static str {
    match severity {
        Severity::Error => "error",
        Severity::Warning => "warning",
        Severity::Info => "info",
        Severity::Hint => "hint",
        Severity::Form => "form",
    }
}

fn version_name(version: UsfmVersion) -> &'static str {
    match version {
        UsfmVersion::V3_0 => "3.0",
        UsfmVersion::V3_2 => "3.2",
        UsfmVersion::V4_0 => "4.0",
    }
}

fn aux(aux: AuxKind) -> &'static str {
    match aux {
        AuxKind::None => "none",
        AuxKind::ExpectedNumber => "expectedNumber",
        AuxKind::NumberingCap => "numberingCap",
        AuxKind::Count => "count",
        AuxKind::Version => "version",
        AuxKind::MalformedShape => "malformedShape",
    }
}

/// A JSON string literal. The templates are full of backslashes (`\f was never
/// closed`), which is the whole reason this is not a `format!("\"{}\"")`.
fn quoted(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => write!(out, "\\u{:04x}", c as u32).expect("String write"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_row_appears_once_in_declaration_order() {
        let json = diagnostics_json();
        let mut at = 0;
        for (code, row) in LINT_ROWS.iter().enumerate() {
            let needle = format!("\"code\": {code}, \"name\": \"{}\"", row.name);
            let found = json[at..]
                .find(&needle)
                .unwrap_or_else(|| panic!("{} is missing or out of order", row.name));
            at += found + needle.len();
        }
    }

    #[test]
    fn the_generator_is_deterministic() {
        assert_eq!(diagnostics_json(), diagnostics_json());
    }

    #[test]
    fn backslashes_in_a_template_are_escaped() {
        let json = diagnostics_json();
        // `\*` in a template is one backslash; the wire carries two.
        assert!(
            json.contains("milestone is missing its \\\\*"),
            "a backslash in a template must double on the wire"
        );
        assert!(
            !json.chars().any(|c| (c as u32) < 0x20 && c != '\n'),
            "no raw control bytes in the wire"
        );
    }
}
