/**
 * @generated by `cargo run -p sous-core --bin codegen` from the Rust wire
 * schema. DO NOT EDIT — edit `sous-chef/core/src/corpus.rs` or this template.
 *
 * This reader is deliberately lazy: opening validates the envelope and book
 * directory, while `BookView.at()` decodes exactly one fixed-width row.
 */

export const MAGIC = 0x53554f53;
export const FORMAT_VERSION = 1;
export const FLAG_UTF16 = 1;
export const HEADER_BYTES = 48;
export const DIRECTORY_ENTRY_BYTES = 20;
export const RECORD_LEN = 16;
export const HEADER_MAGIC_OFFSET = 0;
export const HEADER_VERSION_OFFSET = 4;
export const HEADER_FLAGS_OFFSET = 8;
export const HEADER_BOOK_COUNT_OFFSET = 12;
export const HEADER_RECORD_LEN_OFFSET = 16;
export const HEADER_TOTAL_FINDINGS_OFFSET = 20;
export const HEADER_PATTERN_COUNT_OFFSET = 24;
export const HEADER_PATTERN_OFFSET_OFFSET = 28;
export const HEADER_SNAPSHOT_ID_OFFSET = 32;
export const DIRECTORY_KEY_OFFSET = 0;
export const DIRECTORY_KEY_TERMINATOR_OFFSET = 3;
export const DIRECTORY_LENGTH_OFFSET = 4;
export const DIRECTORY_SECTION_OFFSET = 8;
export const DIRECTORY_FINDING_COUNT_OFFSET = 12;
export const DIRECTORY_ID_OFFSET = 16;
export const ID_PREFIX_BYTES = 2;
export const SECTION_ALIGNMENT = 4;
export const RECORD_FROM_OFFSET = 0;
export const RECORD_TO_OFFSET = 4;
export const RECORD_BOOK_INDEX_OFFSET = 8;
export const RECORD_CODE_OFFSET = 10;
export const RECORD_FLAGS_OFFSET = 11;
export const RECORD_BOOK_SCOPE_OFFSET = 12;
export const RECORD_PROJECT_SCOPE_OFFSET = 14;
export const PATTERN_ROW_LEN = 24;
export const PATTERN_GLYPH_OFFSET = 0;
export const PATTERN_NEIGHBOR_OFFSET = 4;
export const PATTERN_CHANNEL_OFFSET = 8;
export const PATTERN_KEY_OFFSET = 9;
export const PATTERN_BAND_OFFSET = 10;
export const PATTERN_FLAGS_OFFSET = 11;
export const PATTERN_NUMERATOR_OFFSET = 12;
export const PATTERN_DENOMINATOR_OFFSET = 16;
export const PATTERN_SHARE_OFFSET = 20;
/** Books whose counts hold part of the numerator; books-possible is `bookCount`. */
export const PATTERN_BOOKS_OFFSET = 22;
export const PATTERN_RESERVED_OFFSET = 23;
/** The band byte a `Rarity` row carries: no staircase step. */
export const PATTERN_BAND_NONE = 255;
/** The pooled decimal-digit lane, which is not a scalar. */
export const PATTERN_DIGIT_GLYPH = 4294967295;
export const BAND_STEPS = 5;
export const RUN_BUCKETS = 6;

export type CoordinateSpace = "utf8" | "utf16";
export type ByteSource = ArrayBuffer | ArrayBufferView;

export interface ProportionalityDigest {
  readonly bookScope: number | null;
  readonly projectScope: number | null;
  readonly saturated: boolean;
}

export interface LengthProportionalityFinding {
  readonly kind: "LengthProportionality";
  readonly from: number;
  readonly to: number;
  readonly bookIdx: number;
  readonly digest: ProportionalityDigest;
}

/** Wire lane 12..14 is the class index into this table. */
export const HYGIENE_CLASSES = ["C0Control", "Delete", "C1Control", "ReplacementChar", "StrayCarriageReturn", "StrandedBackslash", "ConflictMarker", "FreeCombiningMark", "MisplacedFormat", "NoBreakSpace", "Noncharacter"] as const;
export type HygieneClass = (typeof HYGIENE_CLASSES)[number];

export interface HygieneDigest {
  readonly class: HygieneClass;
  /** Code points in the run; exact unless `saturated`. */
  readonly run: number;
  readonly saturated: boolean;
}

export interface HygieneFinding {
  readonly kind: "Hygiene";
  readonly from: number;
  readonly to: number;
  readonly bookIdx: number;
  readonly hygiene: HygieneDigest;
}

/** Wire lane 12..14 is the kind index into this table. */
export const PRESENCE_KINDS = ["Missing", "Extra", "Empty"] as const;
export type PresenceKind = (typeof PRESENCE_KINDS)[number];

export interface PresenceDigest {
  readonly kind: PresenceKind;
  /** Consecutive verse keys the row covers; exact unless `saturated`. Which
   * keys they are is the consumer's own table of contents around the span. */
  readonly keys: number;
  readonly saturated: boolean;
}

export interface PresenceFinding {
  readonly kind: "Presence";
  readonly from: number;
  readonly to: number;
  readonly bookIdx: number;
  readonly presence: PresenceDigest;
}

export interface SourceCopyDigest {
  /** Consecutive target words the paired source verse also holds. */
  readonly run: number;
  /** Eligible words the whole paired unit offered. */
  readonly eligible: number;
  /** Either lane clamped at 0x7fff. */
  readonly saturated: boolean;
}

export interface SourceCopyFinding {
  readonly kind: "SourceCopy";
  readonly from: number;
  readonly to: number;
  readonly bookIdx: number;
  readonly sourceCopy: SourceCopyDigest;
}

/** Wire byte 8 of a pattern row is the index into this table. */
export const CHANNELS = ["ExactNeighbor", "PooledNeighbor", "RunShape", "Placement", "Rarity", "Casing", "WordLength", "Doubled", "LetterRun", "SentenceStart"] as const;
export type Channel = (typeof CHANNELS)[number];

/** The outer class either side of a glyph. */
export const OUTER_CLASSES = ["Letter", "Space", "Digit", "Nonletter", "Edge"] as const;
export type OuterClass = (typeof OUTER_CLASSES)[number];

/** The G2 neighbour categories; a `PooledNeighbor` key byte indexes this. */
export const POOLS = ["Quote", "Bracket", "Dash", "Terminal", "Separator", "Digit", "Symbol", "Other"] as const;
export type Pool = (typeof POOLS)[number];

/** Convention lane 14..16 is a bitmask over this table, low bit first. */
export const CONVENTION_REASONS = ["PlacementBefore", "PlacementAfter", "RunShape", "ExactNeighbor", "Rarity", "PooledNeighbor", "Casing", "WordLength", "DoubledBare", "DoubledSeparated", "LetterRun", "SentenceStart"] as const;
export type ConventionReason = (typeof CONVENTION_REASONS)[number];

/** How a word occurrence is cased; a `Casing` key byte indexes this.
 * `Uncased` is counted nowhere and refused on the wire. */
export const CASING_FORMS = ["Lower", "Title", "Upper", "Mixed", "Uncased"] as const;
export type CasingForm = (typeof CASING_FORMS)[number];

/** The run lengths a `LetterRun` key byte may name; the last one saturates. */
export const LETTER_RUN_MIN = 2;
export const LETTER_RUN_MAX = 8;

export type PatternKey =
  | { readonly kind: "ExactNeighbor"; readonly neighbor: number }
  | { readonly kind: "PooledNeighbor"; readonly pool: Pool }
  | { readonly kind: "RunShape"; readonly pure: boolean; readonly bucket: number }
  | { readonly kind: "Placement"; readonly side: "prev" | "next"; readonly class: OuterClass }
  | { readonly kind: "Rarity" }
  | { readonly kind: "Casing"; readonly hash: bigint; readonly form: CasingForm }
  | { readonly kind: "WordLength"; readonly hash: bigint; readonly sigma: number }
  | { readonly kind: "Doubled"; readonly hash: bigint; readonly separated: boolean }
  | { readonly kind: "LetterRun"; readonly length: number }
  | { readonly kind: "SentenceStart" };

/** One corpus-level pattern: a glyph, the channel that convicted it, and the
 * fraction behind the claim. */
export interface Pattern {
  /** A code point, or `PATTERN_DIGIT_GLYPH` for the pooled digit lane. Zero on
   * a word channel, which judges no scalar: bytes 0..8 carry the word hash. */
  readonly glyph: number;
  readonly channel: Channel;
  readonly key: PatternKey;
  /** Staircase step index; `null` for `Rarity`. */
  readonly band: number | null;
  readonly numerator: number;
  readonly denominator: number;
  readonly shareBp: number;
  /** Books holding part of the numerator, out of the snapshot's `bookCount`.
   * Information only: nothing in the engine gates on dispersion. */
  readonly books: number;
}

export interface ConventionDigest {
  /** Position in the snapshot's pattern table. */
  readonly pattern: number;
  /** Every rung the site matched. */
  readonly reasons: readonly ConventionReason[];
}

export interface ConventionFinding {
  readonly kind: "Convention";
  readonly from: number;
  readonly to: number;
  readonly bookIdx: number;
  readonly convention: ConventionDigest;
}

export type Finding =
  | LengthProportionalityFinding
  | HygieneFinding
  | ConventionFinding
  | SourceCopyFinding
  | PresenceFinding;

export class FindingsSnapshotError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FindingsSnapshotError";
  }
}

interface BookEntry {
  readonly key: string;
  /** The host's opaque book id, unique where `key` need not be. */
  readonly id: string;
  readonly length: number;
  readonly offset: number;
  readonly count: number;
}

function fail(message: string): never {
  throw new FindingsSnapshotError(message);
}

function asDataView(source: ByteSource): DataView {
  if (ArrayBuffer.isView(source)) {
    return new DataView(source.buffer, source.byteOffset, source.byteLength);
  }
  if (source instanceof ArrayBuffer) {
    return new DataView(source);
  }
  return fail("findings buffer is not an ArrayBuffer or view");
}

function u32(view: DataView, at: number): number {
  return view.getUint32(at, true);
}

function checkKey(view: DataView, at: number): string {
  const bytes: number[] = [];
  for (let i = 0; i < 3; i += 1) {
    const byte = view.getUint8(at + i);
    if (byte < 0x20 || byte > 0x7e) {
      return fail(`book key contains a non-printable ASCII byte at ${at + i}`);
    }
    bytes.push(byte);
  }
  if (view.getUint8(at + 3) !== 0) {
    return fail(`book key at ${at} is missing its terminator`);
  }
  return String.fromCharCode(...bytes);
}

const UTF8 = new TextDecoder("utf-8", { fatal: true });

/** One `u16` length-prefixed UTF-8 id, with the offset just past it. */
function readId(view: DataView, offset: number, book: number): [string, number] {
  if (offset + ID_PREFIX_BYTES > view.byteLength) {
    return fail(`book ${book} id runs past the corpus buffer`);
  }
  const length = view.getUint16(offset, true);
  const end = offset + ID_PREFIX_BYTES + length;
  if (end > view.byteLength) {
    return fail(`book ${book} id runs past the corpus buffer`);
  }
  const bytes = new Uint8Array(view.buffer, view.byteOffset + offset + ID_PREFIX_BYTES, length);
  try {
    return [UTF8.decode(bytes), end];
  } catch {
    return fail(`book ${book} id is not valid UTF-8`);
  }
}

/** One 24-byte pattern row, refusing every value the encoder cannot write. */
function readPattern(view: DataView, at: number, row: number, bookCount: number): Pattern {
  if (view.getUint8(at + PATTERN_FLAGS_OFFSET) !== 0) {
    return fail(`pattern row ${row} has an invalid flags`);
  }
  if (view.getUint8(at + PATTERN_RESERVED_OFFSET) !== 0) {
    return fail(`pattern row ${row} has an invalid reserved`);
  }
  const rawGlyph = u32(view, at + PATTERN_GLYPH_OFFSET);
  const neighbor = u32(view, at + PATTERN_NEIGHBOR_OFFSET);
  const channel = CHANNELS[view.getUint8(at + PATTERN_CHANNEL_OFFSET)];
  if (channel === undefined) {
    return fail(`pattern row ${row} has an invalid channel`);
  }
  // Bytes 0..8 are a u64 word hash on a word channel, so no scalar check
  // applies there.
  const word = channel === "Casing" || channel === "WordLength" || channel === "Doubled";
  const glyph = word ? 0 : rawGlyph;
  if (!word && glyph !== PATTERN_DIGIT_GLYPH && (glyph > 0x10ffff || (glyph >= 0xd800 && glyph <= 0xdfff))) {
    return fail(`pattern row ${row} has an invalid glyph`);
  }
  const raw = view.getUint8(at + PATTERN_KEY_OFFSET);
  const high = raw >> 4;
  const low = raw & 0x0f;
  let key: PatternKey;
  if (word) {
    const hash = (BigInt(neighbor) << 32n) | BigInt(rawGlyph);
    if (channel === "WordLength") {
      key = { kind: "WordLength", hash, sigma: raw };
    } else if (channel === "Doubled") {
      if (raw > 1) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "Doubled", hash, separated: raw === 1 };
    } else {
      const form = CASING_FORMS[raw];
      if (form === undefined || form === "Uncased") {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "Casing", hash, form };
    }
  } else if (channel === "ExactNeighbor") {
    if (raw !== 0) {
      return fail(`pattern row ${row} has an invalid key`);
    }
    if (neighbor !== PATTERN_DIGIT_GLYPH && (neighbor > 0x10ffff || (neighbor >= 0xd800 && neighbor <= 0xdfff))) {
      return fail(`pattern row ${row} has an invalid neighbor`);
    }
    key = { kind: "ExactNeighbor", neighbor };
  } else {
    if (neighbor !== 0) {
      return fail(`pattern row ${row} has an invalid neighbor`);
    }
    if (channel === "PooledNeighbor") {
      const pool = POOLS[raw];
      if (pool === undefined) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "PooledNeighbor", pool };
    } else if (channel === "RunShape") {
      if (high > 1 || low === 0 || low > RUN_BUCKETS) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "RunShape", pure: high === 1, bucket: low };
    } else if (channel === "Placement") {
      const outer = OUTER_CLASSES[low];
      if (high > 1 || outer === undefined) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "Placement", side: high === 1 ? "next" : "prev", class: outer };
    } else if (channel === "LetterRun") {
      // A real scalar in the glyph field, and the key byte is the run length.
      if (raw < LETTER_RUN_MIN || raw > LETTER_RUN_MAX) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "LetterRun", length: raw };
    } else if (channel === "SentenceStart") {
      // The glyph is the whole claim: a lowercase letter after a glyph this
      // corpus almost always capitalizes after.
      if (raw !== 0) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "SentenceStart" };
    } else {
      if (raw !== 0) {
        return fail(`pattern row ${row} has an invalid key`);
      }
      key = { kind: "Rarity" };
    }
  }
  const rawBand = view.getUint8(at + PATTERN_BAND_OFFSET);
  let band: number | null;
  if (channel === "Rarity") {
    if (rawBand !== PATTERN_BAND_NONE) {
      return fail(`pattern row ${row} has an invalid band`);
    }
    band = null;
  } else {
    if (rawBand >= BAND_STEPS) {
      return fail(`pattern row ${row} has an invalid band`);
    }
    band = rawBand;
  }
  const shareBp = view.getUint16(at + PATTERN_SHARE_OFFSET, true);
  const numerator = u32(view, at + PATTERN_NUMERATOR_OFFSET);
  const denominator = u32(view, at + PATTERN_DENOMINATOR_OFFSET);
  if (numerator > denominator) {
    return fail(`pattern row ${row} has an invalid numerator`);
  }
  // The same fraction the producer computes, from the same clamped pair: a
  // row whose share does not follow from its own counts is refused, not
  // reported.
  const expected =
    denominator === 0
      ? 0
      : Math.min(Math.floor((numerator * 10000) / denominator), 10000);
  if (shareBp > 10000 || shareBp !== expected) {
    return fail(`pattern row ${row} has an invalid share`);
  }
  const books = view.getUint8(at + PATTERN_BOOKS_OFFSET);
  if (books > bookCount || (books === 0 && numerator > 0)) {
    return fail(`pattern row ${row} has an invalid books`);
  }
  return {
    glyph,
    channel,
    key,
    band,
    numerator,
    denominator,
    shareBp,
    books,
  };
}

function readReasons(bits: number): readonly ConventionReason[] {
  if (bits === 0) {
    return fail("a convention row carries at least one reason");
  }
  if ((bits & ~((1 << CONVENTION_REASONS.length) - 1)) !== 0) {
    return fail(`unknown convention reasons 0x${bits.toString(16).padStart(4, "0")}`);
  }
  return CONVENTION_REASONS.filter((_, bit) => (bits & (1 << bit)) !== 0);
}

function signedDeviation(view: DataView, at: number): number | null {
  const raw = view.getInt16(at, true);
  return raw === -0x8000 ? null : raw / 256;
}

export class BookView {
  readonly #view: DataView;
  readonly #entry: BookEntry;
  readonly #index: number;
  readonly #patternCount: number;

  constructor(view: DataView, entry: BookEntry, index: number, patternCount: number) {
    this.#view = view;
    this.#entry = entry;
    this.#index = index;
    this.#patternCount = patternCount;
  }

  get key(): string {
    return this.#entry.key;
  }

  /** The host id this book was published under. */
  get id(): string {
    return this.#entry.id;
  }

  get index(): number {
    return this.#index;
  }

  /** Number of lazy finding rows in this book. */
  get length(): number {
    return this.#entry.count;
  }

  /** Published coordinate extent for this book. */
  get publishedLength(): number {
    return this.#entry.length;
  }

  get count(): number {
    return this.#entry.count;
  }

  at(row: number): Finding {
    if (!Number.isSafeInteger(row) || row < 0 || row >= this.#entry.count) {
      return fail(`finding row ${row} is outside book ${this.#index}`);
    }
    const at = this.#entry.offset + row * RECORD_LEN;
    const from = u32(this.#view, at + RECORD_FROM_OFFSET);
    const to = u32(this.#view, at + RECORD_TO_OFFSET);
    const bookIdx = this.#view.getUint16(at + RECORD_BOOK_INDEX_OFFSET, true);
    if (bookIdx !== this.#index) {
      return fail(`finding row ${row} carries book index ${bookIdx}, expected ${this.#index}`);
    }
    const code = this.#view.getUint8(at + RECORD_CODE_OFFSET);
    if (code !== 0 && code !== 1 && code !== 2 && code !== 3 && code !== 4) {
      return fail(`unknown finding rule code ${code}`);
    }
    const flags = this.#view.getUint8(at + RECORD_FLAGS_OFFSET);
    if ((flags & ~1) !== 0) {
      return fail(`unknown finding flags 0x${flags.toString(16).padStart(2, "0")}`);
    }
    if (from > to) {
      return fail(`reversed finding span ${from}..${to}`);
    }
    if (to > this.#entry.length) {
      return fail(`finding span ${from}..${to} exceeds book length ${this.#entry.length}`);
    }
    const saturated = (flags & 1) !== 0;
    if (code === 1) {
      const classIndex = this.#view.getInt16(at + RECORD_BOOK_SCOPE_OFFSET, true);
      const hygieneClass = HYGIENE_CLASSES[classIndex];
      if (hygieneClass === undefined) {
        return fail(`unknown hygiene class ${classIndex}`);
      }
      const run = this.#view.getInt16(at + RECORD_PROJECT_SCOPE_OFFSET, true);
      if (run < 1) {
        return fail("hygiene run length must be at least 1");
      }
      if (saturated && run !== 0x7fff) {
        return fail("saturated hygiene run must read back as 0x7fff");
      }
      return { kind: "Hygiene", from, to, bookIdx, hygiene: { class: hygieneClass, run, saturated } };
    }
    if (code === 4) {
      const kindIndex = this.#view.getInt16(at + RECORD_BOOK_SCOPE_OFFSET, true);
      const presenceKind = PRESENCE_KINDS[kindIndex];
      if (presenceKind === undefined) {
        return fail(`unknown presence kind ${kindIndex}`);
      }
      const keys = this.#view.getInt16(at + RECORD_PROJECT_SCOPE_OFFSET, true);
      if (keys < 1) {
        return fail("a presence row covers at least one key");
      }
      if (saturated && keys !== 0x7fff) {
        return fail("saturated presence key count must read back as 0x7fff");
      }
      return { kind: "Presence", from, to, bookIdx, presence: { kind: presenceKind, keys, saturated } };
    }
    if (code === 3) {
      const run = this.#view.getInt16(at + RECORD_BOOK_SCOPE_OFFSET, true);
      const eligible = this.#view.getInt16(at + RECORD_PROJECT_SCOPE_OFFSET, true);
      if (run < 1 || eligible < run) {
        return fail(`a source-copy run of ${run} in a unit of ${eligible} eligible words`);
      }
      if (saturated && run !== 0x7fff && eligible !== 0x7fff) {
        return fail("a saturated source-copy row clamps a lane to 0x7fff");
      }
      return { kind: "SourceCopy", from, to, bookIdx, sourceCopy: { run, eligible, saturated } };
    }
    if (code === 2) {
      if (saturated) {
        return fail("a convention row is never saturated");
      }
      const pattern = this.#view.getUint16(at + RECORD_BOOK_SCOPE_OFFSET, true);
      if (pattern >= this.#patternCount) {
        return fail(`book ${this.#index} row ${row} names pattern ${pattern} in a table of ${this.#patternCount}`);
      }
      const reasons = readReasons(this.#view.getUint16(at + RECORD_PROJECT_SCOPE_OFFSET, true));
      return { kind: "Convention", from, to, bookIdx, convention: { pattern, reasons } };
    }
    return {
      kind: "LengthProportionality",
      from,
      to,
      bookIdx,
      digest: {
        bookScope: signedDeviation(this.#view, at + RECORD_BOOK_SCOPE_OFFSET),
        projectScope: signedDeviation(this.#view, at + RECORD_PROJECT_SCOPE_OFFSET),
        saturated,
      },
    };
  }
}

export class FindingsSnapshot {
  readonly #view: DataView;
  readonly #entries: readonly BookEntry[];
  readonly #byKey: ReadonlyMap<string, number>;
  readonly #byId: ReadonlyMap<string, number>;
  readonly #patternStart: number;
  readonly #patternCount: number;
  readonly snapshotId: Uint8Array;
  readonly coordinateSpace: CoordinateSpace;

  private constructor(
    view: DataView,
    entries: readonly BookEntry[],
    snapshotId: Uint8Array,
    coordinateSpace: CoordinateSpace,
    patternStart: number,
    patternCount: number,
  ) {
    this.#view = view;
    this.#entries = entries;
    this.#patternStart = patternStart;
    this.#patternCount = patternCount;
    // First position wins: two ids may publish the same `\id`.
    this.#byKey = new Map([...entries].reverse().map((entry, at) => [entry.key, entries.length - 1 - at]));
    this.#byId = new Map(entries.map((entry, index) => [entry.id, index]));
    this.snapshotId = snapshotId;
    this.coordinateSpace = coordinateSpace;
  }

  static open(source: ByteSource): FindingsSnapshot {
    const view = asDataView(source);
    if (view.byteLength < HEADER_BYTES) {
      return fail(`corpus buffer is ${view.byteLength} bytes; header is ${HEADER_BYTES}`);
    }
    if (u32(view, HEADER_MAGIC_OFFSET) !== MAGIC) {
      return fail("unknown corpus magic");
    }
    if (u32(view, HEADER_VERSION_OFFSET) !== FORMAT_VERSION) {
      return fail(`unsupported corpus format version ${u32(view, HEADER_VERSION_OFFSET)}`);
    }
    const flags = u32(view, HEADER_FLAGS_OFFSET);
    if (flags !== 0 && flags !== FLAG_UTF16) {
      return fail(`unknown corpus flags 0x${flags.toString(16)}`);
    }
    const coordinateSpace: CoordinateSpace = flags === FLAG_UTF16 ? "utf16" : "utf8";
    const bookCount = u32(view, HEADER_BOOK_COUNT_OFFSET);
    if (bookCount > 0x10000) {
      return fail(`corpus has ${bookCount} books; maximum is 65536`);
    }
    if (u32(view, HEADER_RECORD_LEN_OFFSET) !== RECORD_LEN) {
      return fail(`record stride is ${u32(view, HEADER_RECORD_LEN_OFFSET)}, expected ${RECORD_LEN}`);
    }
    const totalFindings = u32(view, HEADER_TOTAL_FINDINGS_OFFSET);
    const patternCount = u32(view, HEADER_PATTERN_COUNT_OFFSET);
    if (patternCount > 0xffff) {
      return fail(`corpus declares ${patternCount} patterns; maximum is 65535`);
    }
    const snapshotId = new Uint8Array(view.buffer, view.byteOffset + HEADER_SNAPSHOT_ID_OFFSET, 16).slice();
    const idStart = HEADER_BYTES + bookCount * DIRECTORY_ENTRY_BYTES;
    if (idStart > view.byteLength) {
      return fail("book directory exceeds corpus buffer");
    }

    // The id string table, in directory order: each offset must be the running
    // cursor, so the strings cannot overlap, reorder, or hide bytes.
    const ids: string[] = [];
    const seenIds = new Set<string>();
    let idCursor = idStart;
    for (let index = 0; index < bookCount; index += 1) {
      const at = HEADER_BYTES + index * DIRECTORY_ENTRY_BYTES + DIRECTORY_ID_OFFSET;
      const offset = u32(view, at);
      if (offset !== idCursor) {
        return fail(`book ${index} id starts at ${offset}, expected ${idCursor}`);
      }
      const [id, end] = readId(view, offset, index);
      if (seenIds.has(id)) {
        return fail(`book ${index} repeats a host id already published`);
      }
      seenIds.add(id);
      ids.push(id);
      idCursor = end;
    }
    const patternStart =
      idStart + Math.ceil((idCursor - idStart) / SECTION_ALIGNMENT) * SECTION_ALIGNMENT;
    if (patternStart > view.byteLength) {
      return fail("book id table exceeds corpus buffer");
    }
    if (u32(view, HEADER_PATTERN_OFFSET_OFFSET) !== patternStart) {
      return fail(
        `pattern table starts at ${u32(view, HEADER_PATTERN_OFFSET_OFFSET)}, expected ${patternStart}`,
      );
    }
    const patternEnd = patternStart + patternCount * PATTERN_ROW_LEN;
    if (patternEnd > view.byteLength) {
      return fail("pattern table exceeds corpus buffer");
    }
    for (let row = 0; row < patternCount; row += 1) {
      readPattern(view, patternStart + row * PATTERN_ROW_LEN, row, bookCount);
    }

    const entries: BookEntry[] = [];
    let cursor = patternEnd;
    let totalSeen = 0;
    for (let index = 0; index < bookCount; index += 1) {
      const at = HEADER_BYTES + index * DIRECTORY_ENTRY_BYTES;
      const key = checkKey(view, at + DIRECTORY_KEY_OFFSET);
      const length = u32(view, at + DIRECTORY_LENGTH_OFFSET);
      const offset = u32(view, at + DIRECTORY_SECTION_OFFSET);
      const count = u32(view, at + DIRECTORY_FINDING_COUNT_OFFSET);
      if (offset !== cursor) {
        return fail(`book ${index} section starts at ${offset}, expected ${cursor}`);
      }
      const end = offset + count * RECORD_LEN;
      if (!Number.isSafeInteger(end) || end > view.byteLength) {
        return fail(`book ${index} section exceeds corpus buffer`);
      }
      entries.push({ key, id: ids[index], length, offset, count });
      cursor = end;
      totalSeen += count;
    }
    if (cursor !== view.byteLength) {
      return fail(`corpus has trailing bytes after offset ${cursor}`);
    }
    if (totalSeen !== totalFindings) {
      return fail(`header declares ${totalFindings} findings, directory contains ${totalSeen}`);
    }
    return new FindingsSnapshot(view, entries, snapshotId, coordinateSpace, patternStart, patternCount);
  }

  get length(): number {
    return this.#entries.length;
  }

  /** Rows in the publication's pattern table. */
  get patternCount(): number {
    return this.#patternCount;
  }

  /** One pattern row, decoded. */
  pattern(index: number): Pattern {
    if (!Number.isSafeInteger(index) || index < 0 || index >= this.#patternCount) {
      return fail(`pattern ${index} is outside a table of ${this.#patternCount}`);
    }
    return readPattern(
      this.#view,
      this.#patternStart + index * PATTERN_ROW_LEN,
      index,
      this.#entries.length,
    );
  }

  /** The whole table, in emission order. */
  patterns(): Pattern[] {
    return Array.from({ length: this.#patternCount }, (_, row) => this.pattern(row));
  }

  /** By directory position, or the first book carrying that `BookKey`. */
  book(keyOrIndex: string | number): BookView | undefined {
    const index = typeof keyOrIndex === "string" ? this.#byKey.get(keyOrIndex) : keyOrIndex;
    if (index === undefined || !Number.isSafeInteger(index) || index < 0 || index >= this.#entries.length) {
      return undefined;
    }
    return new BookView(this.#view, this.#entries[index], index, this.#patternCount);
  }

  /** Seeks the id string table; ids are unique where keys need not be. */
  bookById(id: string): BookView | undefined {
    const index = this.#byId.get(id);
    return index === undefined ? undefined : this.book(index);
  }

  /** Every finding published under one host id, decoded eagerly. */
  findingsFor(id: string): Finding[] {
    const book = this.bookById(id);
    if (book === undefined) {
      return [];
    }
    return Array.from({ length: book.count }, (_, row) => book.at(row));
  }
}
