/**
 * @generated by `cargo run -p sous-core --bin codegen` from the Rust wire
 * schema. DO NOT EDIT — edit `sous-chef/core/src/corpus.rs` or this template.
 *
 * This reader is deliberately lazy: opening validates the envelope and book
 * directory, while `BookView.at()` decodes exactly one fixed-width row.
 */

export const MAGIC = 0x53554f53;
export const FORMAT_VERSION = 1;
export const FLAG_UTF16 = 1;
export const HEADER_BYTES = 40;
export const DIRECTORY_ENTRY_BYTES = 16;
export const RECORD_LEN = 16;
export const HEADER_MAGIC_OFFSET = 0;
export const HEADER_VERSION_OFFSET = 4;
export const HEADER_FLAGS_OFFSET = 8;
export const HEADER_BOOK_COUNT_OFFSET = 12;
export const HEADER_RECORD_LEN_OFFSET = 16;
export const HEADER_TOTAL_FINDINGS_OFFSET = 20;
export const HEADER_SNAPSHOT_ID_OFFSET = 24;
export const DIRECTORY_KEY_OFFSET = 0;
export const DIRECTORY_KEY_TERMINATOR_OFFSET = 3;
export const DIRECTORY_LENGTH_OFFSET = 4;
export const DIRECTORY_SECTION_OFFSET = 8;
export const DIRECTORY_FINDING_COUNT_OFFSET = 12;
export const RECORD_FROM_OFFSET = 0;
export const RECORD_TO_OFFSET = 4;
export const RECORD_BOOK_INDEX_OFFSET = 8;
export const RECORD_CODE_OFFSET = 10;
export const RECORD_FLAGS_OFFSET = 11;
export const RECORD_BOOK_SCOPE_OFFSET = 12;
export const RECORD_PROJECT_SCOPE_OFFSET = 14;

export type CoordinateSpace = "utf8" | "utf16";
export type ByteSource = ArrayBuffer | ArrayBufferView;

export interface ProportionalityDigest {
  readonly bookScope: number | null;
  readonly projectScope: number | null;
  readonly saturated: boolean;
}

export interface LengthProportionalityFinding {
  readonly kind: "LengthProportionality";
  readonly from: number;
  readonly to: number;
  readonly bookIdx: number;
  readonly digest: ProportionalityDigest;
}

export type Finding = LengthProportionalityFinding;

export class FindingsSnapshotError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FindingsSnapshotError";
  }
}

interface BookEntry {
  readonly key: string;
  readonly length: number;
  readonly offset: number;
  readonly count: number;
}

function fail(message: string): never {
  throw new FindingsSnapshotError(message);
}

function asDataView(source: ByteSource): DataView {
  if (ArrayBuffer.isView(source)) {
    return new DataView(source.buffer, source.byteOffset, source.byteLength);
  }
  if (source instanceof ArrayBuffer) {
    return new DataView(source);
  }
  return fail("findings buffer is not an ArrayBuffer or view");
}

function u32(view: DataView, at: number): number {
  return view.getUint32(at, true);
}

function checkKey(view: DataView, at: number): string {
  const bytes: number[] = [];
  for (let i = 0; i < 3; i += 1) {
    const byte = view.getUint8(at + i);
    if (byte < 0x20 || byte > 0x7e) {
      return fail(`book key contains a non-printable ASCII byte at ${at + i}`);
    }
    bytes.push(byte);
  }
  if (view.getUint8(at + 3) !== 0) {
    return fail(`book key at ${at} is missing its terminator`);
  }
  return String.fromCharCode(...bytes);
}

function signedDeviation(view: DataView, at: number): number | null {
  const raw = view.getInt16(at, true);
  return raw === -0x8000 ? null : raw / 256;
}

export class BookView {
  readonly #view: DataView;
  readonly #entry: BookEntry;
  readonly #index: number;

  constructor(view: DataView, entry: BookEntry, index: number) {
    this.#view = view;
    this.#entry = entry;
    this.#index = index;
  }

  get key(): string {
    return this.#entry.key;
  }

  get index(): number {
    return this.#index;
  }

  /** Number of lazy finding rows in this book. */
  get length(): number {
    return this.#entry.count;
  }

  /** Published coordinate extent for this book. */
  get publishedLength(): number {
    return this.#entry.length;
  }

  get count(): number {
    return this.#entry.count;
  }

  at(row: number): Finding {
    if (!Number.isSafeInteger(row) || row < 0 || row >= this.#entry.count) {
      return fail(`finding row ${row} is outside book ${this.#index}`);
    }
    const at = this.#entry.offset + row * RECORD_LEN;
    const from = u32(this.#view, at + RECORD_FROM_OFFSET);
    const to = u32(this.#view, at + RECORD_TO_OFFSET);
    const bookIdx = this.#view.getUint16(at + RECORD_BOOK_INDEX_OFFSET, true);
    if (bookIdx !== this.#index) {
      return fail(`finding row ${row} carries book index ${bookIdx}, expected ${this.#index}`);
    }
    const code = this.#view.getUint8(at + RECORD_CODE_OFFSET);
    if (code !== 0) {
      return fail(`unknown finding rule code ${code}`);
    }
    const flags = this.#view.getUint8(at + RECORD_FLAGS_OFFSET);
    if ((flags & ~1) !== 0) {
      return fail(`unknown finding flags 0x${flags.toString(16).padStart(2, "0")}`);
    }
    if (from > to) {
      return fail(`reversed finding span ${from}..${to}`);
    }
    if (to > this.#entry.length) {
      return fail(`finding span ${from}..${to} exceeds book length ${this.#entry.length}`);
    }
    return {
      kind: "LengthProportionality",
      from,
      to,
      bookIdx,
      digest: {
        bookScope: signedDeviation(this.#view, at + RECORD_BOOK_SCOPE_OFFSET),
        projectScope: signedDeviation(this.#view, at + RECORD_PROJECT_SCOPE_OFFSET),
        saturated: (flags & 1) !== 0,
      },
    };
  }
}

export class FindingsSnapshot {
  readonly #view: DataView;
  readonly #entries: readonly BookEntry[];
  readonly #byKey: ReadonlyMap<string, number>;
  readonly snapshotId: Uint8Array;
  readonly coordinateSpace: CoordinateSpace;

  private constructor(
    view: DataView,
    entries: readonly BookEntry[],
    snapshotId: Uint8Array,
    coordinateSpace: CoordinateSpace,
  ) {
    this.#view = view;
    this.#entries = entries;
    this.#byKey = new Map(entries.map((entry, index) => [entry.key, index]));
    this.snapshotId = snapshotId;
    this.coordinateSpace = coordinateSpace;
  }

  static open(source: ByteSource): FindingsSnapshot {
    const view = asDataView(source);
    if (view.byteLength < HEADER_BYTES) {
      return fail(`corpus buffer is ${view.byteLength} bytes; header is ${HEADER_BYTES}`);
    }
    if (u32(view, HEADER_MAGIC_OFFSET) !== MAGIC) {
      return fail("unknown corpus magic");
    }
    if (u32(view, HEADER_VERSION_OFFSET) !== FORMAT_VERSION) {
      return fail(`unsupported corpus format version ${u32(view, HEADER_VERSION_OFFSET)}`);
    }
    const flags = u32(view, HEADER_FLAGS_OFFSET);
    if (flags !== 0 && flags !== FLAG_UTF16) {
      return fail(`unknown corpus flags 0x${flags.toString(16)}`);
    }
    const coordinateSpace: CoordinateSpace = flags === FLAG_UTF16 ? "utf16" : "utf8";
    const bookCount = u32(view, HEADER_BOOK_COUNT_OFFSET);
    if (bookCount > 0x10000) {
      return fail(`corpus has ${bookCount} books; maximum is 65536`);
    }
    if (u32(view, HEADER_RECORD_LEN_OFFSET) !== RECORD_LEN) {
      return fail(`record stride is ${u32(view, HEADER_RECORD_LEN_OFFSET)}, expected ${RECORD_LEN}`);
    }
    const totalFindings = u32(view, HEADER_TOTAL_FINDINGS_OFFSET);
    const snapshotId = new Uint8Array(view.buffer, view.byteOffset + HEADER_SNAPSHOT_ID_OFFSET, 16).slice();
    const directoryEnd = HEADER_BYTES + bookCount * DIRECTORY_ENTRY_BYTES;
    if (directoryEnd > view.byteLength) {
      return fail("book directory exceeds corpus buffer");
    }

    const entries: BookEntry[] = [];
    const keys = new Set<string>();
    let cursor = directoryEnd;
    let totalSeen = 0;
    for (let index = 0; index < bookCount; index += 1) {
      const at = HEADER_BYTES + index * DIRECTORY_ENTRY_BYTES;
      const key = checkKey(view, at + DIRECTORY_KEY_OFFSET);
      if (keys.has(key)) {
        return fail(`duplicate corpus book key ${key}`);
      }
      keys.add(key);
      const length = u32(view, at + DIRECTORY_LENGTH_OFFSET);
      const offset = u32(view, at + DIRECTORY_SECTION_OFFSET);
      const count = u32(view, at + DIRECTORY_FINDING_COUNT_OFFSET);
      if (offset !== cursor) {
        return fail(`book ${index} section starts at ${offset}, expected ${cursor}`);
      }
      const end = offset + count * RECORD_LEN;
      if (!Number.isSafeInteger(end) || end > view.byteLength) {
        return fail(`book ${index} section exceeds corpus buffer`);
      }
      entries.push({ key, length, offset, count });
      cursor = end;
      totalSeen += count;
    }
    if (cursor !== view.byteLength) {
      return fail(`corpus has trailing bytes after offset ${cursor}`);
    }
    if (totalSeen !== totalFindings) {
      return fail(`header declares ${totalFindings} findings, directory contains ${totalSeen}`);
    }
    return new FindingsSnapshot(view, entries, snapshotId, coordinateSpace);
  }

  get length(): number {
    return this.#entries.length;
  }

  book(keyOrIndex: string | number): BookView | undefined {
    const index = typeof keyOrIndex === "string" ? this.#byKey.get(keyOrIndex) : keyOrIndex;
    if (index === undefined || !Number.isSafeInteger(index) || index < 0 || index >= this.#entries.length) {
      return undefined;
    }
    return new BookView(this.#view, this.#entries[index], index);
  }
}
