/**
 * @generated by `cargo run --bin codegen` from `onion/src/wire/schema.rs`.
 * DO NOT EDIT — edit the schema, or the template at `reader.ts.tmpl`, and
 * regenerate. `onion/tests/codegen_output_matches_input.rs` fails the build if
 * this file is stale.
 *
 * The reader over one plated parse. Its writer is generated from the SAME
 * declaration, so the two ends of the wire cannot disagree.
 *
 *   import init, { parse as rawParse } from "./pkg/onion_wasm.js";
 *   import { reader } from "./reader.js";
 *
 *   await init();
 *   const onion = reader(rawParse);
 *   const { tree, tokens, diagnostics, toc } = onion.parse(text, {
 *     diagnostics: true,
 *     toc: true,
 *     utf16: true,
 *   });
 *   for (const item of tree.walk()) {
 *     if (item.isNode) console.log(item.marker()?.name, item.span());
 *   }
 *
 * Offsets are UTF-8 byte offsets unless the parse asked for `utf16`. Node ids
 * and child ids are INDICES and never convert.
 *
 * STRIP-ONLY TYPESCRIPT. No parameter properties, no enums, no decorators, no
 * namespaces — nothing that emits code. Node 24, Bun and esbuild's strip mode
 * all run this file as shipped, with no build step and so no second copy of the
 * reader to fall out of date with the writer.
 *
 * Nothing here holds a wasm allocation: `parse` returns a `Uint8Array` that JS
 * owns and the collector reclaims. There is no `free`.
 */

// ---------------------------------------------------------------------------
// The wire, generated
// ---------------------------------------------------------------------------

/** `"ONWR"`, little-endian. */
export const MAGIC = 0x52574e4f;

/** Bumped whenever the schema changes shape. */
export const FORMAT_VERSION = 4;

/** Set when every offset in the dish is a UTF-16 code unit. */
export const FLAG_UTF16 = 1 << 0;

/** "No such offset / no such index." */
export const NONE = 0xffffffff;

/** Bit 31 of a child id: the id names a NODE, not a token. */
export const NODE_ID_BIT = 0x80000000;

/**
 * Header bytes before the section directory: magic, format version, section
 * count, flags, the declared `\usfm` version, the source's length, and its
 * xxh3-64 across the last two words.
 */
export const HEADER_BYTES = 32;

/** The `\usfm` ladder, indexed by `Dish.usfmVersion`. */
export const USFM_VERSIONS = ["3.0", "3.2", "4.0"] as const;

export const SECTION = {
  /** The scanner's output, in document order. */
  tokens: 0,
  /** The tree's nodes. Node id is the row index. */
  nodes: 1,
  /** The shared child arena: token ids, and node ids tagged with bit 31. */
  childIds: 2,
  /** Findings, sorted by anchor then code. Empty unless asked for. */
  diagnostics: 3,
  /** Offered repairs, reached through a diagnostic's `fix`. */
  fixes: 4,
  /** The shared edit arena every fix's range indexes. */
  edits: 5,
  /** Inserted bytes, concatenated. Edits carry absolute positions into it. */
  fixText: 6,
  /** The chapter table. Empty unless asked for. */
  chapters: 7,
  /** The verse anchors. Empty unless asked for. */
  verses: 8,
} as const;

export const SECTION_NAMES = [
  "tokens",
  "nodes",
  "childIds",
  "diagnostics",
  "fixes",
  "edits",
  "fixText",
  "chapters",
  "verses",
] as const;


/** What a marker IS. All fourteen — never coarsened. */
export const MarkerKind = {
  Unknown: 0,
  Paragraph: 1,
  Character: 2,
  Note: 3,
  Chapter: 4,
  Verse: 5,
  Milestone: 6,
  Figure: 7,
  Sidebar: 8,
  Periph: 9,
  Meta: 10,
  TableRow: 11,
  TableCell: 12,
  Header: 13,
} as const;

/** The spec group a marker belongs to. ParaBody is distinct from ParaPoetry. */
export const Category = {
  Unknown: 0,
  ParaIdentification: 1,
  ParaIntroductions: 2,
  ParaTitlesSections: 3,
  ParaBody: 4,
  ParaPoetry: 5,
  ParaLists: 6,
  ParaTables: 7,
  ParaPeripheral: 8,
  CharTextFeatures: 9,
  CharFormatting: 10,
  CharBreaks: 11,
  CharIntroductions: 12,
  CharPoetry: 13,
  CharLists: 14,
  CharTables: 15,
  CharNotesFootnote: 16,
  CharNotesCrossReference: 17,
  NoteFootnote: 18,
  NoteCrossReference: 19,
  MilestoneList: 20,
  MilestoneTable: 21,
  MilestoneQt: 22,
  MilestoneTs: 23,
  MilestoneVid: 24,
  ChapterVerse: 25,
  Sidebar: 26,
  Meta: 27,
  Peripheral: 28,
  DocumentStructure: 29,
  Figure: 30,
} as const;

/** Whether a marker requires, allows or refuses a closer. */
export const ClosingBehavior = {
  None: 0,
  RequiredExplicit: 1,
  OptionalExplicitUntilNoteEnd: 2,
  SelfClosingMilestone: 3,
} as const;

/** Which spellings a row admits. */
export const SpellingShape = {
  Any: 0,
  PlainOnly: 1,
  MilestoneOnly: 2,
} as const;

/** What must follow a marker's name — `Marker.ws()`. */
export const StructuralWhitespaceRequirement = {
  NotRequired: 7,
  TagEndDelimiter: 6,
  AtLeastOneHorizontalWhitespace: 0,
  OptionalHorizontalWhitespace: 1,
  AtLeastOneWhitespace: 2,
  OptionalWhitespace: 3,
  SingleNewline: 4,
  AtLeastOneNewline: 5,
} as const;

/** Where in the document grammar a node sits — `NodeView.context()`. */
export const SpecContext = {
  Scripture: 0,
  BookIdentification: 1,
  BookHeaders: 2,
  BookTitles: 3,
  BookIntroduction: 4,
  BookIntroductionEndTitles: 5,
  BookChapterLabel: 6,
  ChapterContent: 7,
  Peripheral: 8,
  PeripheralContent: 9,
  PeripheralDivision: 10,
  Section: 11,
  Para: 12,
  List: 13,
  Table: 14,
  Sidebar: 15,
  Footnote: 16,
  CrossReference: 17,
} as const;

/** Why a node closed. `Explicit` is the well-formed answer. */
export const CloseReason = {
  Explicit: 0,
  Implicit: 1,
  Recovery: 2,
  Eof: 3,
} as const;

/** Why an attribute list stopped parsing — `attrs`'s trailing code. */
export const MalformedAttr = {
  UnterminatedQuote: 0,
  EmptyName: 1,
  MissingValue: 2,
  BareJunk: 3,
} as const;

/** What the marker table says about an attribute name — `attrResolve`. */
export const AttrResolution = {
  Defined: 0,
  UserNamespace: 1,
  Unknown: 2,
} as const;

/** What shape a token is — `TokenView.kind()`, spelling bit stripped. */
export const TokenKind = {
  Marker: 0,
  ClosingMarker: 1,
  Milestone: 2,
  MilestoneTerminator: 3,
  Newline: 4,
  OptBreak: 5,
  AttrList: 6,
  Text: 7,
  Designator: 8,
  NoteCaller: 9,
  BookCode: 10,
  Pad: 11,
} as const;

/**
 * Bit 0 of a token's flags byte: the last byte of the span is the one
 * horizontal delimiter the scanner folded on, so the payload ends at
 * `end - 1`. Read it through `TokenView.payloadEnd()`.
 */
export const TOKEN_DELIMITER_FOLDED = 1;

/**
 * Bit 1 of a token's flags byte: a `Text` token of nothing but horizontal
 * whitespace. Never set on another kind.
 */
export const TOKEN_BLANK = 2;

/**
 * Bit 4 of a token's kind byte, meaning PER SHAPE: `\+` nesting on the two
 * marker shapes, the `-e` half on a milestone. No shape carries both.
 */
export const TOKEN_SPELLING_BIT = 1 << 4;

/** Do these kind bits name a marker, and so resolve to a table row? */
export const isMarkerKind = (kind: number): boolean =>
  kind === TokenKind.Marker ||
  kind === TokenKind.ClosingMarker ||
  kind === TokenKind.Milestone;

/**
 * One lexical token: the leaves of the tree.
 *
 * 12 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class TokenRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 12;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 12;
    return this;
  }

  /** Where the token begins. */
  get start(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** Where it ends. Spans TILE the document, so ends ascend too. */
  get end(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** Packed TokenKind; bit 4 is the per-shape spelling bit. */
  get kind(): number {
    return this.#view.getUint8(this.#row + 8);
  }

  /** Row in the marker table; 0 is UNRESOLVED. */
  get marker(): number {
    return this.#view.getUint8(this.#row + 9);
  }

  /** The trailing number as spelled: 2 for `\q2`, 1 for `\tc1`, 0 for a bare `\q`. The row's `numbering` says whether it is a nesting level or a column index. */
  get level(): number {
    return this.#view.getUint8(this.#row + 10);
  }

  /** `TOKEN_DELIMITER_FOLDED` | `TOKEN_BLANK`. Also rounds the row to 12 bytes, so every row's `start` and `end` land aligned for a typed-array view over a 4-aligned section. */
  get flags(): number {
    return this.#view.getUint8(this.#row + 11);
  }

}

/**
 * One structural node. `token` and the child range are indices, not offsets.
 *
 * 14 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class NodeRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 14;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 14;
    return this;
  }

  /** The opening marker's token index; u32::MAX on the root. */
  get token(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** Start of this node's range in the child arena. */
  get childFrom(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** End of that range. Ranges are neither contiguous nor monotonic. */
  get childTo(): number {
    return this.#view.getUint32(this.#row + 8, true);
  }

  /** CloseReason: Explicit, Implicit, Recovery, Eof. */
  get reason(): number {
    return this.#view.getUint8(this.#row + 12);
  }

  /** The stamped SpecContext. */
  get ctx(): number {
    return this.#view.getUint8(this.#row + 13);
  }

}

/**
 * One finding, with its anchor resolved from a token index to a span.
 *
 * 32 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class DiagnosticRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 32;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 32;
    return this;
  }

  /** Index into the lint catalog. */
  get code(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** The anchor's start. */
  get from(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** The anchor's end. */
  get to(): number {
    return this.#view.getUint32(this.#row + 8, true);
  }

  /** The other party's start, or NONE. */
  get secondFrom(): number {
    return this.#view.getUint32(this.#row + 12, true);
  }

  /** The other party's end, or NONE. */
  get secondTo(): number {
    return this.#view.getUint32(this.#row + 16, true);
  }

  /** The code's aux integer; its meaning is the catalog row's. */
  get aux(): number {
    return this.#view.getUint32(this.#row + 20, true);
  }

  /** Index into the fix section, or NONE. */
  get fix(): number {
    return this.#view.getUint32(this.#row + 24, true);
  }

}

/**
 * One offered repair: the edits it owns.
 *
 * 8 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class FixRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 8;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 8;
    return this;
  }

  /** Start of this fix's range in the edit section. */
  get editFrom(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** End of that range. */
  get editTo(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

}

/**
 * One edit of a repair: replace [from, to) with the named text.
 *
 * 16 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class EditRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 16;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 16;
    return this;
  }

  /** Where the replacement starts. */
  get from(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** Where it ends; equal to `from` for a pure insertion. */
  get to(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** Start of the inserted bytes in the fix-text section. */
  get textFrom(): number {
    return this.#view.getUint32(this.#row + 8, true);
  }

  /** Their length. Zero is a pure deletion. */
  get textLen(): number {
    return this.#view.getUint32(this.#row + 12, true);
  }

}

/**
 * One chapter's extent and number. The rows tile the document.
 *
 * 18 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class ChapterRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 18;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 18;
    return this;
  }

  /** Where the chapter begins. */
  get start(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** Where it ends. */
  get end(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** The `\c` marker's token index; NONE on the front-matter row. */
  get token(): number {
    return this.#view.getUint32(this.#row + 8, true);
  }

  /** The number's own token index, or NONE. `\c` opens no node, so this is the only route from a chapter to its designator. */
  get designator(): number {
    return this.#view.getUint32(this.#row + 12, true);
  }

  /** The number read, or 0 for absent or malformed. */
  get number(): number {
    return this.#view.getUint16(this.#row + 16, true);
  }

}

/**
 * One verse anchor and the range of verse numbers it names.
 *
 * 18 bytes per row. A CURSOR: `seek` moves it, the getters read
* the row it is on, and nothing is allocated per row.
 */
export class VerseRow {
  readonly #view: DataView;
  #row = 0;

  constructor(view: DataView) {
    this.#view = view;
  }

  /** Rows in the section. */
  get length(): number {
    return (this.#view.byteLength / this.stride) | 0;
  }

  readonly stride = 18;

  /** Move to row `n`; returns `this` so reads chain. */
  seek(n: number): this {
    this.#row = n * 18;
    return this;
  }

  /** Where the anchor sits. */
  get at(): number {
    return this.#view.getUint32(this.#row + 0, true);
  }

  /** The `\v` marker's token index. */
  get token(): number {
    return this.#view.getUint32(this.#row + 4, true);
  }

  /** The number's own token index, or NONE. `\v` opens no node, so this is the only route from a verse to its designator. */
  get designator(): number {
    return this.#view.getUint32(this.#row + 8, true);
  }

  /** The enclosing chapter's number. */
  get chapter(): number {
    return this.#view.getUint16(this.#row + 12, true);
  }

  /** First verse named; 0 when the designator is absent or malformed. */
  get first(): number {
    return this.#view.getUint16(this.#row + 14, true);
  }

  /** Last verse named — a bridge `\v 5-7` names 5 through 7. */
  get last(): number {
    return this.#view.getUint16(this.#row + 16, true);
  }

}



/**
 * The marker table — 153 rows, generated from `tables::rows::ROWS`.
*
 * Indexed by a token's `marker` field. Row 0 is UNRESOLVED: an unknown
* name, a `\z` extension, an illegal spelling. It has no name, so the
* spelling is only in the document.
*
 * `numbering` is a packed code: 0 unnumbered, 1..=13 the cap, 14 unbounded,
* 15 table columns.
*
 * `ws` is a `StructuralWhitespaceRequirement`: what must follow the marker's
* name. `SingleNewline` is the rule for a marker that takes no content on
* its own line.
 */
export const MARKERS: readonly {
  readonly name: string;
  readonly kind: number;
  readonly category: number;
  readonly closing: number;
  readonly shape: number;
  readonly numbering: number;
  readonly ws: number;
}[] = [
  { name: "", kind: 0, category: 0, closing: 0, shape: 0, numbering: 0, ws: 7 },
  { name: "add", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "addpn", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "b", kind: 1, category: 5, closing: 0, shape: 0, numbering: 0, ws: 4 },
  { name: "bd", kind: 2, category: 10, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "bdit", kind: 2, category: 10, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "bk", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "c", kind: 4, category: 25, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "ca", kind: 2, category: 25, closing: 1, shape: 0, numbering: 0, ws: 0 },
  { name: "cat", kind: 10, category: 27, closing: 1, shape: 0, numbering: 0, ws: 1 },
  { name: "cd", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "cl", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "cls", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "cp", kind: 1, category: 25, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "d", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "dc", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "ef", kind: 3, category: 18, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "em", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "esb", kind: 8, category: 26, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "esbe", kind: 8, category: 26, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ex", kind: 3, category: 19, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "f", kind: 3, category: 18, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "fdc", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fe", kind: 3, category: 18, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "fig", kind: 7, category: 30, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "fk", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fl", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fm", kind: 2, category: 16, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "fp", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fq", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fqa", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fr", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "ft", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fv", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "fw", kind: 2, category: 16, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "h", kind: 1, category: 1, closing: 0, shape: 0, numbering: 3, ws: 0 },
  { name: "ib", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "id", kind: 13, category: 29, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "ide", kind: 1, category: 1, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "ie", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "iex", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ili", kind: 1, category: 2, closing: 0, shape: 0, numbering: 2, ws: 6 },
  { name: "im", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "imi", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "imq", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "imt", kind: 1, category: 2, closing: 0, shape: 0, numbering: 4, ws: 6 },
  { name: "imte", kind: 1, category: 2, closing: 0, shape: 0, numbering: 2, ws: 6 },
  { name: "io", kind: 1, category: 2, closing: 0, shape: 0, numbering: 4, ws: 6 },
  { name: "ior", kind: 2, category: 12, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "iot", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ip", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ipc", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ipi", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ipq", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ipr", kind: 1, category: 2, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "iq", kind: 1, category: 2, closing: 0, shape: 0, numbering: 3, ws: 6 },
  { name: "iqt", kind: 2, category: 12, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "is", kind: 1, category: 2, closing: 0, shape: 0, numbering: 2, ws: 6 },
  { name: "it", kind: 2, category: 10, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "jmp", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "k", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "lf", kind: 1, category: 6, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "lh", kind: 1, category: 6, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "li", kind: 1, category: 6, closing: 0, shape: 0, numbering: 4, ws: 6 },
  { name: "lik", kind: 2, category: 14, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "lim", kind: 1, category: 6, closing: 0, shape: 0, numbering: 4, ws: 6 },
  { name: "list", kind: 6, category: 20, closing: 3, shape: 0, numbering: 0, ws: 1 },
  { name: "lit", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "litl", kind: 2, category: 14, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "liv", kind: 2, category: 14, closing: 1, shape: 0, numbering: 14, ws: 6 },
  { name: "m", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "mi", kind: 1, category: 4, closing: 0, shape: 0, numbering: 3, ws: 6 },
  { name: "mr", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "ms", kind: 1, category: 3, closing: 0, shape: 0, numbering: 3, ws: 0 },
  { name: "mt", kind: 1, category: 3, closing: 0, shape: 0, numbering: 4, ws: 0 },
  { name: "mte", kind: 1, category: 3, closing: 0, shape: 0, numbering: 2, ws: 0 },
  { name: "nb", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "nd", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "no", kind: 2, category: 10, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "ord", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "p", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pb", kind: 2, category: 11, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pc", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "periph", kind: 9, category: 28, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "ph", kind: 1, category: 4, closing: 0, shape: 0, numbering: 3, ws: 6 },
  { name: "pi", kind: 1, category: 4, closing: 0, shape: 0, numbering: 3, ws: 6 },
  { name: "pm", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pmc", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pmo", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pmr", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pn", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "png", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "po", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pr", kind: 1, category: 4, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "pro", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "q", kind: 1, category: 5, closing: 0, shape: 0, numbering: 4, ws: 6 },
  { name: "qa", kind: 1, category: 5, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "qac", kind: 2, category: 13, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "qc", kind: 1, category: 5, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "qd", kind: 1, category: 5, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "qm", kind: 1, category: 5, closing: 0, shape: 0, numbering: 3, ws: 6 },
  { name: "qr", kind: 1, category: 5, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "qs", kind: 2, category: 13, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "qt", kind: 6, category: 22, closing: 3, shape: 2, numbering: 5, ws: 1 },
  { name: "qt", kind: 2, category: 9, closing: 1, shape: 1, numbering: 0, ws: 6 },
  { name: "r", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "rb", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "ref", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "rem", kind: 1, category: 1, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "rq", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "s", kind: 1, category: 3, closing: 0, shape: 0, numbering: 4, ws: 6 },
  { name: "sc", kind: 2, category: 10, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "sd", kind: 1, category: 3, closing: 0, shape: 0, numbering: 4, ws: 0 },
  { name: "sig", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "sls", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "sp", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "sr", kind: 1, category: 3, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "sts", kind: 1, category: 1, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "sup", kind: 2, category: 10, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "ta", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "table", kind: 6, category: 21, closing: 3, shape: 0, numbering: 0, ws: 1 },
  { name: "tc", kind: 12, category: 15, closing: 0, shape: 0, numbering: 15, ws: 6 },
  { name: "tcc", kind: 12, category: 15, closing: 0, shape: 0, numbering: 15, ws: 6 },
  { name: "tcr", kind: 12, category: 15, closing: 0, shape: 0, numbering: 15, ws: 6 },
  { name: "th", kind: 12, category: 15, closing: 0, shape: 0, numbering: 15, ws: 6 },
  { name: "thc", kind: 12, category: 15, closing: 0, shape: 0, numbering: 15, ws: 6 },
  { name: "thr", kind: 12, category: 15, closing: 0, shape: 0, numbering: 15, ws: 6 },
  { name: "tl", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "toc", kind: 1, category: 1, closing: 0, shape: 0, numbering: 3, ws: 0 },
  { name: "toca", kind: 1, category: 1, closing: 0, shape: 0, numbering: 3, ws: 0 },
  { name: "tr", kind: 11, category: 7, closing: 0, shape: 0, numbering: 0, ws: 6 },
  { name: "ts", kind: 6, category: 23, closing: 3, shape: 0, numbering: 0, ws: 1 },
  { name: "usfm", kind: 13, category: 29, closing: 0, shape: 0, numbering: 0, ws: 0 },
  { name: "v", kind: 5, category: 25, closing: 0, shape: 0, numbering: 0, ws: 2 },
  { name: "va", kind: 2, category: 25, closing: 1, shape: 0, numbering: 0, ws: 0 },
  { name: "vid", kind: 6, category: 24, closing: 3, shape: 0, numbering: 0, ws: 1 },
  { name: "vp", kind: 2, category: 25, closing: 1, shape: 0, numbering: 0, ws: 0 },
  { name: "w", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "wa", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "wg", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "wh", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "wj", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "wl", kind: 2, category: 9, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "x", kind: 3, category: 19, closing: 1, shape: 0, numbering: 0, ws: 6 },
  { name: "xdc", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xk", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xnt", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xo", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xop", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xot", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xq", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xt", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
  { name: "xta", kind: 2, category: 17, closing: 2, shape: 0, numbering: 0, ws: 6 },
];

/**
 * The lint catalog — one row per code, from `lint::LINT_ROWS`.
*
 * `severity` is the base rung and `escalation` the ladder above it, walked
* with the document's declared `\usfm` version. A `null` severity is a GATE:
* the code says nothing until a version at or above its first rung is
* declared.
 */
export const CATALOG = {
  "schema": "onion-diagnostics-v1",
  "codes": [
    {"code": 0, "name": "unclosed-note", "category": "structure", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} was never closed", "formatter": false, "fixLabel": "insert the note closer"},
    {"code": 1, "name": "unclosed-char", "category": "structure", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} was never closed", "formatter": false, "fixLabel": "insert the closer"},
    {"code": 2, "name": "unclosed-at-eof", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} is still open at the end of the book", "formatter": false, "fixLabel": "insert the closer"},
    {"code": 3, "name": "unterminated-container", "category": "structure", "severity": "warning", "escalation": [["4.0", "error"]], "aux": "none", "template": "{anchor} container was not closed by its end milestone", "formatter": false, "fixLabel": "insert the container end milestone"},
    {"code": 4, "name": "unterminated-milestone", "category": "structure", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} milestone is missing its \\*", "formatter": false, "fixLabel": "insert \\*"},
    {"code": 5, "name": "orphan-closer", "category": "structure", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} closes nothing", "formatter": false, "fixLabel": "delete the closer"},
    {"code": 6, "name": "orphan-terminator", "category": "structure", "severity": "error", "escalation": [], "aux": "none", "template": "\\* terminates no milestone", "formatter": false, "fixLabel": "delete \\*"},
    {"code": 7, "name": "orphan-container-end", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} ends no open container", "formatter": false, "fixLabel": null},
    {"code": 8, "name": "content-outside-sidebar-rule", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} is inside the sidebar opened by {second}", "formatter": false, "fixLabel": null},
    {"code": 9, "name": "unknown-marker", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} is not a known marker", "formatter": false, "fixLabel": null},
    {"code": 10, "name": "nested-spelling-misuse", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} is not a character marker; the nested spelling does not apply", "formatter": false, "fixLabel": null},
    {"code": 11, "name": "missing-paragraph", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} is not inside a paragraph", "formatter": true, "fixLabel": "insert \\p"},
    {"code": 12, "name": "designator-malformed", "category": "ordering", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} is not a valid chapter/verse number", "formatter": false, "fixLabel": null},
    {"code": 13, "name": "chapter-duplicate", "category": "ordering", "severity": "error", "escalation": [], "aux": "expectedNumber", "template": "chapter {anchor} repeats the chapter at {second}; expected {aux}", "formatter": false, "fixLabel": "renumber to the expected chapter"},
    {"code": 14, "name": "chapter-out-of-order", "category": "ordering", "severity": "error", "escalation": [], "aux": "expectedNumber", "template": "chapter {anchor} goes backwards from {second}; expected {aux}", "formatter": false, "fixLabel": "renumber to the expected chapter"},
    {"code": 15, "name": "chapter-gap", "category": "ordering", "severity": "warning", "escalation": [], "aux": "expectedNumber", "template": "chapter {anchor} skips ahead; expected {aux}", "formatter": false, "fixLabel": null},
    {"code": 16, "name": "verse-duplicate", "category": "ordering", "severity": "warning", "escalation": [], "aux": "expectedNumber", "template": "verse {anchor} repeats the verse at {second}; expected {aux}", "formatter": false, "fixLabel": "renumber to the expected verse"},
    {"code": 17, "name": "verse-out-of-order", "category": "ordering", "severity": "warning", "escalation": [], "aux": "expectedNumber", "template": "verse {anchor} goes backwards from {second}; expected {aux}", "formatter": false, "fixLabel": "renumber to the expected verse"},
    {"code": 18, "name": "verse-gap", "category": "ordering", "severity": "warning", "escalation": [], "aux": "expectedNumber", "template": "verse {anchor} skips ahead; expected {aux}", "formatter": false, "fixLabel": null},
    {"code": 19, "name": "missing-verse-one", "category": "ordering", "severity": "warning", "escalation": [], "aux": "expectedNumber", "template": "this chapter starts at verse {anchor}; expected {aux}", "formatter": false, "fixLabel": null},
    {"code": 20, "name": "verse-before-first-chapter", "category": "ordering", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} comes before the book's first \\c", "formatter": false, "fixLabel": null},
    {"code": 21, "name": "missing-chapter", "category": "ordering", "severity": "warning", "escalation": [], "aux": "none", "template": "this book has verses but no \\c", "formatter": false, "fixLabel": null},
    {"code": 22, "name": "missing-id", "category": "payload", "severity": "error", "escalation": [], "aux": "none", "template": "this book has no \\id line", "formatter": false, "fixLabel": null},
    {"code": 23, "name": "book-code-unknown", "category": "payload", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} is not a book identifier", "formatter": false, "fixLabel": null},
    {"code": 24, "name": "book-code-not-uppercase", "category": "payload", "severity": "warning", "escalation": [], "aux": "none", "template": "book identifier {anchor} should be uppercase", "formatter": false, "fixLabel": "uppercase the book identifier"},
    {"code": 25, "name": "chapter-without-designator", "category": "payload", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} has no chapter number", "formatter": false, "fixLabel": null},
    {"code": 26, "name": "verse-without-designator", "category": "payload", "severity": "error", "escalation": [], "aux": "none", "template": "{anchor} has no verse number", "formatter": true, "fixLabel": "delete the empty verse marker"},
    {"code": 27, "name": "ca-cp-placement", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} must follow the \\c it re-numbers", "formatter": false, "fixLabel": null},
    {"code": 28, "name": "va-vp-placement", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} must follow the \\v it re-numbers", "formatter": false, "fixLabel": null},
    {"code": 29, "name": "caller-shape", "category": "payload", "severity": "hint", "escalation": [], "aux": "none", "template": "{anchor} is an unusual note caller", "formatter": false, "fixLabel": null},
    {"code": 30, "name": "numbering-mix", "category": "payload", "severity": "info", "escalation": [], "aux": "numberingCap", "template": "{anchor} mixes numbered and bare spellings with {second} (levels 1-{aux})", "formatter": false, "fixLabel": null},
    {"code": 31, "name": "marker-not-ws-preceded", "category": "form", "severity": "hint", "escalation": [], "aux": "none", "template": "{anchor} needs whitespace before it", "formatter": true, "fixLabel": "insert a line break"},
    {"code": 32, "name": "delimiter-shape", "category": "form", "severity": "hint", "escalation": [], "aux": "none", "template": "{anchor} is not followed by structural whitespace", "formatter": false, "fixLabel": null},
    {"code": 33, "name": "empty-paragraph", "category": "form", "severity": "info", "escalation": [], "aux": "none", "template": "{anchor} has no content", "formatter": true, "fixLabel": "delete the empty paragraph"},
    {"code": 34, "name": "attr-trailing-form-deprecated", "category": "attributes", "severity": null, "escalation": [["3.2", "warning"], ["4.0", "error"]], "aux": "version", "template": "the trailing attribute form is deprecated in USFM {aux}", "formatter": false, "fixLabel": null},
    {"code": 35, "name": "attr-both-lists", "category": "attributes", "severity": "warning", "escalation": [], "aux": "none", "template": "a second attribute list overrides the one at {second}", "formatter": false, "fixLabel": null},
    {"code": 36, "name": "attr-terminator-mismatch", "category": "attributes", "severity": "warning", "escalation": [], "aux": "none", "template": "the attribute list on {second} is closed by the wrong marker", "formatter": false, "fixLabel": null},
    {"code": 37, "name": "attr-pipe-hint", "category": "attributes", "severity": "hint", "escalation": [], "aux": "none", "template": "did you mean an attribute list on {second}?", "formatter": false, "fixLabel": null},
    {"code": 38, "name": "attr-unknown-name", "category": "attributes", "severity": "hint", "escalation": [], "aux": "count", "template": "{second} defines no such attribute", "formatter": false, "fixLabel": null},
    {"code": 39, "name": "attr-malformed", "category": "attributes", "severity": "warning", "escalation": [], "aux": "malformedShape", "template": "the attribute list on {second} stops making sense", "formatter": false, "fixLabel": null},
    {"code": 40, "name": "attr-required-if", "category": "attributes", "severity": "warning", "escalation": [], "aux": "none", "template": "{second} is missing an attribute this occurrence requires", "formatter": false, "fixLabel": null},
    {"code": 41, "name": "deprecated-marker", "category": "version", "severity": null, "escalation": [["3.0", "warning"], ["4.0", "error"]], "aux": "version", "template": "{anchor} is deprecated since USFM {aux}", "formatter": false, "fixLabel": "rename to the replacement marker"},
    {"code": 42, "name": "deprecated-attribute", "category": "version", "severity": "info", "escalation": [], "aux": "none", "template": "the attribute list on {second} uses a deprecated attribute", "formatter": false, "fixLabel": null},
    {"code": 43, "name": "marker-out-of-band", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} belongs earlier in the book than this", "formatter": false, "fixLabel": null},
    {"code": 44, "name": "duplicate-id", "category": "payload", "severity": "error", "escalation": [], "aux": "none", "template": "this book already has an \\id line", "formatter": false, "fixLabel": "delete the duplicate line"},
    {"code": 45, "name": "paragraph-before-first-chapter", "category": "structure", "severity": "warning", "escalation": [], "aux": "none", "template": "{anchor} body paragraph before the book's first \\c", "formatter": false, "fixLabel": null},
    {"code": 46, "name": "delimiter-surplus", "category": "form", "severity": "hint", "escalation": [], "aux": "none", "template": "{anchor} reducible whitespace after a delimiter", "formatter": true, "fixLabel": "remove the extra whitespace"},
    {"code": 47, "name": "duplicate-usfm", "category": "payload", "severity": "error", "escalation": [], "aux": "none", "template": "this book already has a \\usfm line", "formatter": false, "fixLabel": "delete the duplicate line"},
    {"code": 48, "name": "remove-marker", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "{anchor} was removed on request", "formatter": false, "fixLabel": "remove the marker"},
    {"code": 49, "name": "bridge-empty-verses", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "{anchor} opens a run of empty verses", "formatter": false, "fixLabel": "bridge the empty verses"},
    {"code": 50, "name": "dedupe-verse-number", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "the text after {anchor} repeats the verse number", "formatter": false, "fixLabel": "delete the repeated verse number"},
    {"code": 51, "name": "block-marker-own-line", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "{anchor} belongs at the start of a line", "formatter": false, "fixLabel": "start a line here"},
    {"code": 52, "name": "char-marker-line-join", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "this line break sits on a character-marker boundary", "formatter": false, "fixLabel": "join the line"},
    {"code": 53, "name": "collapse-blank-lines", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "blank lines", "formatter": false, "fixLabel": "collapse the blank lines"},
    {"code": 54, "name": "normalize-newlines", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "this line ending is not the configured form", "formatter": false, "fixLabel": "normalize the line ending"},
    {"code": 55, "name": "trim-text-edges", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "whitespace at the edge of a text run", "formatter": false, "fixLabel": "collapse the edge whitespace"},
    {"code": 56, "name": "delimiter-single", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "{anchor} is followed by more than one space", "formatter": false, "fixLabel": "reduce the delimiter to one space"},
    {"code": 57, "name": "designator-ws-single", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "{anchor} is followed by more than one space", "formatter": false, "fixLabel": "reduce the payload delimiter to one space"},
    {"code": 58, "name": "marker-ws-at-line-start", "category": "form", "severity": "form", "escalation": [], "aux": "none", "template": "{anchor} is indented", "formatter": false, "fixLabel": "delete the indentation"}
  ]
} as const;

/** The rows, by code. A diagnostic's `code` field indexes this. */
export const CODES = CATALOG.codes;

// ---------------------------------------------------------------------------
// Views over one parse — hand-written, and stating no engine fact
// ---------------------------------------------------------------------------

/** One span, in whatever space the parse was asked for. */
export interface Span {
  from: number;
  to: number;
}

/** A marker's table row. `null` fields belong to row 0, the unresolved row. */
export class Marker {
  readonly idx: number;

  constructor(idx: number) {
    this.idx = idx;
  }

  /** The table's canonical name — `null` on row 0, which has none. */
  name(): string | null {
    return this.idx === 0 ? null : (MARKERS[this.idx]?.name ?? null);
  }

  /** One of `MarkerKind`. */
  kind(): number {
    return MARKERS[this.idx]?.kind ?? 0;
  }

  /** One of `Category` — `ParaBody` is distinct from `ParaPoetry`. */
  category(): number {
    return MARKERS[this.idx]?.category ?? 0;
  }

  /** One of `ClosingBehavior`. */
  closing(): number {
    return MARKERS[this.idx]?.closing ?? 0;
  }

  /** One of `Numbering`. */
  numbering(): number {
    return MARKERS[this.idx]?.numbering ?? 0;
  }

  /** One of `SpellingShape`. */
  shape(): number {
    return MARKERS[this.idx]?.shape ?? 0;
  }

  /**
   * One of `StructuralWhitespaceRequirement`: what must follow this marker's
   * name. `SingleNewline` is the rule for a marker that takes no content on its
   * own line.
   */
  ws(): number {
    return MARKERS[this.idx]?.ws ?? 0;
  }

  /**
   * Row 0: an unknown name, a `\z` extension, an illegal spelling. The row has
   * no name, so the actual spelling is only in the document —
   * `TokenView.spelling(text)` reads it, and is the one place to.
   */
  isUnknown(): boolean {
    return this.idx === 0;
  }
}

/** One leaf. */
export class TokenView {
  readonly isNode = false;
  readonly id: number;
  private readonly rows: TokenRow;

  constructor(rows: TokenRow, id: number) {
    this.rows = rows;
    this.id = id;
  }

  span(): Span {
    const r = this.rows.seek(this.id);
    return { from: r.start, to: r.end };
  }

  /** One of `TokenKind`, with the spelling bit stripped. */
  kind(): number {
    return this.rows.seek(this.id).kind & ~TOKEN_SPELLING_BIT;
  }

  /**
   * The last byte of the span is the one horizontal delimiter the scanner
   * folded on — `\v ` keeps the space, `\v  1` puts the surplus in a `Pad`.
   * Only `Marker`, `Milestone`, `Designator`, `NoteCaller` and `BookCode` fold.
   */
  delimiterFolded(): boolean {
    return (this.rows.seek(this.id).flags & TOKEN_DELIMITER_FOLDED) !== 0;
  }

  /** A `Text` token of nothing but spaces and tabs. */
  isBlank(): boolean {
    return (this.rows.seek(this.id).flags & TOKEN_BLANK) !== 0;
  }

  /**
   * Where the token's PAYLOAD ends: `end`, or one back from it when a
   * delimiter is folded on. One in either space — a space and a tab are one
   * byte and one UTF-16 code unit alike — so this is right whichever the parse
   * asked for.
   */
  payloadEnd(): number {
    const r = this.rows.seek(this.id);
    return (r.flags & TOKEN_DELIMITER_FOLDED) !== 0 ? r.end - 1 : r.end;
  }

  /**
   * The marker as the author SPELLED it, `text` being the document this parse
   * came from: `"q2"`, `"+add"` sliced past the `+`, `"qt1-s"`, `"w"` from
   * `\w*`. `""` for a kind that is not marker-shaped.
   *
   *   \q2 → "q2"   \+nd → "nd"   \zaln-s → "zaln-s"   \add* → "add"
   *
   * Level digits and a milestone's `-s`/`-e` half are part of the spelling;
   * the `\`, the `+` and a closer's `*` are punctuation and are not. THE place
   * to read an unknown marker's name — `Marker.name()` is `null` on row 0.
   *
   * A JS string indexes in UTF-16, so `text` and the dish must agree: parse
   * with `utf16: true`, or hold an all-ASCII document.
   */
  spelling(text: string): string {
    const r = this.rows.seek(this.id);
    const kind = r.kind & ~TOKEN_SPELLING_BIT;
    if (!isMarkerKind(kind)) return "";
    let from = r.start + 1;
    if (kind !== TokenKind.Milestone && (r.kind & TOKEN_SPELLING_BIT) !== 0) from += 1;
    let to = this.payloadEnd();
    if (kind === TokenKind.ClosingMarker && text[to - 1] === "*") to -= 1;
    return text.slice(from, to);
  }

  /** `\+` nesting on a marker, the `-e` half on a milestone. */
  spelled(): boolean {
    return (this.rows.seek(this.id).kind & TOKEN_SPELLING_BIT) !== 0;
  }

  /** The resolved row when this token IS a marker; `null` otherwise. */
  marker(): Marker | null {
    const r = this.rows.seek(this.id);
    return isMarkerKind(r.kind & ~TOKEN_SPELLING_BIT) ? new Marker(r.marker) : null;
  }

  /**
   * The trailing number as SPELLED — 2 for `\q2`, 1 for `\tc1`, 0 for a bare
   * `\q` and for every token that is not a numbered marker.
   *
   * `Marker.numbering()` is the row's cap, and says what the number MEANS: a
   * nesting level, or a table column index. `\q1` and `\q2` share a row, so
   * this is its only home — reading it here is what lets a consumer render
   * poetry levels, or a table's columns, without slicing a document byte.
   */
  level(): number {
    return this.rows.seek(this.id).level;
  }
}

/** One structural node. */
export class NodeView {
  readonly isNode = true;
  readonly id: number;
  private readonly tree: Tree;

  constructor(tree: Tree, id: number) {
    this.tree = tree;
    this.id = id;
  }

  /**
   * Its opening marker through the end of its last descendant TOKEN.
   *
   * Walked, not read off the last child: a child is as likely to be a node as
   * a token, and an unclosed note's recovery newline lands inside the
   * INNERMOST node rather than on the note's own child list. `child(childCount
   * - 1).span().to` is not this value.
   */
  span(): Span {
    return this.tree.extent(this.id);
  }

  /** The resolved row; `null` on the root, which no marker opens. */
  marker(): Marker | null {
    const token = this.tree.nodes.seek(this.id).token;
    if (token === NONE) return null;
    return new Marker(this.tree.tokens.seek(token).marker);
  }

  /** Its opening marker's level; 0 on the root and on an unnumbered marker. */
  level(): number {
    const token = this.tree.nodes.seek(this.id).token;
    if (token === NONE) return 0;
    return this.tree.tokens.seek(token).level;
  }

  /** "Is this a container?" — the div/element question, no arena walk. */
  hasChildren(): boolean {
    const r = this.tree.nodes.seek(this.id);
    return r.childTo > r.childFrom;
  }

  childCount(): number {
    const r = this.tree.nodes.seek(this.id);
    return r.childTo - r.childFrom;
  }

  /** One resolved child. Structure and text interleave; check `isNode`. */
  child(i: number): NodeView | TokenView {
    const r = this.tree.nodes.seek(this.id);
    return this.tree.resolve(this.tree.childIds[r.childFrom + i]);
  }

  /** Every child, in document order. */
  children(): (NodeView | TokenView)[] {
    const out: (NodeView | TokenView)[] = [];
    for (let i = 0, n = this.childCount(); i < n; i++) out.push(this.child(i));
    return out;
  }

  /** One of `CloseReason` — `Explicit` is the well-formed answer. */
  closeReason(): number {
    return this.tree.nodes.seek(this.id).reason;
  }

  /** One of `SpecContext`: where in the document grammar this sits. */
  context(): number {
    return this.tree.nodes.seek(this.id).ctx;
  }
}

/** The tree, and the arena behind it. */
export class Tree {
  readonly nodes: NodeRow;
  readonly tokens: TokenRow;
  readonly childIds: Uint32Array;
  private cachedOwnership: { owners: Uint32Array; parents: Uint32Array } | null = null;

  constructor(nodes: NodeRow, tokens: TokenRow, childIds: Uint32Array) {
    this.nodes = nodes;
    this.tokens = tokens;
    this.childIds = childIds;
  }

  /** The document node. Everything hangs off it. */
  root(): NodeView {
    return new NodeView(this, 0);
  }

  nodeCount(): number {
    return this.nodes.length;
  }

  /** A child id resolved to whichever kind it names. */
  resolve(id: number): NodeView | TokenView {
    return (id & NODE_ID_BIT) !== 0
      ? new NodeView(this, id & ~NODE_ID_BIT)
      : new TokenView(this.tokens, id);
  }

  /**
   * Document order, structure and text interleaved. Without an argument it
   * walks the whole document; with one, that node's subtree.
   */
  *walk(from?: NodeView | number): IterableIterator<NodeView | TokenView> {
    const start = typeof from === "number" ? from : (from?.id ?? 0);
    const stack: number[][] = [this.childRange(start)];
    while (stack.length) {
      const range = stack[stack.length - 1];
      if (range[0] === range[1]) {
        stack.pop();
        continue;
      }
      const id = this.childIds[range[0]++];
      const item = this.resolve(id);
      yield item;
      if (item.isNode) stack.push(this.childRange(item.id));
    }
  }

  /**
   * Every node in document order, WITHOUT the tokens between them.
   *
   * `walk()` reads the child arena and yields structure and text interleaved,
   * which is what a scan of everything wants. A structural question — every
   * paragraph, an outline, "does this book have sidebars" — pays for the
   * tokens it skips: on Psalms that is 6,781 nodes among 30,896 tokens.
   *
   * This never touches the arena. Node ids ascend with their opening markers,
   * so a row index IS document order (asserted over the corpus in onion's
   * `cst_oracle`).
   *
   * FLAT: depth and parent are not reported. Nesting is still there — a `\p`
   * inside an `\esb` has its extent inside the sidebar's — but you learn it by
   * comparing extents. To build a tree, recurse `root()` and `children()`.
   */
  *walkNodes(): IterableIterator<NodeView> {
    for (let id = 0, n = this.nodes.length; id < n; id++) yield new NodeView(this, id);
  }

  /**
   * The FIRST descendant token's INDEX.
   *
   *   \p \v 1 a\f + \ft note\f*    firstToken(the note) → the `\f` token
   *                                lastToken(the note)  → the `\f*` token
   *
   * A descent, because a child is as likely to be a node as a token — the last
   * child of `\f` is usually the `\ft` node. A childless node answers with its
   * own opening marker, the only token it has, which is `NONE` on the root of
   * an empty document.
   */
  firstToken(node: number): number {
    return this.edgeToken(node, true);
  }

  /** The LAST descendant token's index. `firstToken`'s twin. */
  lastToken(node: number): number {
    return this.edgeToken(node, false);
  }

  /**
   * One node's extent: its opening marker through the end of its last
   * descendant TOKEN, in whichever space the parse was asked for.
   */
  extent(node: number): Span {
    const first = this.firstToken(node);
    if (first === NONE || first >= this.tokens.length) return { from: 0, to: 0 };
    const from = this.tokens.seek(first).start;
    // Only the root is childless, and only on an empty document.
    const r = this.nodes.seek(node);
    if (r.childFrom === r.childTo) return { from, to: from };
    return { from, to: this.tokens.seek(this.lastToken(node)).end };
  }

  /**
   * The descent behind both edges. Every field of a row is read BEFORE the
   * step that moves the cursor off it, so no read is stale.
   */
  private edgeToken(node: number, first: boolean): number {
    for (;;) {
      const r = this.nodes.seek(node);
      const childFrom = r.childFrom;
      const childTo = r.childTo;
      if (childFrom === childTo) return r.token;
      const id = this.childIds[first ? childFrom : childTo - 1];
      if ((id & NODE_ID_BIT) === 0) return id;
      node = id & ~NODE_ID_BIT;
    }
  }

  /**
   * Token index → the id of the innermost node that owns it.
   *
   *   \p \v 1 a\f + \ft note\f*
   *           ^         ^ the `\ft` node, not the `\f` that contains it
   *           the `\p` node
   *
   * Every token id appears EXACTLY ONCE in the child arena, so ownership is
   * total and unambiguous: no token is unowned and none has two owners.
   *
   * Built on first call from ONE walk of the arena, and kept — `parent()`
   * comes out of the same pass.
   */
  owners(): Uint32Array {
    return this.ownership().owners;
  }

  /** A node's parent, `NONE` on the root. The same one walk as `owners()`. */
  parent(node: number): number {
    return this.ownership().parents[node] ?? NONE;
  }

  private ownership(): { owners: Uint32Array; parents: Uint32Array } {
    if (this.cachedOwnership !== null) return this.cachedOwnership;
    const owners = new Uint32Array(this.tokens.length).fill(NONE);
    const parents = new Uint32Array(this.nodes.length).fill(NONE);
    const stack = [0];
    while (stack.length) {
      const node = stack.pop() as number;
      const [from, to] = this.childRange(node);
      for (let slot = from; slot < to; slot++) {
        const id = this.childIds[slot];
        if ((id & NODE_ID_BIT) === 0) {
          owners[id] = node;
        } else {
          const child = id & ~NODE_ID_BIT;
          parents[child] = node;
          stack.push(child);
        }
      }
    }
    this.cachedOwnership = { owners, parents };
    return this.cachedOwnership;
  }

  private childRange(node: number): number[] {
    const r = this.nodes.seek(node);
    return [r.childFrom, r.childTo];
  }

  /**
   * The innermost node containing `pos` — the caret question.
   *
   * A descent, not a scan: at each level the containing child wins, so nesting
   * (`\p` inside `\esb`) resolves to the inner one.
   */
  nodeAt(pos: number): NodeView | null {
    let best: number | null = null;
    let node = 0;
    for (;;) {
      const [from, to] = this.childRange(node);
      let next: number | null = null;
      for (let slot = from; slot < to; slot++) {
        const id = this.childIds[slot];
        if ((id & NODE_ID_BIT) === 0) continue;
        const child = id & ~NODE_ID_BIT;
        const span = this.extent(child);
        // Children are in document order, so once one starts past `pos`
        // nothing after it can contain `pos` either.
        if (span.from > pos) break;
        if (pos < span.to) {
          next = child;
          break;
        }
      }
      if (next === null) return best === null ? null : new NodeView(this, best);
      best = next;
      node = next;
    }
  }
}

/** Every token, as a sequence. */
export class Tokens {
  readonly rows: TokenRow;

  constructor(rows: TokenRow) {
    this.rows = rows;
  }

  get length(): number {
    return this.rows.length;
  }

  at(i: number): TokenView {
    return new TokenView(this.rows, i);
  }

  *[Symbol.iterator](): IterableIterator<TokenView> {
    for (let i = 0, n = this.rows.length; i < n; i++) yield new TokenView(this.rows, i);
  }

  /**
   * Every token WITHOUT allocating a view per row — the shape a whole-book
   * syntax pass wants. Return `false` to stop.
   *
   * `markerIdx` is an INDEX, not a resolved row, and that is deliberate: the
   * point of this path is that it allocates nothing, and a `Marker` per token
   * is exactly what it exists to avoid. The 153-row table ships in this file,
   * so `MARKERS[markerIdx]` resolves it with one array read and no call — the
   * row is still local, it is simply not wrapped.
   */
  forEach(fn: (kind: number, markerIdx: number, from: number, to: number) => void | boolean): void {
    for (let i = 0, n = this.rows.length; i < n; i++) {
      const r = this.rows.seek(i);
      if (fn(r.kind, r.marker, r.start, r.end) === false) return;
    }
  }
}

/** One edit of a repair. */
export interface FixEdit extends Span {
  insert: string;
}

/** One finding. */
export class DiagnosticView {
  readonly id: number;
  private readonly d: DiagnosticRow;
  private readonly f: FixRow;
  private readonly e: EditRow;
  private readonly text: string;

  constructor(d: DiagnosticRow, f: FixRow, e: EditRow, text: string, id: number) {
    this.d = d;
    this.f = f;
    this.e = e;
    this.text = text;
    this.id = id;
  }

  /** The catalog row: name, category, severity ladder, template. */
  code(): (typeof CODES)[number] {
    return CODES[this.d.seek(this.id).code];
  }

  span(): Span {
    const r = this.d.seek(this.id);
    return { from: r.from, to: r.to };
  }

  /** The other party — an opener, an owner, a first occurrence — or `null`. */
  second(): Span | null {
    const r = this.d.seek(this.id);
    return r.secondFrom === NONE ? null : { from: r.secondFrom, to: r.secondTo };
  }

  /** The code's aux integer. What it MEANS is `code().aux`. */
  aux(): number {
    return this.d.seek(this.id).aux;
  }

  /** The offered repair, or `null`. */
  fix(): FixEdit[] | null {
    const at = this.d.seek(this.id).fix;
    if (at === NONE) return null;
    const f = this.f.seek(at);
    const out: FixEdit[] = [];
    for (let i = f.editFrom; i < f.editTo; i++) {
      const e = this.e.seek(i);
      out.push({
        from: e.from,
        to: e.to,
        insert: this.text.slice(e.textFrom, e.textFrom + e.textLen),
      });
    }
    return out;
  }

  /**
   * The severity this code carries in a document declaring `version` — the
   * ladder, walked. `null` means the code says nothing at that version.
   */
  severity(version: string | null): string | null {
    const row = this.code();
    let severity = row.severity;
    if (version === null) return severity;
    for (const [rung, at] of row.escalation) if (rung <= version) severity = at;
    return severity;
  }

  /**
   * The message, rendered from the template and the document's own bytes.
   * `slice` is the editor's `doc.sliceString`; no text crosses the wall to
   * make this.
   */
  message(slice: (from: number, to: number) => string): string {
    const span = this.span();
    const second = this.second();
    return this.code()
      .template.replace("{anchor}", slice(span.from, span.to))
      .replace("{second}", second ? slice(second.from, second.to) : "");
  }

  /** Where to go look: the chapter and verse containing this finding. */
  locate(toc: Toc): { chapter: number; verse: number } | null {
    return toc.at(this.span().from);
  }
}

/** Findings, as a sequence. */
export class Diagnostics {
  private readonly d: DiagnosticRow;
  private readonly f: FixRow;
  private readonly e: EditRow;
  private readonly text: string;

  constructor(d: DiagnosticRow, f: FixRow, e: EditRow, text: string) {
    this.d = d;
    this.f = f;
    this.e = e;
    this.text = text;
  }

  get length(): number {
    return this.d.length;
  }

  at(i: number): DiagnosticView {
    return new DiagnosticView(this.d, this.f, this.e, this.text, i);
  }

  *[Symbol.iterator](): IterableIterator<DiagnosticView> {
    for (let i = 0, n = this.d.length; i < n; i++) yield this.at(i);
  }
}

/** The chapter and verse index. Over the TOKEN stream, not the tree. */
export class Toc {
  readonly chapterRows: ChapterRow;
  readonly verseRows: VerseRow;

  constructor(chapterRows: ChapterRow, verseRows: VerseRow) {
    this.chapterRows = chapterRows;
    this.verseRows = verseRows;
  }

  chapters(): {
    number: number;
    token: number;
    designator: number;
    from: number;
    to: number;
  }[] {
    const out = [];
    for (let i = 0, n = this.chapterRows.length; i < n; i++) {
      const r = this.chapterRows.seek(i);
      out.push({
        number: r.number,
        token: r.token,
        designator: r.designator,
        from: r.start,
        to: r.end,
      });
    }
    return out;
  }

  verses(): {
    chapter: number;
    first: number;
    last: number;
    at: number;
    token: number;
    designator: number;
  }[] {
    const out = [];
    for (let i = 0, n = this.verseRows.length; i < n; i++) {
      const r = this.verseRows.seek(i);
      out.push({
        chapter: r.chapter,
        first: r.first,
        last: r.last,
        at: r.at,
        token: r.token,
        designator: r.designator,
      });
    }
    return out;
  }

  /**
   * Every chapter without allocating a row object — the twin of
   * `Tokens.forEach`, for a consumer that reads the toc per commit. Return
   * `false` to stop.
   */
  forEachChapter(
    fn: (number: number, from: number, to: number, token: number, designator: number) => void | boolean,
  ): void {
    for (let i = 0, n = this.chapterRows.length; i < n; i++) {
      const r = this.chapterRows.seek(i);
      if (fn(r.number, r.start, r.end, r.token, r.designator) === false) return;
    }
  }

  /** Every verse anchor, the same way. */
  forEachVerse(
    fn: (
      chapter: number,
      first: number,
      last: number,
      at: number,
      token: number,
      designator: number,
    ) => void | boolean,
  ): void {
    for (let i = 0, n = this.verseRows.length; i < n; i++) {
      const r = this.verseRows.seek(i);
      if (fn(r.chapter, r.first, r.last, r.at, r.token, r.designator) === false) return;
    }
  }

  /**
   * The chapter:verse address containing `pos` — the reverse index. Chapters
   * tile, so the chapter is a binary search; the verse is the last anchor at
   * or before `pos` within it.
   */
  at(pos: number): { chapter: number; verse: number } | null {
    const chapters = this.chapterRows;
    if (chapters.length === 0) return null;
    let lo = 0;
    let hi = chapters.length - 1;
    let found = 0;
    while (lo <= hi) {
      const mid = (lo + hi) >> 1;
      if (chapters.seek(mid).start <= pos) {
        found = mid;
        lo = mid + 1;
      } else hi = mid - 1;
    }
    const chapter = chapters.seek(found).number;

    // Anchors are sorted by `at`, so the verse is the last one at or before
    // `pos` — a binary search, not a scan.
    const verses = this.verseRows;
    lo = 0;
    hi = verses.length - 1;
    let verse = 0;
    while (lo <= hi) {
      const mid = (lo + hi) >> 1;
      const r = verses.seek(mid);
      if (r.at <= pos) {
        if (r.chapter === chapter) verse = r.first;
        lo = mid + 1;
      } else hi = mid - 1;
    }
    return { chapter, verse };
  }
}

// ---------------------------------------------------------------------------
// Attributes — the one export whose wire is a flat array, not a dish
// ---------------------------------------------------------------------------

/** u32s per attribute in what `attrs` returns: name span, then value span. */
export const ATTR_STRIDE = 4;

/** One attribute list, decoded. A bare value has an EMPTY name span. */
export interface AttrList {
  attrs: { name: Span; value: Span }[];
  /** `code` is a `MalformedAttr`. Absent when the list parsed clean. */
  malformed?: { code: number; at: number };
}

/**
 * What the wasm `attrs(text, from, to, utf16)` export returns, as objects.
 *
 *   const list = attrList(rawAttrs(text, from, to, 1));
 *   for (const { name, value } of list.attrs) …
 *
 * Four words per attribute and two at the tail, in whatever space the call
 * asked for. A malformed tail ENDS the list, so it is one finding and always
 * the last thing in the array.
 */
export function attrList(flat: Uint32Array | readonly number[]): AttrList {
  const attrs: { name: Span; value: Span }[] = [];
  for (let at = 0; at + ATTR_STRIDE <= flat.length - 2; at += ATTR_STRIDE) {
    attrs.push({
      name: { from: flat[at], to: flat[at + 1] },
      value: { from: flat[at + 2], to: flat[at + 3] },
    });
  }
  const code = flat[flat.length - 2];
  return code === NONE ? { attrs } : { attrs, malformed: { code, at: flat[flat.length - 1] } };
}

/** What a parse should compute. Everything defaults off except the tree. */
export interface ParseOptions {
  /** Run the lint walk — the one expensive optional. */
  diagnostics?: boolean;
  /** Build the chapter and verse index. Cheap, and needs no tree. */
  toc?: boolean;
  /** Emit every offset as a UTF-16 code unit instead of a byte. */
  utf16?: boolean;
}

/** The wasm export's own shape: positional, because an object cannot cross. */
export type RawParse = (
  text: string,
  diagnostics: boolean,
  toc: boolean,
  utf16: boolean,
) => Uint8Array;

/**
 * The typed door over a wasm build.
 *
 *   const onion = reader(rawParse);
 *   const dish = onion.parse(text, { diagnostics: true });
 *
 * The options object stops HERE and never crosses: through bindgen it would be
 * `Reflect::get` per key, where `{ diagnostcs: true }` reads as `false` and the
 * read comes back empty. As a TypeScript object literal the same typo is a
 * compile error, because `ParseOptions` declares no such property.
 *
 * Takes the raw export rather than importing one, so this file is agnostic
 * about which build it sits beside — bundler, web or node.
 */
export function reader(rawParse: RawParse): { parse(text: string, opts?: ParseOptions): Dish } {
  return {
    parse(text: string, opts: ParseOptions = {}): Dish {
      return deserialize(rawParse(text, !!opts.diagnostics, !!opts.toc, !!opts.utf16));
    },
  };
}

/** What `deserialize` hands back. */
export interface Dish {
  tree: Tree;
  tokens: Tokens;
  diagnostics: Diagnostics;
  toc: Toc;
  /** True when every offset is a UTF-16 code unit. */
  utf16: boolean;
  /**
   * The `\usfm` ladder index the document declares, or `NONE`. Decode with
   * `declaredVersion`.
   *
   * Crosses unconditionally because it GATES diagnostics: a finding's severity
   * is not knowable without it, and several codes say nothing at all until a
   * version is declared.
   */
  usfmVersion: number;
  /**
   * The source's length in the same space as every offset here — bytes, or
   * UTF-16 code units under `utf16`. An end-of-document position without
   * holding the text.
   */
  sourceLength: number;
  /**
   * xxh3-64 of the source BYTES, whatever space the offsets are in. Two dishes
   * of one document agree; the flag does not enter into it.
   */
  sourceHash: bigint;
}

/** The declared version as the string `DiagnosticView.severity` wants. */
export const declaredVersion = (dish: { usfmVersion: number }): string | null =>
  dish.usfmVersion === NONE ? null : (USFM_VERSIONS[dish.usfmVersion] ?? null);

/** `"ONCP"`, little-endian — a whole project, not one parse. */
export const CORPUS_MAGIC = 0x50434e4f;

/** Bumped when the envelope changes. Independent of each dish's own version. */
export const CORPUS_FORMAT_VERSION = 1;

/** One book out of a project buffer: the key you gave, and its parse. */
export interface CorpusBook {
  /** Carried back verbatim — onion never parses a key. */
  key: string;
  dish: Dish;
}

/**
 * Read a whole project.
 *
 * The envelope only frames: each book's bytes are exactly what a single parse
 * writes, so this decodes through `deserialize` and there is one reader for
 * both doors.
 *
 * Books are decoded LAZILY — the getter parses on first touch. A project-wide
 * findings panel that only wants counts should not pay to build a tree per
 * book.
 */
export function deserializeCorpus(bytes: Uint8Array): CorpusBook[] {
  const head = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (head.getUint32(0, true) !== CORPUS_MAGIC) throw new Error("onion: not a corpus buffer");
  const version = head.getUint32(4, true);
  if (version !== CORPUS_FORMAT_VERSION) {
    throw new Error(`onion: corpus version ${version}, reader expects ${CORPUS_FORMAT_VERSION}`);
  }
  const count = head.getUint32(8, true);
  const decoder = new TextDecoder();
  const out: CorpusBook[] = [];
  for (let n = 0; n < count; n++) {
    const entry = 16 + n * 16;
    const keyAt = head.getUint32(entry, true);
    const keyLen = head.getUint32(entry + 4, true);
    const dishAt = head.getUint32(entry + 8, true);
    const dishLen = head.getUint32(entry + 12, true);
    const key = decoder.decode(new Uint8Array(bytes.buffer, bytes.byteOffset + keyAt, keyLen));
    let dish: Dish | null = null;
    out.push({
      key,
      get dish(): Dish {
        dish ??= deserialize(new Uint8Array(bytes.buffer, bytes.byteOffset + dishAt, dishLen));
        return dish;
      },
    });
  }
  return out;
}

/**
 * Read one plated parse.
 *
 * Refuses a dish whose magic or version it does not recognise, rather than
 * misreading one.
 */
export function deserialize(dish: Uint8Array): Dish {
  const head = new DataView(dish.buffer, dish.byteOffset, dish.byteLength);
  if (head.getUint32(0, true) !== MAGIC) throw new Error("onion: not a parse buffer");
  const version = head.getUint32(4, true);
  if (version !== FORMAT_VERSION) {
    throw new Error(`onion: wire version ${version}, reader expects ${FORMAT_VERSION}`);
  }
  const count = head.getUint32(8, true);
  const utf16 = (head.getUint32(12, true) & FLAG_UTF16) !== 0;
  const usfmVersion = head.getUint32(16, true);
  const sourceLength = head.getUint32(20, true);
  const sourceHash = head.getBigUint64(24, true);

  const view = (n: number): DataView => {
    const at = head.getUint32(HEADER_BYTES + n * 8, true);
    const len = head.getUint32(HEADER_BYTES + n * 8 + 4, true);
    return new DataView(dish.buffer, dish.byteOffset + at, len);
  };
  if (count !== SECTION_NAMES.length) {
    throw new Error(`onion: ${count} sections, reader expects ${SECTION_NAMES.length}`);
  }

  const childIdsView = view(SECTION.childIds);
  const childIds = new Uint32Array(
    childIdsView.buffer,
    childIdsView.byteOffset,
    childIdsView.byteLength / 4,
  );
  const fixTextView = view(SECTION.fixText);
  const fixText = new TextDecoder().decode(
    new Uint8Array(fixTextView.buffer, fixTextView.byteOffset, fixTextView.byteLength),
  );

  const tokens = new TokenRow(view(SECTION.tokens));
  const tree = new Tree(new NodeRow(view(SECTION.nodes)), tokens, childIds);
  return {
    tree,
    tokens: new Tokens(tokens),
    diagnostics: new Diagnostics(
      new DiagnosticRow(view(SECTION.diagnostics)),
      new FixRow(view(SECTION.fixes)),
      new EditRow(view(SECTION.edits)),
      fixText,
    ),
    toc: new Toc(new ChapterRow(view(SECTION.chapters)), new VerseRow(view(SECTION.verses))),
    utf16,
    usfmVersion,
    sourceLength,
    sourceHash,
  };
}
