//! @generated by `cargo run --bin codegen` from `wire::schema`.
//! DO NOT EDIT — edit the schema or `wire::emit` and regenerate.
//! `tests/codegen_output_matches_input.rs` fails the build if this is stale.
//!
//! One writer per wire record. Fields go out in schema order, little-endian,
//! with no padding between them — nothing here casts a Rust struct, so nothing
//! depends on its layout. `offsets` collects the buffer position of every
//! source offset written, which is what lets `wire::plate` convert the whole
//! dish to UTF-16 in one sorted sweep instead of one per section.

// Every field is cast to its wire width uniformly, whether or not the engine's
// type already matches. A generator that emitted the cast only sometimes would
// be a generator with a special case in it; the redundant ones cost nothing.
#![allow(clippy::unnecessary_cast)]

use super::{Chapter, Diagnostic, Edit, Fix, Verse};

/// Where every source offset landed in a section's bytes, so `wire::plate` can
/// convert them all in one sorted sweep.
///
/// An alias rather than the type spelled out: it keeps every generated
/// signature under rustfmt's 100 columns, so what the emitter writes is what
/// `cargo fmt` leaves alone. A generator whose output the formatter rewrites
/// reports itself stale on every run.
pub type Offsets = Vec<usize>;

/// One lexical token: the leaves of the tree.
///
/// 12 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_tokens(
    rows: &[crate::Token],
    source: &[u8],
    out: &mut Vec<u8>,
    offsets: &mut Offsets,
) {
    out.reserve(rows.len() * 12);
    for t in rows {
        offsets.push(out.len());
        // Where the token begins.
        out.extend_from_slice(&((t.start) as u32).to_le_bytes());
        offsets.push(out.len());
        // Where it ends. Spans TILE the document, so ends ascend too.
        out.extend_from_slice(&((t.end()) as u32).to_le_bytes());
        // Packed TokenKind; bit 4 is the per-shape spelling bit.
        out.extend_from_slice(&((t.kind_bits) as u8).to_le_bytes());
        // Row in the marker table; 0 is UNRESOLVED.
        out.extend_from_slice(&((t.marker_idx) as u8).to_le_bytes());
        // The trailing number as spelled: 2 for `\q2`, 1 for `\tc1`, 0 for a bare `\q`. The row's `numbering` says whether it is a nesting level or a column index.
        out.extend_from_slice(&((t.level) as u8).to_le_bytes());
        // `TOKEN_DELIMITER_FOLDED` | `TOKEN_BLANK`. Also rounds the row to 12 bytes, so every row's `start` and `end` land aligned for a typed-array view over a 4-aligned section.
        out.extend_from_slice(&((t.wire_flags(source)) as u8).to_le_bytes());
    }
}

/// One structural node. `token` and the child range are indices, not offsets.
///
/// 14 bytes per row. Every field is an index or a code, so nothing
/// here is ever converted.
pub fn write_nodes(rows: &[crate::cst::Node], out: &mut Vec<u8>, _offsets: &mut Offsets) {
    out.reserve(rows.len() * 14);
    for n in rows {
        // The opening marker's token index; u32::MAX on the root.
        out.extend_from_slice(&((n.token) as u32).to_le_bytes());
        // Start of this node's range in the child arena.
        out.extend_from_slice(&((n.children.start) as u32).to_le_bytes());
        // End of that range. Ranges are neither contiguous nor monotonic.
        out.extend_from_slice(&((n.children.end) as u32).to_le_bytes());
        // CloseReason: Explicit, Implicit, Recovery, Eof.
        out.extend_from_slice(&((n.reason) as u8).to_le_bytes());
        // The stamped SpecContext.
        out.extend_from_slice(&((n.ctx) as u8).to_le_bytes());
    }
}

/// One finding, with its anchor resolved from a token index to a span.
///
/// 32 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_diagnostics(rows: &[Diagnostic], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 32);
    for d in rows {
        // Index into the lint catalog.
        out.extend_from_slice(&((d.code) as u32).to_le_bytes());
        offsets.push(out.len());
        // The anchor's start.
        out.extend_from_slice(&((d.from) as u32).to_le_bytes());
        offsets.push(out.len());
        // The anchor's end.
        out.extend_from_slice(&((d.to) as u32).to_le_bytes());
        offsets.push(out.len());
        // The other party's start, or NONE.
        out.extend_from_slice(&((d.second_from) as u32).to_le_bytes());
        offsets.push(out.len());
        // The other party's end, or NONE.
        out.extend_from_slice(&((d.second_to) as u32).to_le_bytes());
        // The code's aux integer; its meaning is the catalog row's.
        out.extend_from_slice(&((d.aux) as u32).to_le_bytes());
        // Index into the fix section, or NONE.
        out.extend_from_slice(&((d.fix) as u32).to_le_bytes());
        // Rounds the row to 32 bytes. Room for a u64 code or a checksum.
        out.extend_from_slice(&((0) as u32).to_le_bytes());
    }
}

/// One offered repair: the edits it owns.
///
/// 8 bytes per row. Every field is an index or a code, so nothing
/// here is ever converted.
pub fn write_fixes(rows: &[Fix], out: &mut Vec<u8>, _offsets: &mut Offsets) {
    out.reserve(rows.len() * 8);
    for f in rows {
        // Start of this fix's range in the edit section.
        out.extend_from_slice(&((f.edit_from) as u32).to_le_bytes());
        // End of that range.
        out.extend_from_slice(&((f.edit_to) as u32).to_le_bytes());
    }
}

/// One edit of a repair: replace [from, to) with the named text.
///
/// 16 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_edits(rows: &[Edit], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 16);
    for e in rows {
        offsets.push(out.len());
        // Where the replacement starts.
        out.extend_from_slice(&((e.from) as u32).to_le_bytes());
        offsets.push(out.len());
        // Where it ends; equal to `from` for a pure insertion.
        out.extend_from_slice(&((e.to) as u32).to_le_bytes());
        // Start of the inserted bytes in the fix-text section.
        out.extend_from_slice(&((e.text_from) as u32).to_le_bytes());
        // Their length. Zero is a pure deletion.
        out.extend_from_slice(&((e.text_len) as u32).to_le_bytes());
    }
}

/// One chapter's extent and number. The rows tile the document.
///
/// 18 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_chapters(rows: &[Chapter], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 18);
    for c in rows {
        offsets.push(out.len());
        // Where the chapter begins.
        out.extend_from_slice(&((c.start) as u32).to_le_bytes());
        offsets.push(out.len());
        // Where it ends.
        out.extend_from_slice(&((c.end) as u32).to_le_bytes());
        // The `\c` marker's token index; NONE on the front-matter row.
        out.extend_from_slice(&((c.token) as u32).to_le_bytes());
        // The number's own token index, or NONE. `\c` opens no node, so this is the only route from a chapter to its designator.
        out.extend_from_slice(&((c.designator) as u32).to_le_bytes());
        // The number read, or 0 for absent or malformed.
        out.extend_from_slice(&((c.number) as u16).to_le_bytes());
    }
}

/// One verse anchor and the range of verse numbers it names.
///
/// 18 bytes per row. `offsets` collects the position of every
/// source offset written, for the UTF-16 pass.
pub fn write_verses(rows: &[Verse], out: &mut Vec<u8>, offsets: &mut Offsets) {
    out.reserve(rows.len() * 18);
    for v in rows {
        offsets.push(out.len());
        // Where the anchor sits.
        out.extend_from_slice(&((v.at) as u32).to_le_bytes());
        // The `\v` marker's token index.
        out.extend_from_slice(&((v.token) as u32).to_le_bytes());
        // The number's own token index, or NONE. `\v` opens no node, so this is the only route from a verse to its designator.
        out.extend_from_slice(&((v.designator) as u32).to_le_bytes());
        // The enclosing chapter's number.
        out.extend_from_slice(&((v.chapter) as u16).to_le_bytes());
        // First verse named; 0 when the designator is absent or malformed.
        out.extend_from_slice(&((v.first) as u16).to_le_bytes());
        // Last verse named — a bridge `\v 5-7` names 5 through 7.
        out.extend_from_slice(&((v.last) as u16).to_le_bytes());
    }
}
