[package]
name = "sous-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "sous"
path = "src/main.rs"

[dependencies]
rayon.workspace = true
sous-core = { path = "../core" }
usfm_onion = { path = "../../onion", default-features = false }
usage.workspace = true
