//! @generated by `cargo run --bin codegen` from `tables::rows::ROWS`.
//! DO NOT EDIT — edit the authored rows or `tables::emit` and regenerate.
//! `tests/codegen_output_matches_input.rs` fails the build if this file is stale.
//!
//! Conformance target: USFM 3.2 only. Everything here is a projection of
//! the authored table; nothing is stated here that is not stated there.
//!
//! One `u128` per row. Consumers use the accessor functions and never touch
//! bits — the layout is codegen's business and may change freely.

#![allow(dead_code)]

use mise::extensions::ExtensionCategory;

use crate::tables::schema::{
    AttrStatus, Category, ClosingBehavior, HtmlElement, MarkerKind, Numbering, Payload, ScopeKind,
    SpecContext, SpellingShape, StructuralWhitespaceRequirement as Ws,
};

/// A row's position in `tables::rows::ROWS`. `u8`: ~153 rows, and
/// config-provided `\z` extensions fit in the headroom above them.
pub type MarkerIdx = u8;

// The narrowing is safe only while the table fits; growing past 256 rows is
// a design event (the token's marker_idx field is sized to match).
const _: () = assert!(ROW_COUNT <= 256);

/// The generic EMPTY row: an unconfigured `\z` extension, an unknown name,
/// an illegal digit. Inert, and the walker's cue to unwind [F].
pub const UNRESOLVED: MarkerIdx = 0;

// Bit layout — emitted from `tables::emit`'s field table.
const S_KIND: u32 = 0;
const M_KIND: u128 = 15;
const S_CATEGORY: u32 = 4;
const M_CATEGORY: u128 = 31;
const S_WS: u32 = 9;
const M_WS: u128 = 7;
const S_PAYLOAD: u32 = 12;
const M_PAYLOAD: u128 = 7;
const S_NUMBERING: u32 = 15;
const M_NUMBERING: u128 = 15;
const S_OPENS: u32 = 19;
const M_OPENS: u128 = 15;
const S_CLOSES: u32 = 23;
const M_CLOSES: u128 = 15;
const S_CLOSING: u32 = 27;
const M_CLOSING: u128 = 3;
const S_DEPRECATED: u32 = 29;
const M_DEPRECATED: u128 = 1;
const S_HTML: u32 = 30;
const M_HTML: u128 = 31;
const S_SHAPE: u32 = 35;
const M_SHAPE: u128 = 3;
const S_CONTEXTS: u32 = 37;
const M_CONTEXTS: u128 = 1048575;
const S_CONTRIBUTES: u32 = 57;
const M_CONTRIBUTES: u128 = 31;
const S_ATTR_OFF: u32 = 62;
const M_ATTR_OFF: u128 = 4095;
const S_ATTR_LEN: u32 = 74;
const M_ATTR_LEN: u128 = 15;
const S_DEFAULT_ATTR: u32 = 78;
const M_DEFAULT_ATTR: u128 = 15;

/// Bits used of the 128 available.
pub const BITS_USED: u32 = 82;

/// The packed table. Index IS the marker index.
#[rustfmt::skip]
static PACKED: [u128; 170] = [
    0x0000000000000100000000, //   0 <unresolved>
    0x000000006f070108280292, //   1 add
    0x000000006f070128280292, //   2 addpn
    0x0000001a00100540180c51, //   3 b
    0x000000006f0704882802a2, //   4 bd
    0x000000006f0704882802a2, //   5 bdit
    0x000000006f070108280292, //   6 bk
    0x0000001000100100002594, //   7 c
    0x000000006f070308282592, //   8 ca
    0x00000000700001082807ba, //   9 cat
    0x0000001800100080180431, //  10 cd
    0x0000001800180080180431, //  11 cl
    0x0000001a00100080180241, //  12 cls
    0x0000000000000300002591, //  13 cp
    0x0000001800100080180431, //  14 d
    0x000000006f070108280292, //  15 dc
    0x000000220f570108204323, //  16 ef
    0x000000006f070508280292, //  17 em
    0x00000020005002c04803a8, //  18 esb
    0x00000020005002c48003a8, //  19 esbe
    0x000000240f570108204333, //  20 ex
    0x000000220f570108204323, //  21 f
    0x0000000060000130280302, //  22 fdc
    0x000000220f570108204323, //  23 fe
    0x00180000225703882803e7, //  24 fig
    0x0000000060000110280302, //  25 fk
    0x0000000060000110280302, //  26 fl
    0x000000006f070108280302, //  27 fm
    0x0000000060000110280302, //  28 fp
    0x0000000060000110280302, //  29 fq
    0x0000000060000110280302, //  30 fqa
    0x0000000060000110280302, //  31 fr
    0x0000000060000110280302, //  32 ft
    0x0000000060000110280302, //  33 fv
    0x0000000060000110280302, //  34 fw
    0x0000000600008100198411, //  35 h
    0x0000000a00020540180221, //  36 ib
    0x00000002000081001015dd, //  37 id
    0x0000000600008100180411, //  38 ide
    0x0000000a00020080180221, //  39 ie
    0x0000000a00020080180221, //  40 iex
    0x0000000a00020080190221, //  41 ili
    0x0000000a00020080180221, //  42 im
    0x0000000a00020080180221, //  43 imi
    0x0000000a00020080180221, //  44 imq
    0x0000000a000700c01a0221, //  45 imt
    0x0000000a000200c0190221, //  46 imte
    0x0000000a000200801a0221, //  47 io
    0x00000000600201082802c2, //  48 ior
    0x0000000a000200c0180221, //  49 iot
    0x0000000a00120080180221, //  50 ip
    0x0000000a00020080180221, //  51 ipc
    0x0000000a00020080180221, //  52 ipi
    0x0000000a00020080180221, //  53 ipq
    0x0000000a00020080180221, //  54 ipr
    0x0000000a00020080198221, //  55 iq
    0x00000000600201082802c2, //  56 iqt
    0x0000000a000200c0190221, //  57 is
    0x000000006f0704c82802a2, //  58 it
    0x005801806f070348280292, //  59 jmp
    0x000000006f070108280292, //  60 k
    0x0000001c04100080180261, //  61 lf
    0x0000001c04100080180261, //  62 lh
    0x0000001c041001801a0261, //  63 li
    0x00000000640001082802e2, //  64 lik
    0x0000001c041001801a0261, //  65 lim
    0x0008030000100158300746, //  66 list
    0x0000001a00120080180241, //  67 lit
    0x00000000640001082802e2, //  68 litl
    0x00000000640001082f02e2, //  69 liv
    0x0000001a00100080180241, //  70 m
    0x0000001a00100080198241, //  71 mi
    0x0000001800100080180431, //  72 mr
    0x00000018001000c0198431, //  73 ms
    0x00000018000500c01a0431, //  74 mt
    0x00000018001000c0190431, //  75 mte
    0x0000001a00100080180241, //  76 nb
    0x000000006f070108280292, //  77 nd
    0x000000006f0701082802a2, //  78 no
    0x000000006f070108280292, //  79 ord
    0x0000001a00500080180241, //  80 p
    0x00000000001001000002b2, //  81 pb
    0x0000001a00100080180241, //  82 pc
    0x00040214002004005005c9, //  83 periph
    0x0000001a001000a0198241, //  84 ph
    0x0000001a00100080198241, //  85 pi
    0x0000001a00100080180241, //  86 pm
    0x0000001a00100080180241, //  87 pmc
    0x0000001a00100080180241, //  88 pmo
    0x0000001a00100080180241, //  89 pmr
    0x000000006f070108280292, //  90 pn
    0x000000006f070108280292, //  91 png
    0x0000001a00100080180241, //  92 po
    0x0000001a00100080180241, //  93 pr
    0x000000006f070128280292, //  94 pro
    0x0000001a001000801a0251, //  95 q
    0x0000001a001000c0180251, //  96 qa
    0x00000000620001082802d2, //  97 qac
    0x0000001a00100080180251, //  98 qc
    0x0000001a00100080180251, //  99 qd
    0x0000001a00100080198251, // 100 qm
    0x0000001a00100080180251, // 101 qr
    0x00000000620001082802d2, // 102 qs
    0x004c03800f071158328766, // 103 qt
    0x000000006f070908280292, // 104 qt
    0x0000001800100080180431, // 105 r
    0x004404406f070448280292, // 106 rb
    0x004401006f070348280292, // 107 ref
    0x0000000600008100180411, // 108 rem
    0x000000006f070108280292, // 109 rq
    0x00000018001000c01a0231, // 110 s
    0x000000006f0701082802a2, // 111 sc
    0x00000018001005401a0431, // 112 sd
    0x000000006f070108280292, // 113 sig
    0x000000006f070108280292, // 114 sls
    0x0000001800100080180431, // 115 sp
    0x0000001800100080180431, // 116 sr
    0x0000000600008100180411, // 117 sts
    0x000000006f0703082802a2, // 118 sup
    0x000404806f070108280292, // 119 ta
    0x0008030000100158300756, // 120 table
    0x0000001e080002804782fc, // 121 tc
    0x0000001e080002804782fc, // 122 tcc
    0x0000001e080002804782fc, // 123 tcr
    0x0000001e080002804782fc, // 124 th
    0x0000001e080002804782fc, // 125 thc
    0x0000001e080002804782fc, // 126 thr
    0x004404c06f070108280292, // 127 tl
    0x0000000600008100198411, // 128 toc
    0x0000000600008100198411, // 129 toca
    0x0000001e0810024038027b, // 130 tr
    0x000803000e100158300776, // 131 ts
    0x00000002000081001035dd, // 132 usfm
    0x000000000e102300002995, // 133 v
    0x000000006f070308282592, // 134 va
    0x0048050000100158300786, // 135 vid
    0x000000006f070308282592, // 136 vp
    0x004c05806f070108280292, // 137 w
    0x000000006f070108280292, // 138 wa
    0x000000006f070108280292, // 139 wg
    0x000000006f070108280292, // 140 wh
    0x000000006f070108280292, // 141 wj
    0x004404c06f070108280292, // 142 wl
    0x000000240f570108204333, // 143 x
    0x0000000060000130280312, // 144 xdc
    0x0000000060000110280312, // 145 xk
    0x0000000060000110280312, // 146 xnt
    0x0000000060000110280312, // 147 xo
    0x0000000060000110280312, // 148 xop
    0x0000000060000110280312, // 149 xot
    0x0000000060000110280312, // 150 xq
    0x000402406f070350280312, // 151 xt
    0x0000000060000110280312, // 152 xta
    0x0000000600008900180411, // 153 zheader
    0x00000018000508c0180431, // 154 ztitle
    0x0000000a00120880180221, // 155 zintro
    0x00000018001008c0180231, // 156 zsect
    0x0000001a00500880180241, // 157 zpara
    0x0000001c04100980180261, // 158 zlist
    0x0000001a00120880180241, // 159 zother
    0x000000220f570908204323, // 160 zfoot
    0x000000240f570908204333, // 161 zxref
    0x000000006f070908280292, // 162 zchar
    0x00000000600209082802c2, // 163 zichar
    0x00000000640009082802e2, // 164 zlchar
    0x0000000060000910280302, // 165 zfchar
    0x000402406f070b50280312, // 166 zxchar
    0x004c03800f071158300766, // 167 zms
    0x000803000e100158300776, // 168 zmsbare
    0x0000001e08000a804782fc, // 169 zcell
];

/// idx → canonical name. This array is what makes the table double as the
/// MARKER CATALOG: iterate it and you have every marker USFM 3.2 defines.
#[rustfmt::skip]
static NAMES: [&str; 170] = [
    "",
    "add",
    "addpn",
    "b",
    "bd",
    "bdit",
    "bk",
    "c",
    "ca",
    "cat",
    "cd",
    "cl",
    "cls",
    "cp",
    "d",
    "dc",
    "ef",
    "em",
    "esb",
    "esbe",
    "ex",
    "f",
    "fdc",
    "fe",
    "fig",
    "fk",
    "fl",
    "fm",
    "fp",
    "fq",
    "fqa",
    "fr",
    "ft",
    "fv",
    "fw",
    "h",
    "ib",
    "id",
    "ide",
    "ie",
    "iex",
    "ili",
    "im",
    "imi",
    "imq",
    "imt",
    "imte",
    "io",
    "ior",
    "iot",
    "ip",
    "ipc",
    "ipi",
    "ipq",
    "ipr",
    "iq",
    "iqt",
    "is",
    "it",
    "jmp",
    "k",
    "lf",
    "lh",
    "li",
    "lik",
    "lim",
    "list",
    "lit",
    "litl",
    "liv",
    "m",
    "mi",
    "mr",
    "ms",
    "mt",
    "mte",
    "nb",
    "nd",
    "no",
    "ord",
    "p",
    "pb",
    "pc",
    "periph",
    "ph",
    "pi",
    "pm",
    "pmc",
    "pmo",
    "pmr",
    "pn",
    "png",
    "po",
    "pr",
    "pro",
    "q",
    "qa",
    "qac",
    "qc",
    "qd",
    "qm",
    "qr",
    "qs",
    "qt",
    "qt",
    "r",
    "rb",
    "ref",
    "rem",
    "rq",
    "s",
    "sc",
    "sd",
    "sig",
    "sls",
    "sp",
    "sr",
    "sts",
    "sup",
    "ta",
    "table",
    "tc",
    "tcc",
    "tcr",
    "th",
    "thc",
    "thr",
    "tl",
    "toc",
    "toca",
    "tr",
    "ts",
    "usfm",
    "v",
    "va",
    "vid",
    "vp",
    "w",
    "wa",
    "wg",
    "wh",
    "wj",
    "wl",
    "x",
    "xdc",
    "xk",
    "xnt",
    "xo",
    "xop",
    "xot",
    "xq",
    "xt",
    "xta",
    "zheader",
    "ztitle",
    "zintro",
    "zsect",
    "zpara",
    "zlist",
    "zother",
    "zfoot",
    "zxref",
    "zchar",
    "zichar",
    "zlchar",
    "zfchar",
    "zxchar",
    "zms",
    "zmsbare",
    "zcell",
];

/// Every row's `defined_attributes`, concatenated; a row's slice is
/// `[ATTR_OFF .. ATTR_OFF + ATTR_LEN]`. Identical runs are shared.
#[rustfmt::skip]
static ATTRS: [(&str, AttrStatus); 25] = [
    ("src", AttrStatus::Required),
    ("size", AttrStatus::Required),
    ("ref", AttrStatus::Required),
    ("alt", AttrStatus::Optional),
    ("loc", AttrStatus::Optional),
    ("copy", AttrStatus::Optional),
    ("href", AttrStatus::Optional),
    ("title", AttrStatus::Optional),
    ("id", AttrStatus::Optional),
    ("link-href", AttrStatus::Deprecated),
    ("link-title", AttrStatus::Deprecated),
    ("link-id", AttrStatus::Deprecated),
    ("sid", AttrStatus::Optional),
    ("eid", AttrStatus::Optional),
    ("who", AttrStatus::Optional),
    ("sid", AttrStatus::Optional),
    ("eid", AttrStatus::Optional),
    ("gloss", AttrStatus::Optional),
    ("a-*", AttrStatus::Optional),
    ("lang", AttrStatus::Optional),
    ("ref", AttrStatus::Required),
    ("h", AttrStatus::Optional),
    ("lemma", AttrStatus::Optional),
    ("strong", AttrStatus::Optional),
    ("srcloc", AttrStatus::Optional),
];
/// Number of rows — the marker catalog's size.
pub const ROW_COUNT: usize = NAMES.len();

/// The first extension TEMPLATE row. Every index below this one is a
/// marker USFM 3.2 defines; every index at or above it is a template a
/// registered `\z` extension resolves to.
pub const FIRST_EXTENSION_ROW: MarkerIdx = 153;

/// Is this row a template — and so a row whose `name` is NOT the marker's?
///
/// The ONE `is this an extension` predicate in the engine, and it exists
/// for one purpose: a template cannot carry the spelling a document used,
/// so anything showing a name to a human or writing one to an export reads
/// it off the token span instead. Nothing branches on it to decide what a
/// marker DOES — that is the row's, which is the point of templates.
#[inline]
pub fn is_extension(idx: MarkerIdx) -> bool {
    idx >= FIRST_EXTENSION_ROW
}
/// The template row a spec `\category` word behaves as. TOTAL: the two
/// USX-internal words answer [`UNRESOLVED`], which is what "registers
/// nothing" means at a call site.
#[rustfmt::skip]
pub fn template_for(category: ExtensionCategory) -> MarkerIdx {
    match category {
        ExtensionCategory::Header => 153, // zheader
        ExtensionCategory::Title => 154, // ztitle
        ExtensionCategory::Introduction => 155, // zintro
        ExtensionCategory::SectionPara => 156, // zsect
        ExtensionCategory::VersePara => 157, // zpara
        ExtensionCategory::List => 158, // zlist
        ExtensionCategory::OtherPara => 159, // zother
        ExtensionCategory::CrossReference => 161, // zxref
        ExtensionCategory::Footnote => 160, // zfoot
        ExtensionCategory::Char => 162, // zchar
        ExtensionCategory::IntroChar => 163, // zichar
        ExtensionCategory::ListChar => 164, // zlchar
        ExtensionCategory::FootnoteChar => 165, // zfchar
        ExtensionCategory::CrossReferenceChar => 166, // zxchar
        ExtensionCategory::Milestone => 167, // zms
        ExtensionCategory::Attribute => UNRESOLVED,
        ExtensionCategory::Cell => 169, // zcell
        ExtensionCategory::Standalone => 168, // zmsbare
        ExtensionCategory::Internal => UNRESOLVED,
    }
}

#[inline]
fn field(idx: MarkerIdx, shift: u32, mask: u128) -> u32 {
    ((PACKED[idx as usize] >> shift) & mask) as u32
}

/// Coarse spec kind.
#[inline]
pub fn kind(idx: MarkerIdx) -> MarkerKind {
    match field(idx, S_KIND, M_KIND) {
        0 => MarkerKind::Unknown,
        1 => MarkerKind::Paragraph,
        2 => MarkerKind::Character,
        3 => MarkerKind::Note,
        4 => MarkerKind::Chapter,
        5 => MarkerKind::Verse,
        6 => MarkerKind::Milestone,
        7 => MarkerKind::Figure,
        8 => MarkerKind::Sidebar,
        9 => MarkerKind::Periph,
        10 => MarkerKind::Meta,
        11 => MarkerKind::TableRow,
        12 => MarkerKind::TableCell,
        13 => MarkerKind::Header,
        _ => unreachable!(),
    }
}

/// Fine spec category — behavior-bearing, see the schema's note on `\pb`.
#[inline]
pub fn category(idx: MarkerIdx) -> Category {
    match field(idx, S_CATEGORY, M_CATEGORY) {
        0 => Category::Unknown,
        1 => Category::ParaIdentification,
        2 => Category::ParaIntroductions,
        3 => Category::ParaTitlesSections,
        4 => Category::ParaBody,
        5 => Category::ParaPoetry,
        6 => Category::ParaLists,
        7 => Category::ParaTables,
        8 => Category::ParaPeripheral,
        9 => Category::CharTextFeatures,
        10 => Category::CharFormatting,
        11 => Category::CharBreaks,
        12 => Category::CharIntroductions,
        13 => Category::CharPoetry,
        14 => Category::CharLists,
        15 => Category::CharTables,
        16 => Category::CharNotesFootnote,
        17 => Category::CharNotesCrossReference,
        18 => Category::NoteFootnote,
        19 => Category::NoteCrossReference,
        20 => Category::MilestoneList,
        21 => Category::MilestoneTable,
        22 => Category::MilestoneQt,
        23 => Category::MilestoneTs,
        24 => Category::MilestoneVid,
        25 => Category::ChapterVerse,
        26 => Category::Sidebar,
        27 => Category::Meta,
        28 => Category::Peripheral,
        29 => Category::DocumentStructure,
        30 => Category::Figure,
        _ => unreachable!(),
    }
}

/// Structural whitespace required after the marker name — the scanner's
/// per-class delimiter fold rule.
#[inline]
pub fn ws_after_name(idx: MarkerIdx) -> Ws {
    match field(idx, S_WS, M_WS) {
        0 => Ws::NotRequired,
        1 => Ws::TagEndDelimiter,
        2 => Ws::AtLeastOneHorizontalWhitespace,
        3 => Ws::OptionalHorizontalWhitespace,
        4 => Ws::AtLeastOneWhitespace,
        5 => Ws::OptionalWhitespace,
        6 => Ws::SingleNewline,
        7 => Ws::AtLeastOneNewline,
        _ => unreachable!(),
    }
}

/// The argument consumed right after the delimiter.
#[inline]
pub fn payload(idx: MarkerIdx) -> Payload {
    match field(idx, S_PAYLOAD, M_PAYLOAD) {
        0 => Payload::None,
        1 => Payload::BookCode,
        2 => Payload::Designator,
        3 => Payload::Version,
        4 => Payload::NoteCaller,
        _ => unreachable!(),
    }
}

/// How this marker's scope ends.
#[inline]
pub fn closing(idx: MarkerIdx) -> ClosingBehavior {
    match field(idx, S_CLOSING, M_CLOSING) {
        0 => ClosingBehavior::None,
        1 => ClosingBehavior::RequiredExplicit,
        2 => ClosingBehavior::OptionalExplicitUntilNoteEnd,
        3 => ClosingBehavior::SelfClosingMilestone,
        _ => unreachable!(),
    }
}

/// Which spellings of the name this row claims.
#[inline]
pub fn shape(idx: MarkerIdx) -> SpellingShape {
    match field(idx, S_SHAPE, M_SHAPE) {
        0 => SpellingShape::Any,
        1 => SpellingShape::PlainOnly,
        2 => SpellingShape::MilestoneOnly,
        _ => unreachable!(),
    }
}

/// The scope an occurrence PUSHES A FRAME for, or `None`. Pushing only —
/// displacement is the walker's pop over `context_mask`, never a column.
#[inline]
pub fn opens_scope(idx: MarkerIdx) -> Option<ScopeKind> {
    match field(idx, S_OPENS, M_OPENS) {
        0 => None,
        1 => Some(ScopeKind::Unknown),
        2 => Some(ScopeKind::Header),
        3 => Some(ScopeKind::Para),
        4 => Some(ScopeKind::Note),
        5 => Some(ScopeKind::Character),
        6 => Some(ScopeKind::Milestone),
        7 => Some(ScopeKind::TableRow),
        8 => Some(ScopeKind::TableCell),
        9 => Some(ScopeKind::Sidebar),
        10 => Some(ScopeKind::Periph),
        11 => Some(ScopeKind::Table),
        12 => Some(ScopeKind::List),
        _ => unreachable!(),
    }
}

/// The scope an occurrence CLOSES — `esbe` and nothing else today.
#[inline]
pub fn closes_scope(idx: MarkerIdx) -> Option<ScopeKind> {
    match field(idx, S_CLOSES, M_CLOSES) {
        0 => None,
        1 => Some(ScopeKind::Unknown),
        2 => Some(ScopeKind::Header),
        3 => Some(ScopeKind::Para),
        4 => Some(ScopeKind::Note),
        5 => Some(ScopeKind::Character),
        6 => Some(ScopeKind::Milestone),
        7 => Some(ScopeKind::TableRow),
        8 => Some(ScopeKind::TableCell),
        9 => Some(ScopeKind::Sidebar),
        10 => Some(ScopeKind::Periph),
        11 => Some(ScopeKind::Table),
        12 => Some(ScopeKind::List),
        _ => unreachable!(),
    }
}

/// Default HTML element class for export. A default, not a mandate.
#[inline]
pub fn html_element(idx: MarkerIdx) -> Option<HtmlElement> {
    match field(idx, S_HTML, M_HTML) {
        0 => None,
        1 => Some(HtmlElement::Transparent),
        2 => Some(HtmlElement::Para),
        3 => Some(HtmlElement::Heading),
        4 => Some(HtmlElement::Span),
        5 => Some(HtmlElement::SelfClosingSpan),
        6 => Some(HtmlElement::ListItem),
        7 => Some(HtmlElement::ListContainer),
        8 => Some(HtmlElement::Table),
        9 => Some(HtmlElement::TableRow),
        10 => Some(HtmlElement::TableCell),
        11 => Some(HtmlElement::Aside),
        12 => Some(HtmlElement::Sup),
        13 => Some(HtmlElement::Anchor),
        14 => Some(HtmlElement::Figure),
        15 => Some(HtmlElement::Image),
        16 => Some(HtmlElement::Section),
        17 => Some(HtmlElement::Ruby),
        18 => Some(HtmlElement::Bold),
        19 => Some(HtmlElement::Italic),
        20 => Some(HtmlElement::Em),
        21 => Some(HtmlElement::Div),
        _ => unreachable!(),
    }
}

/// What context an open frame of this row puts its children in — BAKED from
/// `schema::contributes_context(kind, category)`, so the walker's push-time
/// frame stamp is one array read [I]. `None` means the frame is transparent.
#[inline]
pub fn contributes_context(idx: MarkerIdx) -> Option<SpecContext> {
    match field(idx, S_CONTRIBUTES, M_CONTRIBUTES) {
        0 => None,
        1 => Some(SpecContext::Scripture),
        2 => Some(SpecContext::BookIdentification),
        3 => Some(SpecContext::BookHeaders),
        4 => Some(SpecContext::BookTitles),
        5 => Some(SpecContext::BookIntroduction),
        6 => Some(SpecContext::BookIntroductionEndTitles),
        7 => Some(SpecContext::BookChapterLabel),
        8 => Some(SpecContext::ChapterContent),
        9 => Some(SpecContext::Peripheral),
        10 => Some(SpecContext::PeripheralContent),
        11 => Some(SpecContext::PeripheralDivision),
        12 => Some(SpecContext::Section),
        13 => Some(SpecContext::Para),
        14 => Some(SpecContext::List),
        15 => Some(SpecContext::Table),
        16 => Some(SpecContext::Sidebar),
        17 => Some(SpecContext::Footnote),
        18 => Some(SpecContext::CrossReference),
        _ => unreachable!(),
    }
}

/// Canonical name. `""` for [`UNRESOLVED`].
#[inline]
pub fn name(idx: MarkerIdx) -> &'static str {
    NAMES[idx as usize]
}

/// Spec-deprecated but still legal to read. Lint only; never affects scanning.
#[inline]
pub fn deprecated(idx: MarkerIdx) -> bool {
    field(idx, S_DEPRECATED, M_DEPRECATED) != 0
}

/// Legal numeric suffixes for this row's spellings. The digit itself always
/// lives in the token's span; the bare form is ALWAYS legal [D].
#[inline]
pub fn numbering(idx: MarkerIdx) -> Numbering {
    match field(idx, S_NUMBERING, M_NUMBERING) {
        0 => Numbering::Unnumbered,
        14 => Numbering::Unbounded,
        15 => Numbering::TableColumns,
        cap => Numbering::UpTo(cap as u8),
    }
}

/// Attributes USFM 3.2 defines for this marker, in spec order.
#[inline]
pub fn defined_attributes(idx: MarkerIdx) -> &'static [(&'static str, AttrStatus)] {
    let off = field(idx, S_ATTR_OFF, M_ATTR_OFF) as usize;
    let len = field(idx, S_ATTR_LEN, M_ATTR_LEN) as usize;
    &ATTRS[off..off + len]
}

/// Which defined attribute an unnamed default value binds to
/// (`\w word|lemma-value\w*` → `lemma`). Not always the first entry.
#[inline]
pub fn default_attribute(idx: MarkerIdx) -> Option<&'static str> {
    match field(idx, S_DEFAULT_ATTR, M_DEFAULT_ATTR) {
        0 => None,
        n => Some(defined_attributes(idx)[n as usize - 1].0),
    }
}

/// The context mask — EXACTLY the row's authored `allowed_contexts`, bit
/// positions per `context_bit`. Nothing is added.
///
/// Never widened by the generator: the 3.2 docs state contexts PER MARKER
/// and they genuinely differ (`bd` lists Footnote, `fm` does not). If a
/// marker is legal somewhere, its ROW says so.
#[inline]
pub fn context_mask(idx: MarkerIdx) -> u32 {
    field(idx, S_CONTEXTS, M_CONTEXTS)
}

/// May this marker legally appear in `ctx`? One AND against the top frame's
/// stamped context — the walker's recovery predicate, no stack walk [I].
#[inline]
pub fn allowed_in(idx: MarkerIdx, ctx: SpecContext) -> bool {
    context_mask(idx) & context_bit(ctx) != 0
}

/// A context's bit position in the context masks above.
#[inline]
pub const fn context_bit(ctx: SpecContext) -> u32 {
    1 << match ctx {
        SpecContext::Scripture => 0,
        SpecContext::BookIdentification => 1,
        SpecContext::BookHeaders => 2,
        SpecContext::BookTitles => 3,
        SpecContext::BookIntroduction => 4,
        SpecContext::BookIntroductionEndTitles => 5,
        SpecContext::BookChapterLabel => 6,
        SpecContext::ChapterContent => 7,
        SpecContext::Peripheral => 8,
        SpecContext::PeripheralContent => 9,
        SpecContext::PeripheralDivision => 10,
        SpecContext::Section => 11,
        SpecContext::Para => 12,
        SpecContext::List => 13,
        SpecContext::Table => 14,
        SpecContext::Sidebar => 15,
        SpecContext::Footnote => 16,
        SpecContext::CrossReference => 17,
    }
}

/// Resolve a marker lexeme to its row index.
///
/// `lexeme` is the marker NAME as it was spelled, without the leading `\`
/// and without the closing `*` — `b"q2"`, `b"qt3-s"`, `b"tc1-2"`. `shape`
/// is what the lexer already classified, which is what makes the overloaded
/// names free to disambiguate.
///
/// The strip order is fixed by ruling [G]: `-s`/`-e` FIRST, then the digits.
/// One compare per lookup: every canonical name is pure lowercase ASCII, so
/// the alpha stem IS the name and the trailing run is only ever a level or a
/// column span (`tables::emit` asserts this, so a digit-bearing canonical
/// name panics the generator rather than silently resolving to its stem).
///
/// Anything that does not resolve — an unknown name, `\s5` — returns
/// [`UNRESOLVED`], which is a real inert row and not an error path.
///
/// This is the SPEC table's lookup and knows nothing about extensions: every
/// `z` lexeme leaves here as [`UNRESOLVED`]. A registered one resolves through
/// [`crate::extensions::marker_idx`], which is the door the scanner calls and
/// the only place a template row is reachable.
#[inline]
pub fn marker_idx(lexeme: &[u8], shape: SpellingShape) -> MarkerIdx {
    // A belt, not the door: the scanner routes every `z` lexeme to the
    // registry and never sends one here [F]. It stays because this lookup is
    // TOTAL on its own terms — no `z` name is a spec row — and because it is
    // what makes the template rows unreachable by name.
    if lexeme.first().is_none_or(|b| *b == b'z') {
        return UNRESOLVED;
    }
    let stripped = match lexeme {
        [head @ .., b'-', b's' | b'e'] => head,
        whole => whole,
    };
    let stem_len = stripped
        .iter()
        .position(|b| !b.is_ascii_lowercase())
        .unwrap_or(stripped.len());
    let (stem, rest) = stripped.split_at(stem_len);
    let Some(key) = name_key(stem) else {
        return UNRESOLVED;
    };
    let idx = by_name(key, shape);
    if idx != UNRESOLVED && digits_ok(idx, rest) {
        idx
    } else {
        UNRESOLVED
    }
}

/// A name as the u64 the match compares: little-endian bytes zero-padded, so
/// no length compare is needed. `None` when it cannot be a canonical name.
#[inline]
fn name_key(name: &[u8]) -> Option<u64> {
    if name.is_empty() || name.len() > 8 {
        return None;
    }
    let mut key = [0u8; 8];
    key[..name.len()].copy_from_slice(name);
    Some(u64::from_le_bytes(key))
}

/// The name table itself: one integer match, the compiler's decision tree.
/// Overloaded names (`qt`) cost one extra compare against the shape the lexer
/// already classified; every other name resolves on the u64 alone.
#[inline]
#[rustfmt::skip]
fn by_name(key: u64, shape: SpellingShape) -> MarkerIdx {
    match key {
        0x0000000000000062 => 3, // b
        0x0000000000000063 => 7, // c
        0x0000000000000064 => 14, // d
        0x0000000000000066 => 21, // f
        0x0000000000000068 => 35, // h
        0x000000000000006b => 60, // k
        0x000000000000006d => 70, // m
        0x0000000000000070 => 80, // p
        0x0000000000000071 => 95, // q
        0x0000000000000072 => 105, // r
        0x0000000000000073 => 110, // s
        0x0000000000000076 => 133, // v
        0x0000000000000077 => 137, // w
        0x0000000000000078 => 143, // x
        0x0000000000006163 => 8, // ca
        0x0000000000006171 => 96, // qa
        0x0000000000006174 => 119, // ta
        0x0000000000006176 => 134, // va
        0x0000000000006177 => 138, // wa
        0x0000000000006269 => 36, // ib
        0x000000000000626e => 76, // nb
        0x0000000000006270 => 81, // pb
        0x0000000000006272 => 106, // rb
        0x0000000000006364 => 15, // dc
        0x0000000000006370 => 82, // pc
        0x0000000000006371 => 98, // qc
        0x0000000000006373 => 111, // sc
        0x0000000000006374 => 121, // tc
        0x0000000000006462 => 4, // bd
        0x0000000000006463 => 10, // cd
        0x0000000000006469 => 37, // id
        0x000000000000646e => 77, // nd
        0x0000000000006471 => 99, // qd
        0x0000000000006473 => 112, // sd
        0x0000000000006566 => 23, // fe
        0x0000000000006569 => 39, // ie
        0x0000000000006665 => 16, // ef
        0x000000000000666c => 61, // lf
        0x0000000000006777 => 139, // wg
        0x000000000000686c => 62, // lh
        0x0000000000006870 => 84, // ph
        0x0000000000006874 => 124, // th
        0x0000000000006877 => 140, // wh
        0x000000000000696c => 63, // li
        0x000000000000696d => 71, // mi
        0x0000000000006970 => 85, // pi
        0x0000000000006a77 => 141, // wj
        0x0000000000006b62 => 6, // bk
        0x0000000000006b66 => 25, // fk
        0x0000000000006b78 => 145, // xk
        0x0000000000006c63 => 11, // cl
        0x0000000000006c66 => 26, // fl
        0x0000000000006c74 => 127, // tl
        0x0000000000006c77 => 142, // wl
        0x0000000000006d65 => 17, // em
        0x0000000000006d66 => 27, // fm
        0x0000000000006d69 => 42, // im
        0x0000000000006d70 => 86, // pm
        0x0000000000006d71 => 100, // qm
        0x0000000000006e70 => 90, // pn
        0x0000000000006f69 => 47, // io
        0x0000000000006f6e => 78, // no
        0x0000000000006f70 => 92, // po
        0x0000000000006f78 => 147, // xo
        0x0000000000007063 => 13, // cp
        0x0000000000007066 => 28, // fp
        0x0000000000007069 => 50, // ip
        0x0000000000007073 => 115, // sp
        0x0000000000007076 => 136, // vp
        0x0000000000007166 => 29, // fq
        0x0000000000007169 => 55, // iq
        0x0000000000007172 => 109, // rq
        0x0000000000007178 => 150, // xq
        0x0000000000007266 => 31, // fr
        0x000000000000726d => 72, // mr
        0x0000000000007270 => 93, // pr
        0x0000000000007271 => 101, // qr
        0x0000000000007273 => 116, // sr
        0x0000000000007274 => 130, // tr
        0x0000000000007369 => 57, // is
        0x000000000000736d => 73, // ms
        0x0000000000007371 => 102, // qs
        0x0000000000007374 => 131, // ts
        0x0000000000007466 => 32, // ft
        0x0000000000007469 => 58, // it
        0x000000000000746d => 74, // mt
        0x0000000000007471 => match shape { // qt
            SpellingShape::Any => UNRESOLVED,
            SpellingShape::PlainOnly => 104,
            SpellingShape::MilestoneOnly => 103,
        },
        0x0000000000007478 => 151, // xt
        0x0000000000007666 => 33, // fv
        0x0000000000007766 => 34, // fw
        0x0000000000007865 => 20, // ex
        0x0000000000617166 => 30, // fqa
        0x0000000000617478 => 152, // xta
        0x0000000000627365 => 18, // esb
        0x0000000000636171 => 97, // qac
        0x0000000000636374 => 122, // tcc
        0x0000000000636466 => 22, // fdc
        0x0000000000636478 => 144, // xdc
        0x0000000000636874 => 125, // thc
        0x0000000000636d70 => 87, // pmc
        0x0000000000636f74 => 128, // toc
        0x0000000000637069 => 51, // ipc
        0x0000000000646461 => 1, // add
        0x0000000000646976 => 135, // vid
        0x000000000064726f => 79, // ord
        0x0000000000656469 => 38, // ide
        0x000000000065746d => 75, // mte
        0x0000000000666572 => 107, // ref
        0x0000000000676966 => 24, // fig
        0x0000000000676973 => 113, // sig
        0x0000000000676e70 => 91, // png
        0x0000000000696c69 => 41, // ili
        0x0000000000696d69 => 43, // imi
        0x0000000000697069 => 52, // ipi
        0x00000000006b696c => 64, // lik
        0x00000000006d6572 => 108, // rem
        0x00000000006d696c => 65, // lim
        0x00000000006f6d70 => 88, // pmo
        0x00000000006f7270 => 94, // pro
        0x0000000000706d6a => 59, // jmp
        0x0000000000706f78 => 148, // xop
        0x0000000000707573 => 118, // sup
        0x0000000000716d69 => 44, // imq
        0x0000000000717069 => 53, // ipq
        0x0000000000726374 => 123, // tcr
        0x0000000000726874 => 126, // thr
        0x0000000000726d70 => 89, // pmr
        0x0000000000726f69 => 48, // ior
        0x0000000000727069 => 54, // ipr
        0x0000000000736c63 => 12, // cls
        0x0000000000736c73 => 114, // sls
        0x0000000000737473 => 117, // sts
        0x0000000000746163 => 9, // cat
        0x000000000074696c => 67, // lit
        0x0000000000746d69 => 45, // imt
        0x0000000000746e78 => 146, // xnt
        0x0000000000746f69 => 49, // iot
        0x0000000000746f78 => 149, // xot
        0x0000000000747169 => 56, // iqt
        0x000000000076696c => 69, // liv
        0x0000000000786569 => 40, // iex
        0x0000000061636f74 => 129, // toca
        0x0000000065627365 => 19, // esbe
        0x0000000065746d69 => 46, // imte
        0x000000006c74696c => 68, // litl
        0x000000006d667375 => 132, // usfm
        0x0000000074696462 => 5, // bdit
        0x000000007473696c => 66, // list
        0x000000656c626174 => 120, // table
        0x0000006e70646461 => 2, // addpn
        0x0000687069726570 => 83, // periph
        _ => UNRESOLVED,
    }
}

/// Is the trailing run after the alpha stem a legal spelling of `idx`?
///
/// The bare form is always legal [D]. `TableColumns` accepts anything
/// because the run is PAYLOAD, not a level — `\tc1-2` is a column span the
/// marker's own interpreter reads off the token span [O].
#[inline]
fn digits_ok(idx: MarkerIdx, rest: &[u8]) -> bool {
    match numbering(idx) {
        Numbering::TableColumns => true,
        Numbering::Unnumbered => rest.is_empty(),
        Numbering::Unbounded => rest.iter().all(u8::is_ascii_digit),
        Numbering::UpTo(cap) => match rest {
            [] => true,
            digits if digits.iter().all(u8::is_ascii_digit) => {
                let level = digits
                    .iter()
                    .fold(0u32, |acc, b| acc.saturating_mul(10) + u32::from(b - b'0'));
                (1..=u32::from(cap)).contains(&level)
            }
            _ => false,
        },
    }
}

/// `\v` is illegal inside a paragraph opened by one of these markers — a
/// 3.2 rule keyed on the ENCLOSING paragraph, which no context mask can
/// express. A frame carries the `marker_idx` that opened it, so this is one
/// bit test on that index.
///
/// 18 markers set a bit. 0 rail members are ruled ERRATA with no row and no
/// bit () — see `schema::V_FORBIDDEN_IN_PARAGRAPHS`.
#[rustfmt::skip]
static V_FORBIDDEN: [u64; 3] = [
    0x0004010000002c00,
    0x0039520100020b08,
    0x0000000000000000,
];
/// Does a paragraph opened by `idx` forbid `\v`? Lint's rule, not the
/// scanner's.
#[inline]
pub fn forbids_verse(idx: MarkerIdx) -> bool {
    let idx = idx as usize;
    V_FORBIDDEN[idx / 64] >> (idx % 64) & 1 != 0
}
