//! `src/toc/generated.rs` and `toc-reader.ts` are what the current census
//! schema + generator would produce. On failure the fix is always
//! `cargo run -p usfm_galley --bin codegen`.
//!
//! They exist because both artifacts are CHECKED IN — consumers never run
//! codegen, so nothing else would notice a schema edit that was not
//! regenerated, and the two ends of the wire would quietly disagree.

use usfm_galley::find::wire::{emit as find_emit, schema as find_schema};
use usfm_galley::toc::{emit, schema};

const CHECKED_IN_WRITER: &str = include_str!("../src/toc/generated.rs");
const CHECKED_IN_READER: &str = include_str!("../toc-reader.ts");
const CHECKED_IN_FIND_WRITER: &str = include_str!("../src/find/wire/generated.rs");
const CHECKED_IN_FIND_READER: &str = include_str!("../find-reader.ts");

/// Both artifacts are regenerated by the same bin.
const FIX: &str = "cargo run -p usfm_galley --bin codegen";

/// The census wire's WRITER. Stale here means the writer disagrees with the
/// schema the reader was generated from — the exact drift this design exists
/// to make impossible.
#[test]
fn census_writer_is_not_stale() {
    let fresh = emit::generated_rs();
    assert!(
        fresh == CHECKED_IN_WRITER,
        "{}",
        ticket::stale::first_difference("src/toc/generated.rs", FIX, &fresh, CHECKED_IN_WRITER)
    );
}

/// The census wire's READER. Stale here means the JS package ships a decoder
/// for a buffer the binary beside it no longer writes.
#[test]
fn census_reader_is_not_stale() {
    let fresh = emit::reader_ts();
    assert!(
        fresh == CHECKED_IN_READER,
        "{}",
        ticket::stale::first_difference("toc-reader.ts", FIX, &fresh, CHECKED_IN_READER)
    );
}

/// Find's WRITER. Its bytes are `VERSION` 1's bytes — `find::wire`'s own byte
/// gate holds that — so a drift here is a drift away from what consumers
/// already decode.
#[test]
fn find_writer_is_not_stale() {
    let fresh = find_emit::generated_rs();
    assert!(
        fresh == CHECKED_IN_FIND_WRITER,
        "{}",
        ticket::stale::first_difference(
            "src/find/wire/generated.rs",
            FIX,
            &fresh,
            CHECKED_IN_FIND_WRITER
        )
    );
}

/// Find's READER.
#[test]
fn find_reader_is_not_stale() {
    let fresh = find_emit::reader_ts();
    assert!(
        fresh == CHECKED_IN_FIND_READER,
        "{}",
        ticket::stale::first_difference("find-reader.ts", FIX, &fresh, CHECKED_IN_FIND_READER)
    );
}

/// One level of tail, and no more. A `Repeat` whose sub-record itself had one
/// would be a grammar, and neither emitter walks past the first run — so the
/// shape is refused here rather than mis-generated there.
#[test]
fn no_tail_carries_a_tail_of_its_own() {
    for record in schema::RECORDS.iter().chain(find_schema::RECORDS) {
        if let Some(run) = record.tail.as_ref() {
            assert!(
                run.of.tail.is_none(),
                "{}'s tail nests another in {}",
                record.name,
                run.of.name
            );
            assert!(
                record.fields.iter().any(|field| field.name == run.count),
                "{}'s tail counts a field it does not have: {}",
                record.name,
                run.count
            );
        }
    }
}

/// Every record's stride is the sum of its field widths — the property that
/// makes both ends' `at + offset` arithmetic sound. Nothing pads, because
/// nothing casts a Rust struct.
#[test]
fn census_strides_are_the_sum_of_their_fields() {
    for record in schema::RECORDS.iter().chain(find_schema::RECORDS) {
        let sum: usize = record.fields.iter().map(|f| f.width.bytes()).sum();
        assert_eq!(
            record.stride(),
            sum,
            "{} stride disagrees with its fields",
            record.name
        );
    }
}

/// The reader is generated from the constants the encoder writes, so the two
/// cannot disagree about where a field is — but a HAND-written envelope offset
/// that overlapped its neighbour would still encode and decode consistently
/// while losing a field. The directory's entries tile their stride exactly.
#[test]
fn the_directory_entry_tiles_its_stride() {
    let mut offsets = [
        (schema::DIRECTORY_CODE_OFFSET, 4),
        (schema::DIRECTORY_CHAPTERS_AT_OFFSET, 4),
        (schema::DIRECTORY_CHAPTER_ROWS_OFFSET, 4),
        (schema::DIRECTORY_VERSES_AT_OFFSET, 4),
        (schema::DIRECTORY_VERSE_ROWS_OFFSET, 4),
        (schema::DIRECTORY_ID_AT_OFFSET, 4),
        (schema::DIRECTORY_ID_LEN_OFFSET, 4),
    ];
    offsets.sort_unstable();
    let mut at = 0;
    for (offset, width) in offsets {
        assert_eq!(offset, at, "the directory has a hole or an overlap at {at}");
        at += width;
    }
    assert_eq!(at, schema::DIRECTORY_ENTRY_BYTES);
    assert_eq!(
        schema::DIRECTORY_CODE_TERMINATOR_OFFSET,
        schema::DIRECTORY_CODE_OFFSET + 3,
        "the code's NUL sits after its three bytes"
    );
}
